;!knitout-2
;;Machine: SWG091N2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Gauge: 7
;;Width: 250
;;Position: Center
;Resetting to sheet s0:g4 of 4
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
; Peel sheet 2 relative to 0
; Peel sheet 3 relative to 0
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
; Peel sheet 2 relative to 0
; Peel sheet 3 relative to 0
;Resetting to sheet s2:g4 of 4
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
; Peel sheet 2 relative to 2
; Peel sheet 3 relative to 2
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
; Peel sheet 2 relative to 2
; Peel sheet 3 relative to 2
;Resetting to sheet s1:g4 of 4
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
; Peel sheet 3 relative to 1
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
; Peel sheet 3 relative to 1
;Resetting to sheet s3:g4 of 4
; Peel sheet 0 relative to 3
; Peel sheet 1 relative to 3
; Peel sheet 2 relative to 3
; Peel sheet 3 relative to 3
; Peel sheet 0 relative to 3
; Peel sheet 1 relative to 3
; Peel sheet 2 relative to 3
; Peel sheet 3 relative to 3
inhook  1 ;Activating carrier  1
;Resetting to sheet s0:g4 of 4
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
; Peel sheet 2 relative to 0
; Peel sheet 3 relative to 0
tuck - f116 1 ; tuck loops: [0 on yarn C1.1]. 
tuck - b114 1 ; tuck loops: [1 on yarn C1.1]. 
tuck - f108 1 ; tuck loops: [2 on yarn C1.1]. 
tuck - b106 1 ; tuck loops: [3 on yarn C1.1]. 
tuck - f100 1 ; tuck loops: [4 on yarn C1.1]. 
tuck - b98 1 ; tuck loops: [5 on yarn C1.1]. 
tuck - f92 1 ; tuck loops: [6 on yarn C1.1]. 
tuck - b90 1 ; tuck loops: [7 on yarn C1.1]. 
tuck - f84 1 ; tuck loops: [8 on yarn C1.1]. 
tuck - b82 1 ; tuck loops: [9 on yarn C1.1]. 
tuck - f76 1 ; tuck loops: [10 on yarn C1.1]. 
tuck - b74 1 ; tuck loops: [11 on yarn C1.1]. 
tuck - f68 1 ; tuck loops: [12 on yarn C1.1]. 
tuck - b66 1 ; tuck loops: [13 on yarn C1.1]. 
tuck - f60 1 ; tuck loops: [14 on yarn C1.1]. 
tuck - b58 1 ; tuck loops: [15 on yarn C1.1]. 
tuck - f52 1 ; tuck loops: [16 on yarn C1.1]. 
tuck - b50 1 ; tuck loops: [17 on yarn C1.1]. 
tuck - f44 1 ; tuck loops: [18 on yarn C1.1]. 
tuck - b42 1 ; tuck loops: [19 on yarn C1.1]. 
tuck - f36 1 ; tuck loops: [20 on yarn C1.1]. 
tuck - b34 1 ; tuck loops: [21 on yarn C1.1]. 
tuck - f28 1 ; tuck loops: [22 on yarn C1.1]. 
tuck - b26 1 ; tuck loops: [23 on yarn C1.1]. 
tuck - f20 1 ; tuck loops: [24 on yarn C1.1]. 
tuck - b18 1 ; tuck loops: [25 on yarn C1.1]. 
tuck - f12 1 ; tuck loops: [26 on yarn C1.1]. 
tuck - b10 1 ; tuck loops: [27 on yarn C1.1]. 
tuck - f4 1 ; tuck loops: [28 on yarn C1.1]. 
tuck - b2 1 ; tuck loops: [29 on yarn C1.1]. 
releasehook  1 ;
tuck + f0 1 ; tuck loops: [30 on yarn C1.1]. 
tuck + b6 1 ; tuck loops: [31 on yarn C1.1]. 
tuck + f8 1 ; tuck loops: [32 on yarn C1.1]. 
tuck + b14 1 ; tuck loops: [33 on yarn C1.1]. 
tuck + f16 1 ; tuck loops: [34 on yarn C1.1]. 
tuck + b22 1 ; tuck loops: [35 on yarn C1.1]. 
tuck + f24 1 ; tuck loops: [36 on yarn C1.1]. 
tuck + b30 1 ; tuck loops: [37 on yarn C1.1]. 
tuck + f32 1 ; tuck loops: [38 on yarn C1.1]. 
tuck + b38 1 ; tuck loops: [39 on yarn C1.1]. 
tuck + f40 1 ; tuck loops: [40 on yarn C1.1]. 
tuck + b46 1 ; tuck loops: [41 on yarn C1.1]. 
tuck + f48 1 ; tuck loops: [42 on yarn C1.1]. 
tuck + b54 1 ; tuck loops: [43 on yarn C1.1]. 
tuck + f56 1 ; tuck loops: [44 on yarn C1.1]. 
tuck + b62 1 ; tuck loops: [45 on yarn C1.1]. 
tuck + f64 1 ; tuck loops: [46 on yarn C1.1]. 
tuck + b70 1 ; tuck loops: [47 on yarn C1.1]. 
tuck + f72 1 ; tuck loops: [48 on yarn C1.1]. 
tuck + b78 1 ; tuck loops: [49 on yarn C1.1]. 
tuck + f80 1 ; tuck loops: [50 on yarn C1.1]. 
tuck + b86 1 ; tuck loops: [51 on yarn C1.1]. 
tuck + f88 1 ; tuck loops: [52 on yarn C1.1]. 
tuck + b94 1 ; tuck loops: [53 on yarn C1.1]. 
tuck + f96 1 ; tuck loops: [54 on yarn C1.1]. 
tuck + b102 1 ; tuck loops: [55 on yarn C1.1]. 
tuck + f104 1 ; tuck loops: [56 on yarn C1.1]. 
tuck + b110 1 ; tuck loops: [57 on yarn C1.1]. 
tuck + f112 1 ; tuck loops: [58 on yarn C1.1]. 
tuck + b118 1 ; tuck loops: [59 on yarn C1.1]. 
;Resetting to sheet s1:g4 of 4
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b2 f2 ;
xfer b6 f6 ;
xfer b10 f10 ;
xfer b14 f14 ;
xfer b18 f18 ;
xfer b22 f22 ;
xfer b26 f26 ;
xfer b30 f30 ;
xfer b34 f34 ;
xfer b38 f38 ;
xfer b42 f42 ;
xfer b46 f46 ;
xfer b50 f50 ;
xfer b54 f54 ;
xfer b58 f58 ;
xfer b62 f62 ;
xfer b66 f66 ;
xfer b70 f70 ;
xfer b74 f74 ;
xfer b78 f78 ;
xfer b82 f82 ;
xfer b86 f86 ;
xfer b90 f90 ;
xfer b94 f94 ;
xfer b98 f98 ;
xfer b102 f102 ;
xfer b106 f106 ;
xfer b110 f110 ;
xfer b114 f114 ;
xfer b118 f118 ;
; Peel sheet 3 relative to 1
tuck - f117 1 ; tuck loops: [60 on yarn C1.1]. 
tuck - b115 1 ; tuck loops: [61 on yarn C1.1]. 
tuck - f109 1 ; tuck loops: [62 on yarn C1.1]. 
tuck - b107 1 ; tuck loops: [63 on yarn C1.1]. 
tuck - f101 1 ; tuck loops: [64 on yarn C1.1]. 
tuck - b99 1 ; tuck loops: [65 on yarn C1.1]. 
tuck - f93 1 ; tuck loops: [66 on yarn C1.1]. 
tuck - b91 1 ; tuck loops: [67 on yarn C1.1]. 
tuck - f85 1 ; tuck loops: [68 on yarn C1.1]. 
tuck - b83 1 ; tuck loops: [69 on yarn C1.1]. 
tuck - f77 1 ; tuck loops: [70 on yarn C1.1]. 
tuck - b75 1 ; tuck loops: [71 on yarn C1.1]. 
tuck - f69 1 ; tuck loops: [72 on yarn C1.1]. 
tuck - b67 1 ; tuck loops: [73 on yarn C1.1]. 
tuck - f61 1 ; tuck loops: [74 on yarn C1.1]. 
tuck - b59 1 ; tuck loops: [75 on yarn C1.1]. 
tuck - f53 1 ; tuck loops: [76 on yarn C1.1]. 
tuck - b51 1 ; tuck loops: [77 on yarn C1.1]. 
tuck - f45 1 ; tuck loops: [78 on yarn C1.1]. 
tuck - b43 1 ; tuck loops: [79 on yarn C1.1]. 
tuck - f37 1 ; tuck loops: [80 on yarn C1.1]. 
tuck - b35 1 ; tuck loops: [81 on yarn C1.1]. 
tuck - f29 1 ; tuck loops: [82 on yarn C1.1]. 
tuck - b27 1 ; tuck loops: [83 on yarn C1.1]. 
tuck - f21 1 ; tuck loops: [84 on yarn C1.1]. 
tuck - b19 1 ; tuck loops: [85 on yarn C1.1]. 
tuck - f13 1 ; tuck loops: [86 on yarn C1.1]. 
tuck - b11 1 ; tuck loops: [87 on yarn C1.1]. 
tuck - f5 1 ; tuck loops: [88 on yarn C1.1]. 
tuck - b3 1 ; tuck loops: [89 on yarn C1.1]. 
tuck + f1 1 ; tuck loops: [90 on yarn C1.1]. 
tuck + b7 1 ; tuck loops: [91 on yarn C1.1]. 
tuck + f9 1 ; tuck loops: [92 on yarn C1.1]. 
tuck + b15 1 ; tuck loops: [93 on yarn C1.1]. 
tuck + f17 1 ; tuck loops: [94 on yarn C1.1]. 
tuck + b23 1 ; tuck loops: [95 on yarn C1.1]. 
tuck + f25 1 ; tuck loops: [96 on yarn C1.1]. 
tuck + b31 1 ; tuck loops: [97 on yarn C1.1]. 
tuck + f33 1 ; tuck loops: [98 on yarn C1.1]. 
tuck + b39 1 ; tuck loops: [99 on yarn C1.1]. 
tuck + f41 1 ; tuck loops: [100 on yarn C1.1]. 
tuck + b47 1 ; tuck loops: [101 on yarn C1.1]. 
tuck + f49 1 ; tuck loops: [102 on yarn C1.1]. 
tuck + b55 1 ; tuck loops: [103 on yarn C1.1]. 
tuck + f57 1 ; tuck loops: [104 on yarn C1.1]. 
tuck + b63 1 ; tuck loops: [105 on yarn C1.1]. 
tuck + f65 1 ; tuck loops: [106 on yarn C1.1]. 
tuck + b71 1 ; tuck loops: [107 on yarn C1.1]. 
tuck + f73 1 ; tuck loops: [108 on yarn C1.1]. 
tuck + b79 1 ; tuck loops: [109 on yarn C1.1]. 
tuck + f81 1 ; tuck loops: [110 on yarn C1.1]. 
tuck + b87 1 ; tuck loops: [111 on yarn C1.1]. 
tuck + f89 1 ; tuck loops: [112 on yarn C1.1]. 
tuck + b95 1 ; tuck loops: [113 on yarn C1.1]. 
tuck + f97 1 ; tuck loops: [114 on yarn C1.1]. 
tuck + b103 1 ; tuck loops: [115 on yarn C1.1]. 
tuck + f105 1 ; tuck loops: [116 on yarn C1.1]. 
tuck + b111 1 ; tuck loops: [117 on yarn C1.1]. 
tuck + f113 1 ; tuck loops: [118 on yarn C1.1]. 
tuck + b119 1 ; tuck loops: [119 on yarn C1.1]. 
;KP Printout: 0: stripe 0: [f0, f4, f8, f12, f16, f20]
;Resetting to sheet s0:g4 of 4
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f5 b5 ;
xfer f9 b9 ;
xfer f13 b13 ;
xfer f17 b17 ;
xfer f21 b21 ;
xfer f25 b25 ;
xfer f29 b29 ;
xfer f33 b33 ;
xfer f37 b37 ;
xfer f41 b41 ;
xfer f45 b45 ;
xfer f49 b49 ;
xfer f53 b53 ;
xfer f57 b57 ;
xfer f61 b61 ;
xfer f65 b65 ;
xfer f69 b69 ;
xfer f73 b73 ;
xfer f77 b77 ;
xfer f81 b81 ;
xfer f85 b85 ;
xfer f89 b89 ;
xfer f93 b93 ;
xfer f97 b97 ;
xfer f101 b101 ;
xfer f105 b105 ;
xfer f109 b109 ;
xfer f113 b113 ;
xfer f117 b117 ;
; Peel sheet 2 relative to 0
; Peel sheet 3 relative to 0
xfer f2 b2 ;return loops {29 on yarn C1.1} on f2 to b2
xfer f6 b6 ;return loops {31 on yarn C1.1} on f6 to b6
xfer f10 b10 ;return loops {27 on yarn C1.1} on f10 to b10
xfer f14 b14 ;return loops {33 on yarn C1.1} on f14 to b14
xfer f18 b18 ;return loops {25 on yarn C1.1} on f18 to b18
xfer f22 b22 ;return loops {35 on yarn C1.1} on f22 to b22
xfer f26 b26 ;return loops {23 on yarn C1.1} on f26 to b26
xfer f30 b30 ;return loops {37 on yarn C1.1} on f30 to b30
xfer f34 b34 ;return loops {21 on yarn C1.1} on f34 to b34
xfer f38 b38 ;return loops {39 on yarn C1.1} on f38 to b38
xfer f42 b42 ;return loops {19 on yarn C1.1} on f42 to b42
xfer f46 b46 ;return loops {41 on yarn C1.1} on f46 to b46
xfer f50 b50 ;return loops {17 on yarn C1.1} on f50 to b50
xfer f54 b54 ;return loops {43 on yarn C1.1} on f54 to b54
xfer f58 b58 ;return loops {15 on yarn C1.1} on f58 to b58
xfer f62 b62 ;return loops {45 on yarn C1.1} on f62 to b62
xfer f66 b66 ;return loops {13 on yarn C1.1} on f66 to b66
xfer f70 b70 ;return loops {47 on yarn C1.1} on f70 to b70
xfer f74 b74 ;return loops {11 on yarn C1.1} on f74 to b74
xfer f78 b78 ;return loops {49 on yarn C1.1} on f78 to b78
xfer f82 b82 ;return loops {9 on yarn C1.1} on f82 to b82
xfer f86 b86 ;return loops {51 on yarn C1.1} on f86 to b86
xfer f90 b90 ;return loops {7 on yarn C1.1} on f90 to b90
xfer f94 b94 ;return loops {53 on yarn C1.1} on f94 to b94
xfer f98 b98 ;return loops {5 on yarn C1.1} on f98 to b98
xfer f102 b102 ;return loops {55 on yarn C1.1} on f102 to b102
xfer f106 b106 ;return loops {3 on yarn C1.1} on f106 to b106
xfer f110 b110 ;return loops {57 on yarn C1.1} on f110 to b110
xfer f114 b114 ;return loops {1 on yarn C1.1} on f114 to b114
xfer f118 b118 ;return loops {59 on yarn C1.1} on f118 to b118
knit - f116 1 ;knit loops: [120 on yarn C1.1]. 
knit - b114 1 ;knit loops: [121 on yarn C1.1]. 
knit - f112 1 ;knit loops: [122 on yarn C1.1]. 
knit - f108 1 ;knit loops: [123 on yarn C1.1]. 
knit - b106 1 ;knit loops: [124 on yarn C1.1]. 
knit - f104 1 ;knit loops: [125 on yarn C1.1]. 
knit - f100 1 ;knit loops: [126 on yarn C1.1]. 
knit - b98 1 ;knit loops: [127 on yarn C1.1]. 
knit - f96 1 ;knit loops: [128 on yarn C1.1]. 
knit - f92 1 ;knit loops: [129 on yarn C1.1]. 
knit - b90 1 ;knit loops: [130 on yarn C1.1]. 
knit - f88 1 ;knit loops: [131 on yarn C1.1]. 
knit - f84 1 ;knit loops: [132 on yarn C1.1]. 
knit - b82 1 ;knit loops: [133 on yarn C1.1]. 
knit - f80 1 ;knit loops: [134 on yarn C1.1]. 
knit - f76 1 ;knit loops: [135 on yarn C1.1]. 
knit - b74 1 ;knit loops: [136 on yarn C1.1]. 
knit - f72 1 ;knit loops: [137 on yarn C1.1]. 
knit - f68 1 ;knit loops: [138 on yarn C1.1]. 
knit - b66 1 ;knit loops: [139 on yarn C1.1]. 
knit - f64 1 ;knit loops: [140 on yarn C1.1]. 
knit - f60 1 ;knit loops: [141 on yarn C1.1]. 
knit - b58 1 ;knit loops: [142 on yarn C1.1]. 
knit - f56 1 ;knit loops: [143 on yarn C1.1]. 
knit - f52 1 ;knit loops: [144 on yarn C1.1]. 
knit - b50 1 ;knit loops: [145 on yarn C1.1]. 
knit - f48 1 ;knit loops: [146 on yarn C1.1]. 
knit - f44 1 ;knit loops: [147 on yarn C1.1]. 
knit - b42 1 ;knit loops: [148 on yarn C1.1]. 
knit - f40 1 ;knit loops: [149 on yarn C1.1]. 
knit - f36 1 ;knit loops: [150 on yarn C1.1]. 
knit - b34 1 ;knit loops: [151 on yarn C1.1]. 
knit - f32 1 ;knit loops: [152 on yarn C1.1]. 
knit - f28 1 ;knit loops: [153 on yarn C1.1]. 
knit - b26 1 ;knit loops: [154 on yarn C1.1]. 
knit - f24 1 ;knit loops: [155 on yarn C1.1]. 
knit - b18 1 ;knit loops: [156 on yarn C1.1]. 
knit - b10 1 ;knit loops: [157 on yarn C1.1]. 
knit - b2 1 ;knit loops: [158 on yarn C1.1]. 
inhook  2 ;Activating carrier  2
knit - b118 2 ;knit loops: [159 on yarn C2.2]. 
knit - b110 2 ;knit loops: [160 on yarn C2.2]. 
knit - b102 2 ;knit loops: [161 on yarn C2.2]. 
knit - b94 2 ;knit loops: [162 on yarn C2.2]. 
knit - b86 2 ;knit loops: [163 on yarn C2.2]. 
knit - b78 2 ;knit loops: [164 on yarn C2.2]. 
knit - b70 2 ;knit loops: [165 on yarn C2.2]. 
knit - b62 2 ;knit loops: [166 on yarn C2.2]. 
knit - b54 2 ;knit loops: [167 on yarn C2.2]. 
knit - b46 2 ;knit loops: [168 on yarn C2.2]. 
knit - b38 2 ;knit loops: [169 on yarn C2.2]. 
knit - b30 2 ;knit loops: [170 on yarn C2.2]. 
knit - b22 2 ;knit loops: [171 on yarn C2.2]. 
knit - f20 2 ;knit loops: [172 on yarn C2.2]. 
knit - f16 2 ;knit loops: [173 on yarn C2.2]. 
knit - b14 2 ;knit loops: [174 on yarn C2.2]. 
knit - f12 2 ;knit loops: [175 on yarn C2.2]. 
knit - f8 2 ;knit loops: [176 on yarn C2.2]. 
knit - b6 2 ;knit loops: [177 on yarn C2.2]. 
knit - f4 2 ;knit loops: [178 on yarn C2.2]. 
knit - f0 2 ;knit loops: [179 on yarn C2.2]. 
releasehook  2 ;
inhook  3 ;Activating carrier  3
knit - b114 3 ;knit loops: [180 on yarn C3.3]. 
knit - b106 3 ;knit loops: [181 on yarn C3.3]. 
knit - b98 3 ;knit loops: [182 on yarn C3.3]. 
knit - b90 3 ;knit loops: [183 on yarn C3.3]. 
knit - b82 3 ;knit loops: [184 on yarn C3.3]. 
knit - b74 3 ;knit loops: [185 on yarn C3.3]. 
knit - b66 3 ;knit loops: [186 on yarn C3.3]. 
knit - b58 3 ;knit loops: [187 on yarn C3.3]. 
knit - b50 3 ;knit loops: [188 on yarn C3.3]. 
knit - b42 3 ;knit loops: [189 on yarn C3.3]. 
knit - b34 3 ;knit loops: [190 on yarn C3.3]. 
knit - b26 3 ;knit loops: [191 on yarn C3.3]. 
knit - b18 3 ;knit loops: [192 on yarn C3.3]. 
knit - b10 3 ;knit loops: [193 on yarn C3.3]. 
knit - b2 3 ;knit loops: [194 on yarn C3.3]. 
releasehook  3 ;
;KP Printout: 0: stripe 1: [b3, b7, b11, b15, b19, b23]
;Resetting to sheet s3:g4 of 4
; Peel sheet 0 relative to 3
; Peel sheet 1 relative to 3
; Peel sheet 2 relative to 3
xfer b2 f2 ;
xfer b6 f6 ;
xfer b10 f10 ;
xfer b14 f14 ;
xfer b18 f18 ;
xfer b22 f22 ;
xfer b26 f26 ;
xfer b30 f30 ;
xfer b34 f34 ;
xfer b38 f38 ;
xfer b42 f42 ;
xfer b46 f46 ;
xfer b50 f50 ;
xfer b54 f54 ;
xfer b58 f58 ;
xfer b62 f62 ;
xfer b66 f66 ;
xfer b70 f70 ;
xfer b74 f74 ;
xfer b78 f78 ;
xfer b82 f82 ;
xfer b86 f86 ;
xfer b90 f90 ;
xfer b94 f94 ;
xfer b98 f98 ;
xfer b102 f102 ;
xfer b106 f106 ;
xfer b110 f110 ;
xfer b114 f114 ;
xfer b118 f118 ;
; Peel sheet 3 relative to 3
xfer b1 f1 ;Return loops {90 on yarn C1.1} on b1 to f1
xfer b5 f5 ;Return loops {88 on yarn C1.1} on b5 to f5
xfer b9 f9 ;Return loops {92 on yarn C1.1} on b9 to f9
xfer b13 f13 ;Return loops {86 on yarn C1.1} on b13 to f13
xfer b17 f17 ;Return loops {94 on yarn C1.1} on b17 to f17
xfer b21 f21 ;Return loops {84 on yarn C1.1} on b21 to f21
xfer b25 f25 ;Return loops {96 on yarn C1.1} on b25 to f25
xfer b29 f29 ;Return loops {82 on yarn C1.1} on b29 to f29
xfer b33 f33 ;Return loops {98 on yarn C1.1} on b33 to f33
xfer b37 f37 ;Return loops {80 on yarn C1.1} on b37 to f37
xfer b41 f41 ;Return loops {100 on yarn C1.1} on b41 to f41
xfer b45 f45 ;Return loops {78 on yarn C1.1} on b45 to f45
xfer b49 f49 ;Return loops {102 on yarn C1.1} on b49 to f49
xfer b53 f53 ;Return loops {76 on yarn C1.1} on b53 to f53
xfer b57 f57 ;Return loops {104 on yarn C1.1} on b57 to f57
xfer b61 f61 ;Return loops {74 on yarn C1.1} on b61 to f61
xfer b65 f65 ;Return loops {106 on yarn C1.1} on b65 to f65
xfer b69 f69 ;Return loops {72 on yarn C1.1} on b69 to f69
xfer b73 f73 ;Return loops {108 on yarn C1.1} on b73 to f73
xfer b77 f77 ;Return loops {70 on yarn C1.1} on b77 to f77
xfer b81 f81 ;Return loops {110 on yarn C1.1} on b81 to f81
xfer b85 f85 ;Return loops {68 on yarn C1.1} on b85 to f85
xfer b89 f89 ;Return loops {112 on yarn C1.1} on b89 to f89
xfer b93 f93 ;Return loops {66 on yarn C1.1} on b93 to f93
xfer b97 f97 ;Return loops {114 on yarn C1.1} on b97 to f97
xfer b101 f101 ;Return loops {64 on yarn C1.1} on b101 to f101
xfer b105 f105 ;Return loops {116 on yarn C1.1} on b105 to f105
xfer b109 f109 ;Return loops {62 on yarn C1.1} on b109 to f109
xfer b113 f113 ;Return loops {118 on yarn C1.1} on b113 to f113
xfer b117 f117 ;Return loops {60 on yarn C1.1} on b117 to f117
knit + f5 1 ;knit loops: [195 on yarn C1.1]. 
knit + f13 1 ;knit loops: [196 on yarn C1.1]. 
knit + f21 1 ;knit loops: [197 on yarn C1.1]. 
knit + b27 1 ;knit loops: [198 on yarn C1.1]. 
knit + f29 1 ;knit loops: [199 on yarn C1.1]. 
knit + b31 1 ;knit loops: [200 on yarn C1.1]. 
knit + b35 1 ;knit loops: [201 on yarn C1.1]. 
knit + f37 1 ;knit loops: [202 on yarn C1.1]. 
knit + b39 1 ;knit loops: [203 on yarn C1.1]. 
knit + b43 1 ;knit loops: [204 on yarn C1.1]. 
knit + f45 1 ;knit loops: [205 on yarn C1.1]. 
knit + b47 1 ;knit loops: [206 on yarn C1.1]. 
knit + b51 1 ;knit loops: [207 on yarn C1.1]. 
knit + f53 1 ;knit loops: [208 on yarn C1.1]. 
knit + b55 1 ;knit loops: [209 on yarn C1.1]. 
knit + b59 1 ;knit loops: [210 on yarn C1.1]. 
knit + f61 1 ;knit loops: [211 on yarn C1.1]. 
knit + b63 1 ;knit loops: [212 on yarn C1.1]. 
knit + b67 1 ;knit loops: [213 on yarn C1.1]. 
knit + f69 1 ;knit loops: [214 on yarn C1.1]. 
knit + b71 1 ;knit loops: [215 on yarn C1.1]. 
knit + b75 1 ;knit loops: [216 on yarn C1.1]. 
knit + f77 1 ;knit loops: [217 on yarn C1.1]. 
knit + b79 1 ;knit loops: [218 on yarn C1.1]. 
knit + b83 1 ;knit loops: [219 on yarn C1.1]. 
knit + f85 1 ;knit loops: [220 on yarn C1.1]. 
knit + b87 1 ;knit loops: [221 on yarn C1.1]. 
knit + b91 1 ;knit loops: [222 on yarn C1.1]. 
knit + f93 1 ;knit loops: [223 on yarn C1.1]. 
knit + b95 1 ;knit loops: [224 on yarn C1.1]. 
knit + b99 1 ;knit loops: [225 on yarn C1.1]. 
knit + f101 1 ;knit loops: [226 on yarn C1.1]. 
knit + b103 1 ;knit loops: [227 on yarn C1.1]. 
knit + b107 1 ;knit loops: [228 on yarn C1.1]. 
knit + f109 1 ;knit loops: [229 on yarn C1.1]. 
knit + b111 1 ;knit loops: [230 on yarn C1.1]. 
knit + b115 1 ;knit loops: [231 on yarn C1.1]. 
knit + f117 1 ;knit loops: [232 on yarn C1.1]. 
knit + b119 1 ;knit loops: [233 on yarn C1.1]. 
knit + f1 2 ;knit loops: [234 on yarn C2.2]. 
knit + f9 2 ;knit loops: [235 on yarn C2.2]. 
knit + f17 2 ;knit loops: [236 on yarn C2.2]. 
knit + f25 2 ;knit loops: [237 on yarn C2.2]. 
knit + f33 2 ;knit loops: [238 on yarn C2.2]. 
knit + f41 2 ;knit loops: [239 on yarn C2.2]. 
knit + f49 2 ;knit loops: [240 on yarn C2.2]. 
knit + f57 2 ;knit loops: [241 on yarn C2.2]. 
knit + f65 2 ;knit loops: [242 on yarn C2.2]. 
knit + f73 2 ;knit loops: [243 on yarn C2.2]. 
knit + f81 2 ;knit loops: [244 on yarn C2.2]. 
knit + f89 2 ;knit loops: [245 on yarn C2.2]. 
knit + f97 2 ;knit loops: [246 on yarn C2.2]. 
knit + f105 2 ;knit loops: [247 on yarn C2.2]. 
knit + f113 2 ;knit loops: [248 on yarn C2.2]. 
knit + b3 3 ;knit loops: [249 on yarn C3.3]. 
knit + f5 3 ;knit loops: [250 on yarn C3.3]. 
knit + b7 3 ;knit loops: [251 on yarn C3.3]. 
knit + b11 3 ;knit loops: [252 on yarn C3.3]. 
knit + f13 3 ;knit loops: [253 on yarn C3.3]. 
knit + b15 3 ;knit loops: [254 on yarn C3.3]. 
knit + b19 3 ;knit loops: [255 on yarn C3.3]. 
knit + f21 3 ;knit loops: [256 on yarn C3.3]. 
knit + b23 3 ;knit loops: [257 on yarn C3.3]. 
knit + f29 3 ;knit loops: [258 on yarn C3.3]. 
knit + f37 3 ;knit loops: [259 on yarn C3.3]. 
knit + f45 3 ;knit loops: [260 on yarn C3.3]. 
knit + f53 3 ;knit loops: [261 on yarn C3.3]. 
knit + f61 3 ;knit loops: [262 on yarn C3.3]. 
knit + f69 3 ;knit loops: [263 on yarn C3.3]. 
knit + f77 3 ;knit loops: [264 on yarn C3.3]. 
knit + f85 3 ;knit loops: [265 on yarn C3.3]. 
knit + f93 3 ;knit loops: [266 on yarn C3.3]. 
knit + f101 3 ;knit loops: [267 on yarn C3.3]. 
knit + f109 3 ;knit loops: [268 on yarn C3.3]. 
knit + f117 3 ;knit loops: [269 on yarn C3.3]. 
;KP Printout: 1: stripe 0: [f4, f8, f12, f16, f20, f24]
;Resetting to sheet s0:g4 of 4
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f5 b5 ;
xfer f9 b9 ;
xfer f13 b13 ;
xfer f17 b17 ;
xfer f21 b21 ;
xfer f25 b25 ;
xfer f29 b29 ;
xfer f33 b33 ;
xfer f37 b37 ;
xfer f41 b41 ;
xfer f45 b45 ;
xfer f49 b49 ;
xfer f53 b53 ;
xfer f57 b57 ;
xfer f61 b61 ;
xfer f65 b65 ;
xfer f69 b69 ;
xfer f73 b73 ;
xfer f77 b77 ;
xfer f81 b81 ;
xfer f85 b85 ;
xfer f89 b89 ;
xfer f93 b93 ;
xfer f97 b97 ;
xfer f101 b101 ;
xfer f105 b105 ;
xfer f109 b109 ;
xfer f113 b113 ;
xfer f117 b117 ;
; Peel sheet 2 relative to 0
; Peel sheet 3 relative to 0
xfer f2 b2 ;return loops {194 on yarn C3.3} on f2 to b2
xfer f6 b6 ;return loops {177 on yarn C2.2} on f6 to b6
xfer f10 b10 ;return loops {193 on yarn C3.3} on f10 to b10
xfer f14 b14 ;return loops {174 on yarn C2.2} on f14 to b14
xfer f18 b18 ;return loops {192 on yarn C3.3} on f18 to b18
xfer f22 b22 ;return loops {171 on yarn C2.2} on f22 to b22
xfer f26 b26 ;return loops {191 on yarn C3.3} on f26 to b26
xfer f30 b30 ;return loops {170 on yarn C2.2} on f30 to b30
xfer f34 b34 ;return loops {190 on yarn C3.3} on f34 to b34
xfer f38 b38 ;return loops {169 on yarn C2.2} on f38 to b38
xfer f42 b42 ;return loops {189 on yarn C3.3} on f42 to b42
xfer f46 b46 ;return loops {168 on yarn C2.2} on f46 to b46
xfer f50 b50 ;return loops {188 on yarn C3.3} on f50 to b50
xfer f54 b54 ;return loops {167 on yarn C2.2} on f54 to b54
xfer f58 b58 ;return loops {187 on yarn C3.3} on f58 to b58
xfer f62 b62 ;return loops {166 on yarn C2.2} on f62 to b62
xfer f66 b66 ;return loops {186 on yarn C3.3} on f66 to b66
xfer f70 b70 ;return loops {165 on yarn C2.2} on f70 to b70
xfer f74 b74 ;return loops {185 on yarn C3.3} on f74 to b74
xfer f78 b78 ;return loops {164 on yarn C2.2} on f78 to b78
xfer f82 b82 ;return loops {184 on yarn C3.3} on f82 to b82
xfer f86 b86 ;return loops {163 on yarn C2.2} on f86 to b86
xfer f90 b90 ;return loops {183 on yarn C3.3} on f90 to b90
xfer f94 b94 ;return loops {162 on yarn C2.2} on f94 to b94
xfer f98 b98 ;return loops {182 on yarn C3.3} on f98 to b98
xfer f102 b102 ;return loops {161 on yarn C2.2} on f102 to b102
xfer f106 b106 ;return loops {181 on yarn C3.3} on f106 to b106
xfer f110 b110 ;return loops {160 on yarn C2.2} on f110 to b110
xfer f114 b114 ;return loops {180 on yarn C3.3} on f114 to b114
xfer f118 b118 ;return loops {159 on yarn C2.2} on f118 to b118
knit - b118 1 ;knit loops: [270 on yarn C1.1]. 
knit - f116 1 ;knit loops: [271 on yarn C1.1]. 
knit - f112 1 ;knit loops: [272 on yarn C1.1]. 
knit - b110 1 ;knit loops: [273 on yarn C1.1]. 
knit - f108 1 ;knit loops: [274 on yarn C1.1]. 
knit - f104 1 ;knit loops: [275 on yarn C1.1]. 
knit - b102 1 ;knit loops: [276 on yarn C1.1]. 
knit - f100 1 ;knit loops: [277 on yarn C1.1]. 
knit - f96 1 ;knit loops: [278 on yarn C1.1]. 
knit - b94 1 ;knit loops: [279 on yarn C1.1]. 
knit - f92 1 ;knit loops: [280 on yarn C1.1]. 
knit - f88 1 ;knit loops: [281 on yarn C1.1]. 
knit - b86 1 ;knit loops: [282 on yarn C1.1]. 
knit - f84 1 ;knit loops: [283 on yarn C1.1]. 
knit - f80 1 ;knit loops: [284 on yarn C1.1]. 
knit - b78 1 ;knit loops: [285 on yarn C1.1]. 
knit - f76 1 ;knit loops: [286 on yarn C1.1]. 
knit - f72 1 ;knit loops: [287 on yarn C1.1]. 
knit - b70 1 ;knit loops: [288 on yarn C1.1]. 
knit - f68 1 ;knit loops: [289 on yarn C1.1]. 
knit - f64 1 ;knit loops: [290 on yarn C1.1]. 
knit - b62 1 ;knit loops: [291 on yarn C1.1]. 
knit - f60 1 ;knit loops: [292 on yarn C1.1]. 
knit - f56 1 ;knit loops: [293 on yarn C1.1]. 
knit - b54 1 ;knit loops: [294 on yarn C1.1]. 
knit - f52 1 ;knit loops: [295 on yarn C1.1]. 
knit - f48 1 ;knit loops: [296 on yarn C1.1]. 
knit - b46 1 ;knit loops: [297 on yarn C1.1]. 
knit - f44 1 ;knit loops: [298 on yarn C1.1]. 
knit - f40 1 ;knit loops: [299 on yarn C1.1]. 
knit - b38 1 ;knit loops: [300 on yarn C1.1]. 
knit - f36 1 ;knit loops: [301 on yarn C1.1]. 
knit - f32 1 ;knit loops: [302 on yarn C1.1]. 
knit - b30 1 ;knit loops: [303 on yarn C1.1]. 
knit - f28 1 ;knit loops: [304 on yarn C1.1]. 
knit - b22 1 ;knit loops: [305 on yarn C1.1]. 
knit - b14 1 ;knit loops: [306 on yarn C1.1]. 
knit - b6 1 ;knit loops: [307 on yarn C1.1]. 
knit - f0 1 ;knit loops: [308 on yarn C1.1]. 
knit - b114 2 ;knit loops: [309 on yarn C2.2]. 
knit - b106 2 ;knit loops: [310 on yarn C2.2]. 
knit - b98 2 ;knit loops: [311 on yarn C2.2]. 
knit - b90 2 ;knit loops: [312 on yarn C2.2]. 
knit - b82 2 ;knit loops: [313 on yarn C2.2]. 
knit - b74 2 ;knit loops: [314 on yarn C2.2]. 
knit - b66 2 ;knit loops: [315 on yarn C2.2]. 
knit - b58 2 ;knit loops: [316 on yarn C2.2]. 
knit - b50 2 ;knit loops: [317 on yarn C2.2]. 
knit - b42 2 ;knit loops: [318 on yarn C2.2]. 
knit - b34 2 ;knit loops: [319 on yarn C2.2]. 
knit - b26 2 ;knit loops: [320 on yarn C2.2]. 
knit - f24 2 ;knit loops: [321 on yarn C2.2]. 
knit - f20 2 ;knit loops: [322 on yarn C2.2]. 
knit - b18 2 ;knit loops: [323 on yarn C2.2]. 
knit - f16 2 ;knit loops: [324 on yarn C2.2]. 
knit - f12 2 ;knit loops: [325 on yarn C2.2]. 
knit - b10 2 ;knit loops: [326 on yarn C2.2]. 
knit - f8 2 ;knit loops: [327 on yarn C2.2]. 
knit - f4 2 ;knit loops: [328 on yarn C2.2]. 
knit - b2 2 ;knit loops: [329 on yarn C2.2]. 
knit - b118 3 ;knit loops: [330 on yarn C3.3]. 
knit - b110 3 ;knit loops: [331 on yarn C3.3]. 
knit - b102 3 ;knit loops: [332 on yarn C3.3]. 
knit - b94 3 ;knit loops: [333 on yarn C3.3]. 
knit - b86 3 ;knit loops: [334 on yarn C3.3]. 
knit - b78 3 ;knit loops: [335 on yarn C3.3]. 
knit - b70 3 ;knit loops: [336 on yarn C3.3]. 
knit - b62 3 ;knit loops: [337 on yarn C3.3]. 
knit - b54 3 ;knit loops: [338 on yarn C3.3]. 
knit - b46 3 ;knit loops: [339 on yarn C3.3]. 
knit - b38 3 ;knit loops: [340 on yarn C3.3]. 
knit - b30 3 ;knit loops: [341 on yarn C3.3]. 
knit - b22 3 ;knit loops: [342 on yarn C3.3]. 
knit - b14 3 ;knit loops: [343 on yarn C3.3]. 
knit - b6 3 ;knit loops: [344 on yarn C3.3]. 
;KP Printout: 1: stripe 1: [b7, b11, b15, b19, b23, b27]
;Resetting to sheet s3:g4 of 4
; Peel sheet 0 relative to 3
; Peel sheet 1 relative to 3
; Peel sheet 2 relative to 3
xfer b2 f2 ;
xfer b6 f6 ;
xfer b10 f10 ;
xfer b14 f14 ;
xfer b18 f18 ;
xfer b22 f22 ;
xfer b26 f26 ;
xfer b30 f30 ;
xfer b34 f34 ;
xfer b38 f38 ;
xfer b42 f42 ;
xfer b46 f46 ;
xfer b50 f50 ;
xfer b54 f54 ;
xfer b58 f58 ;
xfer b62 f62 ;
xfer b66 f66 ;
xfer b70 f70 ;
xfer b74 f74 ;
xfer b78 f78 ;
xfer b82 f82 ;
xfer b86 f86 ;
xfer b90 f90 ;
xfer b94 f94 ;
xfer b98 f98 ;
xfer b102 f102 ;
xfer b106 f106 ;
xfer b110 f110 ;
xfer b114 f114 ;
xfer b118 f118 ;
; Peel sheet 3 relative to 3
xfer b1 f1 ;Return loops {234 on yarn C2.2} on b1 to f1
xfer b5 f5 ;Return loops {250 on yarn C3.3} on b5 to f5
xfer b9 f9 ;Return loops {235 on yarn C2.2} on b9 to f9
xfer b13 f13 ;Return loops {253 on yarn C3.3} on b13 to f13
xfer b17 f17 ;Return loops {236 on yarn C2.2} on b17 to f17
xfer b21 f21 ;Return loops {256 on yarn C3.3} on b21 to f21
xfer b25 f25 ;Return loops {237 on yarn C2.2} on b25 to f25
xfer b29 f29 ;Return loops {258 on yarn C3.3} on b29 to f29
xfer b33 f33 ;Return loops {238 on yarn C2.2} on b33 to f33
xfer b37 f37 ;Return loops {259 on yarn C3.3} on b37 to f37
xfer b41 f41 ;Return loops {239 on yarn C2.2} on b41 to f41
xfer b45 f45 ;Return loops {260 on yarn C3.3} on b45 to f45
xfer b49 f49 ;Return loops {240 on yarn C2.2} on b49 to f49
xfer b53 f53 ;Return loops {261 on yarn C3.3} on b53 to f53
xfer b57 f57 ;Return loops {241 on yarn C2.2} on b57 to f57
xfer b61 f61 ;Return loops {262 on yarn C3.3} on b61 to f61
xfer b65 f65 ;Return loops {242 on yarn C2.2} on b65 to f65
xfer b69 f69 ;Return loops {263 on yarn C3.3} on b69 to f69
xfer b73 f73 ;Return loops {243 on yarn C2.2} on b73 to f73
xfer b77 f77 ;Return loops {264 on yarn C3.3} on b77 to f77
xfer b81 f81 ;Return loops {244 on yarn C2.2} on b81 to f81
xfer b85 f85 ;Return loops {265 on yarn C3.3} on b85 to f85
xfer b89 f89 ;Return loops {245 on yarn C2.2} on b89 to f89
xfer b93 f93 ;Return loops {266 on yarn C3.3} on b93 to f93
xfer b97 f97 ;Return loops {246 on yarn C2.2} on b97 to f97
xfer b101 f101 ;Return loops {267 on yarn C3.3} on b101 to f101
xfer b105 f105 ;Return loops {247 on yarn C2.2} on b105 to f105
xfer b109 f109 ;Return loops {268 on yarn C3.3} on b109 to f109
xfer b113 f113 ;Return loops {248 on yarn C2.2} on b113 to f113
xfer b117 f117 ;Return loops {269 on yarn C3.3} on b117 to f117
knit + f1 1 ;knit loops: [345 on yarn C1.1]. 
knit + b3 1 ;knit loops: [346 on yarn C1.1]. 
knit + f9 1 ;knit loops: [347 on yarn C1.1]. 
knit + f17 1 ;knit loops: [348 on yarn C1.1]. 
knit + f25 1 ;knit loops: [349 on yarn C1.1]. 
knit + b31 1 ;knit loops: [350 on yarn C1.1]. 
knit + f33 1 ;knit loops: [351 on yarn C1.1]. 
knit + b35 1 ;knit loops: [352 on yarn C1.1]. 
knit + b39 1 ;knit loops: [353 on yarn C1.1]. 
knit + f41 1 ;knit loops: [354 on yarn C1.1]. 
knit + b43 1 ;knit loops: [355 on yarn C1.1]. 
knit + b47 1 ;knit loops: [356 on yarn C1.1]. 
knit + f49 1 ;knit loops: [357 on yarn C1.1]. 
knit + b51 1 ;knit loops: [358 on yarn C1.1]. 
knit + b55 1 ;knit loops: [359 on yarn C1.1]. 
knit + f57 1 ;knit loops: [360 on yarn C1.1]. 
knit + b59 1 ;knit loops: [361 on yarn C1.1]. 
knit + b63 1 ;knit loops: [362 on yarn C1.1]. 
knit + f65 1 ;knit loops: [363 on yarn C1.1]. 
knit + b67 1 ;knit loops: [364 on yarn C1.1]. 
knit + b71 1 ;knit loops: [365 on yarn C1.1]. 
knit + f73 1 ;knit loops: [366 on yarn C1.1]. 
knit + b75 1 ;knit loops: [367 on yarn C1.1]. 
knit + b79 1 ;knit loops: [368 on yarn C1.1]. 
knit + f81 1 ;knit loops: [369 on yarn C1.1]. 
knit + b83 1 ;knit loops: [370 on yarn C1.1]. 
knit + b87 1 ;knit loops: [371 on yarn C1.1]. 
knit + f89 1 ;knit loops: [372 on yarn C1.1]. 
knit + b91 1 ;knit loops: [373 on yarn C1.1]. 
knit + b95 1 ;knit loops: [374 on yarn C1.1]. 
knit + f97 1 ;knit loops: [375 on yarn C1.1]. 
knit + b99 1 ;knit loops: [376 on yarn C1.1]. 
knit + b103 1 ;knit loops: [377 on yarn C1.1]. 
knit + f105 1 ;knit loops: [378 on yarn C1.1]. 
knit + b107 1 ;knit loops: [379 on yarn C1.1]. 
knit + b111 1 ;knit loops: [380 on yarn C1.1]. 
knit + f113 1 ;knit loops: [381 on yarn C1.1]. 
knit + b115 1 ;knit loops: [382 on yarn C1.1]. 
knit + b119 1 ;knit loops: [383 on yarn C1.1]. 
knit + f5 2 ;knit loops: [384 on yarn C2.2]. 
knit + f13 2 ;knit loops: [385 on yarn C2.2]. 
knit + f21 2 ;knit loops: [386 on yarn C2.2]. 
knit + f29 2 ;knit loops: [387 on yarn C2.2]. 
knit + f37 2 ;knit loops: [388 on yarn C2.2]. 
knit + f45 2 ;knit loops: [389 on yarn C2.2]. 
knit + f53 2 ;knit loops: [390 on yarn C2.2]. 
knit + f61 2 ;knit loops: [391 on yarn C2.2]. 
knit + f69 2 ;knit loops: [392 on yarn C2.2]. 
knit + f77 2 ;knit loops: [393 on yarn C2.2]. 
knit + f85 2 ;knit loops: [394 on yarn C2.2]. 
knit + f93 2 ;knit loops: [395 on yarn C2.2]. 
knit + f101 2 ;knit loops: [396 on yarn C2.2]. 
knit + f109 2 ;knit loops: [397 on yarn C2.2]. 
knit + f117 2 ;knit loops: [398 on yarn C2.2]. 
knit + f1 3 ;knit loops: [399 on yarn C3.3]. 
knit + b7 3 ;knit loops: [400 on yarn C3.3]. 
knit + f9 3 ;knit loops: [401 on yarn C3.3]. 
knit + b11 3 ;knit loops: [402 on yarn C3.3]. 
knit + b15 3 ;knit loops: [403 on yarn C3.3]. 
knit + f17 3 ;knit loops: [404 on yarn C3.3]. 
knit + b19 3 ;knit loops: [405 on yarn C3.3]. 
knit + b23 3 ;knit loops: [406 on yarn C3.3]. 
knit + f25 3 ;knit loops: [407 on yarn C3.3]. 
knit + b27 3 ;knit loops: [408 on yarn C3.3]. 
knit + f33 3 ;knit loops: [409 on yarn C3.3]. 
knit + f41 3 ;knit loops: [410 on yarn C3.3]. 
knit + f49 3 ;knit loops: [411 on yarn C3.3]. 
knit + f57 3 ;knit loops: [412 on yarn C3.3]. 
knit + f65 3 ;knit loops: [413 on yarn C3.3]. 
knit + f73 3 ;knit loops: [414 on yarn C3.3]. 
knit + f81 3 ;knit loops: [415 on yarn C3.3]. 
knit + f89 3 ;knit loops: [416 on yarn C3.3]. 
knit + f97 3 ;knit loops: [417 on yarn C3.3]. 
knit + f105 3 ;knit loops: [418 on yarn C3.3]. 
knit + f113 3 ;knit loops: [419 on yarn C3.3]. 
;KP Printout: 2: stripe 0: [f8, f12, f16, f20, f24, f28]
;Resetting to sheet s0:g4 of 4
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f5 b5 ;
xfer f9 b9 ;
xfer f13 b13 ;
xfer f17 b17 ;
xfer f21 b21 ;
xfer f25 b25 ;
xfer f29 b29 ;
xfer f33 b33 ;
xfer f37 b37 ;
xfer f41 b41 ;
xfer f45 b45 ;
xfer f49 b49 ;
xfer f53 b53 ;
xfer f57 b57 ;
xfer f61 b61 ;
xfer f65 b65 ;
xfer f69 b69 ;
xfer f73 b73 ;
xfer f77 b77 ;
xfer f81 b81 ;
xfer f85 b85 ;
xfer f89 b89 ;
xfer f93 b93 ;
xfer f97 b97 ;
xfer f101 b101 ;
xfer f105 b105 ;
xfer f109 b109 ;
xfer f113 b113 ;
xfer f117 b117 ;
; Peel sheet 2 relative to 0
; Peel sheet 3 relative to 0
xfer f2 b2 ;return loops {329 on yarn C2.2} on f2 to b2
xfer f6 b6 ;return loops {344 on yarn C3.3} on f6 to b6
xfer f10 b10 ;return loops {326 on yarn C2.2} on f10 to b10
xfer f14 b14 ;return loops {343 on yarn C3.3} on f14 to b14
xfer f18 b18 ;return loops {323 on yarn C2.2} on f18 to b18
xfer f22 b22 ;return loops {342 on yarn C3.3} on f22 to b22
xfer f26 b26 ;return loops {320 on yarn C2.2} on f26 to b26
xfer f30 b30 ;return loops {341 on yarn C3.3} on f30 to b30
xfer f34 b34 ;return loops {319 on yarn C2.2} on f34 to b34
xfer f38 b38 ;return loops {340 on yarn C3.3} on f38 to b38
xfer f42 b42 ;return loops {318 on yarn C2.2} on f42 to b42
xfer f46 b46 ;return loops {339 on yarn C3.3} on f46 to b46
xfer f50 b50 ;return loops {317 on yarn C2.2} on f50 to b50
xfer f54 b54 ;return loops {338 on yarn C3.3} on f54 to b54
xfer f58 b58 ;return loops {316 on yarn C2.2} on f58 to b58
xfer f62 b62 ;return loops {337 on yarn C3.3} on f62 to b62
xfer f66 b66 ;return loops {315 on yarn C2.2} on f66 to b66
xfer f70 b70 ;return loops {336 on yarn C3.3} on f70 to b70
xfer f74 b74 ;return loops {314 on yarn C2.2} on f74 to b74
xfer f78 b78 ;return loops {335 on yarn C3.3} on f78 to b78
xfer f82 b82 ;return loops {313 on yarn C2.2} on f82 to b82
xfer f86 b86 ;return loops {334 on yarn C3.3} on f86 to b86
xfer f90 b90 ;return loops {312 on yarn C2.2} on f90 to b90
xfer f94 b94 ;return loops {333 on yarn C3.3} on f94 to b94
xfer f98 b98 ;return loops {311 on yarn C2.2} on f98 to b98
xfer f102 b102 ;return loops {332 on yarn C3.3} on f102 to b102
xfer f106 b106 ;return loops {310 on yarn C2.2} on f106 to b106
xfer f110 b110 ;return loops {331 on yarn C3.3} on f110 to b110
xfer f114 b114 ;return loops {309 on yarn C2.2} on f114 to b114
xfer f118 b118 ;return loops {330 on yarn C3.3} on f118 to b118
knit - f116 1 ;knit loops: [420 on yarn C1.1]. 
knit - b114 1 ;knit loops: [421 on yarn C1.1]. 
knit - f112 1 ;knit loops: [422 on yarn C1.1]. 
knit - f108 1 ;knit loops: [423 on yarn C1.1]. 
knit - b106 1 ;knit loops: [424 on yarn C1.1]. 
knit - f104 1 ;knit loops: [425 on yarn C1.1]. 
knit - f100 1 ;knit loops: [426 on yarn C1.1]. 
knit - b98 1 ;knit loops: [427 on yarn C1.1]. 
knit - f96 1 ;knit loops: [428 on yarn C1.1]. 
knit - f92 1 ;knit loops: [429 on yarn C1.1]. 
knit - b90 1 ;knit loops: [430 on yarn C1.1]. 
knit - f88 1 ;knit loops: [431 on yarn C1.1]. 
knit - f84 1 ;knit loops: [432 on yarn C1.1]. 
knit - b82 1 ;knit loops: [433 on yarn C1.1]. 
knit - f80 1 ;knit loops: [434 on yarn C1.1]. 
knit - f76 1 ;knit loops: [435 on yarn C1.1]. 
knit - b74 1 ;knit loops: [436 on yarn C1.1]. 
knit - f72 1 ;knit loops: [437 on yarn C1.1]. 
knit - f68 1 ;knit loops: [438 on yarn C1.1]. 
knit - b66 1 ;knit loops: [439 on yarn C1.1]. 
knit - f64 1 ;knit loops: [440 on yarn C1.1]. 
knit - f60 1 ;knit loops: [441 on yarn C1.1]. 
knit - b58 1 ;knit loops: [442 on yarn C1.1]. 
knit - f56 1 ;knit loops: [443 on yarn C1.1]. 
knit - f52 1 ;knit loops: [444 on yarn C1.1]. 
knit - b50 1 ;knit loops: [445 on yarn C1.1]. 
knit - f48 1 ;knit loops: [446 on yarn C1.1]. 
knit - f44 1 ;knit loops: [447 on yarn C1.1]. 
knit - b42 1 ;knit loops: [448 on yarn C1.1]. 
knit - f40 1 ;knit loops: [449 on yarn C1.1]. 
knit - f36 1 ;knit loops: [450 on yarn C1.1]. 
knit - b34 1 ;knit loops: [451 on yarn C1.1]. 
knit - f32 1 ;knit loops: [452 on yarn C1.1]. 
knit - b26 1 ;knit loops: [453 on yarn C1.1]. 
knit - b18 1 ;knit loops: [454 on yarn C1.1]. 
knit - b10 1 ;knit loops: [455 on yarn C1.1]. 
knit - f4 1 ;knit loops: [456 on yarn C1.1]. 
knit - b2 1 ;knit loops: [457 on yarn C1.1]. 
knit - f0 1 ;knit loops: [458 on yarn C1.1]. 
knit - b118 2 ;knit loops: [459 on yarn C2.2]. 
knit - b110 2 ;knit loops: [460 on yarn C2.2]. 
knit - b102 2 ;knit loops: [461 on yarn C2.2]. 
knit - b94 2 ;knit loops: [462 on yarn C2.2]. 
knit - b86 2 ;knit loops: [463 on yarn C2.2]. 
knit - b78 2 ;knit loops: [464 on yarn C2.2]. 
knit - b70 2 ;knit loops: [465 on yarn C2.2]. 
knit - b62 2 ;knit loops: [466 on yarn C2.2]. 
knit - b54 2 ;knit loops: [467 on yarn C2.2]. 
knit - b46 2 ;knit loops: [468 on yarn C2.2]. 
knit - b38 2 ;knit loops: [469 on yarn C2.2]. 
knit - b30 2 ;knit loops: [470 on yarn C2.2]. 
knit - f28 2 ;knit loops: [471 on yarn C2.2]. 
knit - f24 2 ;knit loops: [472 on yarn C2.2]. 
knit - b22 2 ;knit loops: [473 on yarn C2.2]. 
knit - f20 2 ;knit loops: [474 on yarn C2.2]. 
knit - f16 2 ;knit loops: [475 on yarn C2.2]. 
knit - b14 2 ;knit loops: [476 on yarn C2.2]. 
knit - f12 2 ;knit loops: [477 on yarn C2.2]. 
knit - f8 2 ;knit loops: [478 on yarn C2.2]. 
knit - b6 2 ;knit loops: [479 on yarn C2.2]. 
knit - b114 3 ;knit loops: [480 on yarn C3.3]. 
knit - b106 3 ;knit loops: [481 on yarn C3.3]. 
knit - b98 3 ;knit loops: [482 on yarn C3.3]. 
knit - b90 3 ;knit loops: [483 on yarn C3.3]. 
knit - b82 3 ;knit loops: [484 on yarn C3.3]. 
knit - b74 3 ;knit loops: [485 on yarn C3.3]. 
knit - b66 3 ;knit loops: [486 on yarn C3.3]. 
knit - b58 3 ;knit loops: [487 on yarn C3.3]. 
knit - b50 3 ;knit loops: [488 on yarn C3.3]. 
knit - b42 3 ;knit loops: [489 on yarn C3.3]. 
knit - b34 3 ;knit loops: [490 on yarn C3.3]. 
knit - b26 3 ;knit loops: [491 on yarn C3.3]. 
knit - b18 3 ;knit loops: [492 on yarn C3.3]. 
knit - b10 3 ;knit loops: [493 on yarn C3.3]. 
knit - b2 3 ;knit loops: [494 on yarn C3.3]. 
;KP Printout: 2: stripe 1: [b11, b15, b19, b23, b27, b31]
;Resetting to sheet s3:g4 of 4
; Peel sheet 0 relative to 3
; Peel sheet 1 relative to 3
; Peel sheet 2 relative to 3
xfer b2 f2 ;
xfer b6 f6 ;
xfer b10 f10 ;
xfer b14 f14 ;
xfer b18 f18 ;
xfer b22 f22 ;
xfer b26 f26 ;
xfer b30 f30 ;
xfer b34 f34 ;
xfer b38 f38 ;
xfer b42 f42 ;
xfer b46 f46 ;
xfer b50 f50 ;
xfer b54 f54 ;
xfer b58 f58 ;
xfer b62 f62 ;
xfer b66 f66 ;
xfer b70 f70 ;
xfer b74 f74 ;
xfer b78 f78 ;
xfer b82 f82 ;
xfer b86 f86 ;
xfer b90 f90 ;
xfer b94 f94 ;
xfer b98 f98 ;
xfer b102 f102 ;
xfer b106 f106 ;
xfer b110 f110 ;
xfer b114 f114 ;
xfer b118 f118 ;
; Peel sheet 3 relative to 3
xfer b1 f1 ;Return loops {399 on yarn C3.3} on b1 to f1
xfer b5 f5 ;Return loops {384 on yarn C2.2} on b5 to f5
xfer b9 f9 ;Return loops {401 on yarn C3.3} on b9 to f9
xfer b13 f13 ;Return loops {385 on yarn C2.2} on b13 to f13
xfer b17 f17 ;Return loops {404 on yarn C3.3} on b17 to f17
xfer b21 f21 ;Return loops {386 on yarn C2.2} on b21 to f21
xfer b25 f25 ;Return loops {407 on yarn C3.3} on b25 to f25
xfer b29 f29 ;Return loops {387 on yarn C2.2} on b29 to f29
xfer b33 f33 ;Return loops {409 on yarn C3.3} on b33 to f33
xfer b37 f37 ;Return loops {388 on yarn C2.2} on b37 to f37
xfer b41 f41 ;Return loops {410 on yarn C3.3} on b41 to f41
xfer b45 f45 ;Return loops {389 on yarn C2.2} on b45 to f45
xfer b49 f49 ;Return loops {411 on yarn C3.3} on b49 to f49
xfer b53 f53 ;Return loops {390 on yarn C2.2} on b53 to f53
xfer b57 f57 ;Return loops {412 on yarn C3.3} on b57 to f57
xfer b61 f61 ;Return loops {391 on yarn C2.2} on b61 to f61
xfer b65 f65 ;Return loops {413 on yarn C3.3} on b65 to f65
xfer b69 f69 ;Return loops {392 on yarn C2.2} on b69 to f69
xfer b73 f73 ;Return loops {414 on yarn C3.3} on b73 to f73
xfer b77 f77 ;Return loops {393 on yarn C2.2} on b77 to f77
xfer b81 f81 ;Return loops {415 on yarn C3.3} on b81 to f81
xfer b85 f85 ;Return loops {394 on yarn C2.2} on b85 to f85
xfer b89 f89 ;Return loops {416 on yarn C3.3} on b89 to f89
xfer b93 f93 ;Return loops {395 on yarn C2.2} on b93 to f93
xfer b97 f97 ;Return loops {417 on yarn C3.3} on b97 to f97
xfer b101 f101 ;Return loops {396 on yarn C2.2} on b101 to f101
xfer b105 f105 ;Return loops {418 on yarn C3.3} on b105 to f105
xfer b109 f109 ;Return loops {397 on yarn C2.2} on b109 to f109
xfer b113 f113 ;Return loops {419 on yarn C3.3} on b113 to f113
xfer b117 f117 ;Return loops {398 on yarn C2.2} on b117 to f117
knit + b3 1 ;knit loops: [495 on yarn C1.1]. 
knit + f5 1 ;knit loops: [496 on yarn C1.1]. 
knit + b7 1 ;knit loops: [497 on yarn C1.1]. 
knit + f13 1 ;knit loops: [498 on yarn C1.1]. 
knit + f21 1 ;knit loops: [499 on yarn C1.1]. 
knit + f29 1 ;knit loops: [500 on yarn C1.1]. 
knit + b35 1 ;knit loops: [501 on yarn C1.1]. 
knit + f37 1 ;knit loops: [502 on yarn C1.1]. 
knit + b39 1 ;knit loops: [503 on yarn C1.1]. 
knit + b43 1 ;knit loops: [504 on yarn C1.1]. 
knit + f45 1 ;knit loops: [505 on yarn C1.1]. 
knit + b47 1 ;knit loops: [506 on yarn C1.1]. 
knit + b51 1 ;knit loops: [507 on yarn C1.1]. 
knit + f53 1 ;knit loops: [508 on yarn C1.1]. 
knit + b55 1 ;knit loops: [509 on yarn C1.1]. 
knit + b59 1 ;knit loops: [510 on yarn C1.1]. 
knit + f61 1 ;knit loops: [511 on yarn C1.1]. 
knit + b63 1 ;knit loops: [512 on yarn C1.1]. 
knit + b67 1 ;knit loops: [513 on yarn C1.1]. 
knit + f69 1 ;knit loops: [514 on yarn C1.1]. 
knit + b71 1 ;knit loops: [515 on yarn C1.1]. 
knit + b75 1 ;knit loops: [516 on yarn C1.1]. 
knit + f77 1 ;knit loops: [517 on yarn C1.1]. 
knit + b79 1 ;knit loops: [518 on yarn C1.1]. 
knit + b83 1 ;knit loops: [519 on yarn C1.1]. 
knit + f85 1 ;knit loops: [520 on yarn C1.1]. 
knit + b87 1 ;knit loops: [521 on yarn C1.1]. 
knit + b91 1 ;knit loops: [522 on yarn C1.1]. 
knit + f93 1 ;knit loops: [523 on yarn C1.1]. 
knit + b95 1 ;knit loops: [524 on yarn C1.1]. 
knit + b99 1 ;knit loops: [525 on yarn C1.1]. 
knit + f101 1 ;knit loops: [526 on yarn C1.1]. 
knit + b103 1 ;knit loops: [527 on yarn C1.1]. 
knit + b107 1 ;knit loops: [528 on yarn C1.1]. 
knit + f109 1 ;knit loops: [529 on yarn C1.1]. 
knit + b111 1 ;knit loops: [530 on yarn C1.1]. 
knit + b115 1 ;knit loops: [531 on yarn C1.1]. 
knit + f117 1 ;knit loops: [532 on yarn C1.1]. 
knit + b119 1 ;knit loops: [533 on yarn C1.1]. 
knit + f1 2 ;knit loops: [534 on yarn C2.2]. 
knit + f9 2 ;knit loops: [535 on yarn C2.2]. 
knit + f17 2 ;knit loops: [536 on yarn C2.2]. 
knit + f25 2 ;knit loops: [537 on yarn C2.2]. 
knit + f33 2 ;knit loops: [538 on yarn C2.2]. 
knit + f41 2 ;knit loops: [539 on yarn C2.2]. 
knit + f49 2 ;knit loops: [540 on yarn C2.2]. 
knit + f57 2 ;knit loops: [541 on yarn C2.2]. 
knit + f65 2 ;knit loops: [542 on yarn C2.2]. 
knit + f73 2 ;knit loops: [543 on yarn C2.2]. 
knit + f81 2 ;knit loops: [544 on yarn C2.2]. 
knit + f89 2 ;knit loops: [545 on yarn C2.2]. 
knit + f97 2 ;knit loops: [546 on yarn C2.2]. 
knit + f105 2 ;knit loops: [547 on yarn C2.2]. 
knit + f113 2 ;knit loops: [548 on yarn C2.2]. 
knit + f5 3 ;knit loops: [549 on yarn C3.3]. 
knit + b11 3 ;knit loops: [550 on yarn C3.3]. 
knit + f13 3 ;knit loops: [551 on yarn C3.3]. 
knit + b15 3 ;knit loops: [552 on yarn C3.3]. 
knit + b19 3 ;knit loops: [553 on yarn C3.3]. 
knit + f21 3 ;knit loops: [554 on yarn C3.3]. 
knit + b23 3 ;knit loops: [555 on yarn C3.3]. 
knit + b27 3 ;knit loops: [556 on yarn C3.3]. 
knit + f29 3 ;knit loops: [557 on yarn C3.3]. 
knit + b31 3 ;knit loops: [558 on yarn C3.3]. 
knit + f37 3 ;knit loops: [559 on yarn C3.3]. 
knit + f45 3 ;knit loops: [560 on yarn C3.3]. 
knit + f53 3 ;knit loops: [561 on yarn C3.3]. 
knit + f61 3 ;knit loops: [562 on yarn C3.3]. 
knit + f69 3 ;knit loops: [563 on yarn C3.3]. 
knit + f77 3 ;knit loops: [564 on yarn C3.3]. 
knit + f85 3 ;knit loops: [565 on yarn C3.3]. 
knit + f93 3 ;knit loops: [566 on yarn C3.3]. 
knit + f101 3 ;knit loops: [567 on yarn C3.3]. 
knit + f109 3 ;knit loops: [568 on yarn C3.3]. 
knit + f117 3 ;knit loops: [569 on yarn C3.3]. 
;KP Printout: 3: stripe 0: [f12, f16, f20, f24, f28, f32]
;Resetting to sheet s0:g4 of 4
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f5 b5 ;
xfer f9 b9 ;
xfer f13 b13 ;
xfer f17 b17 ;
xfer f21 b21 ;
xfer f25 b25 ;
xfer f29 b29 ;
xfer f33 b33 ;
xfer f37 b37 ;
xfer f41 b41 ;
xfer f45 b45 ;
xfer f49 b49 ;
xfer f53 b53 ;
xfer f57 b57 ;
xfer f61 b61 ;
xfer f65 b65 ;
xfer f69 b69 ;
xfer f73 b73 ;
xfer f77 b77 ;
xfer f81 b81 ;
xfer f85 b85 ;
xfer f89 b89 ;
xfer f93 b93 ;
xfer f97 b97 ;
xfer f101 b101 ;
xfer f105 b105 ;
xfer f109 b109 ;
xfer f113 b113 ;
xfer f117 b117 ;
; Peel sheet 2 relative to 0
; Peel sheet 3 relative to 0
xfer f2 b2 ;return loops {494 on yarn C3.3} on f2 to b2
xfer f6 b6 ;return loops {479 on yarn C2.2} on f6 to b6
xfer f10 b10 ;return loops {493 on yarn C3.3} on f10 to b10
xfer f14 b14 ;return loops {476 on yarn C2.2} on f14 to b14
xfer f18 b18 ;return loops {492 on yarn C3.3} on f18 to b18
xfer f22 b22 ;return loops {473 on yarn C2.2} on f22 to b22
xfer f26 b26 ;return loops {491 on yarn C3.3} on f26 to b26
xfer f30 b30 ;return loops {470 on yarn C2.2} on f30 to b30
xfer f34 b34 ;return loops {490 on yarn C3.3} on f34 to b34
xfer f38 b38 ;return loops {469 on yarn C2.2} on f38 to b38
xfer f42 b42 ;return loops {489 on yarn C3.3} on f42 to b42
xfer f46 b46 ;return loops {468 on yarn C2.2} on f46 to b46
xfer f50 b50 ;return loops {488 on yarn C3.3} on f50 to b50
xfer f54 b54 ;return loops {467 on yarn C2.2} on f54 to b54
xfer f58 b58 ;return loops {487 on yarn C3.3} on f58 to b58
xfer f62 b62 ;return loops {466 on yarn C2.2} on f62 to b62
xfer f66 b66 ;return loops {486 on yarn C3.3} on f66 to b66
xfer f70 b70 ;return loops {465 on yarn C2.2} on f70 to b70
xfer f74 b74 ;return loops {485 on yarn C3.3} on f74 to b74
xfer f78 b78 ;return loops {464 on yarn C2.2} on f78 to b78
xfer f82 b82 ;return loops {484 on yarn C3.3} on f82 to b82
xfer f86 b86 ;return loops {463 on yarn C2.2} on f86 to b86
xfer f90 b90 ;return loops {483 on yarn C3.3} on f90 to b90
xfer f94 b94 ;return loops {462 on yarn C2.2} on f94 to b94
xfer f98 b98 ;return loops {482 on yarn C3.3} on f98 to b98
xfer f102 b102 ;return loops {461 on yarn C2.2} on f102 to b102
xfer f106 b106 ;return loops {481 on yarn C3.3} on f106 to b106
xfer f110 b110 ;return loops {460 on yarn C2.2} on f110 to b110
xfer f114 b114 ;return loops {480 on yarn C3.3} on f114 to b114
xfer f118 b118 ;return loops {459 on yarn C2.2} on f118 to b118
knit - b118 1 ;knit loops: [570 on yarn C1.1]. 
knit - f116 1 ;knit loops: [571 on yarn C1.1]. 
knit - f112 1 ;knit loops: [572 on yarn C1.1]. 
knit - b110 1 ;knit loops: [573 on yarn C1.1]. 
knit - f108 1 ;knit loops: [574 on yarn C1.1]. 
knit - f104 1 ;knit loops: [575 on yarn C1.1]. 
knit - b102 1 ;knit loops: [576 on yarn C1.1]. 
knit - f100 1 ;knit loops: [577 on yarn C1.1]. 
knit - f96 1 ;knit loops: [578 on yarn C1.1]. 
knit - b94 1 ;knit loops: [579 on yarn C1.1]. 
knit - f92 1 ;knit loops: [580 on yarn C1.1]. 
knit - f88 1 ;knit loops: [581 on yarn C1.1]. 
knit - b86 1 ;knit loops: [582 on yarn C1.1]. 
knit - f84 1 ;knit loops: [583 on yarn C1.1]. 
knit - f80 1 ;knit loops: [584 on yarn C1.1]. 
knit - b78 1 ;knit loops: [585 on yarn C1.1]. 
knit - f76 1 ;knit loops: [586 on yarn C1.1]. 
knit - f72 1 ;knit loops: [587 on yarn C1.1]. 
knit - b70 1 ;knit loops: [588 on yarn C1.1]. 
knit - f68 1 ;knit loops: [589 on yarn C1.1]. 
knit - f64 1 ;knit loops: [590 on yarn C1.1]. 
knit - b62 1 ;knit loops: [591 on yarn C1.1]. 
knit - f60 1 ;knit loops: [592 on yarn C1.1]. 
knit - f56 1 ;knit loops: [593 on yarn C1.1]. 
knit - b54 1 ;knit loops: [594 on yarn C1.1]. 
knit - f52 1 ;knit loops: [595 on yarn C1.1]. 
knit - f48 1 ;knit loops: [596 on yarn C1.1]. 
knit - b46 1 ;knit loops: [597 on yarn C1.1]. 
knit - f44 1 ;knit loops: [598 on yarn C1.1]. 
knit - f40 1 ;knit loops: [599 on yarn C1.1]. 
knit - b38 1 ;knit loops: [600 on yarn C1.1]. 
knit - f36 1 ;knit loops: [601 on yarn C1.1]. 
knit - b30 1 ;knit loops: [602 on yarn C1.1]. 
knit - b22 1 ;knit loops: [603 on yarn C1.1]. 
knit - b14 1 ;knit loops: [604 on yarn C1.1]. 
knit - f8 1 ;knit loops: [605 on yarn C1.1]. 
knit - b6 1 ;knit loops: [606 on yarn C1.1]. 
knit - f4 1 ;knit loops: [607 on yarn C1.1]. 
knit - f0 1 ;knit loops: [608 on yarn C1.1]. 
knit - b114 2 ;knit loops: [609 on yarn C2.2]. 
knit - b106 2 ;knit loops: [610 on yarn C2.2]. 
knit - b98 2 ;knit loops: [611 on yarn C2.2]. 
knit - b90 2 ;knit loops: [612 on yarn C2.2]. 
knit - b82 2 ;knit loops: [613 on yarn C2.2]. 
knit - b74 2 ;knit loops: [614 on yarn C2.2]. 
knit - b66 2 ;knit loops: [615 on yarn C2.2]. 
knit - b58 2 ;knit loops: [616 on yarn C2.2]. 
knit - b50 2 ;knit loops: [617 on yarn C2.2]. 
knit - b42 2 ;knit loops: [618 on yarn C2.2]. 
knit - b34 2 ;knit loops: [619 on yarn C2.2]. 
knit - f32 2 ;knit loops: [620 on yarn C2.2]. 
knit - f28 2 ;knit loops: [621 on yarn C2.2]. 
knit - b26 2 ;knit loops: [622 on yarn C2.2]. 
knit - f24 2 ;knit loops: [623 on yarn C2.2]. 
knit - f20 2 ;knit loops: [624 on yarn C2.2]. 
knit - b18 2 ;knit loops: [625 on yarn C2.2]. 
knit - f16 2 ;knit loops: [626 on yarn C2.2]. 
knit - f12 2 ;knit loops: [627 on yarn C2.2]. 
knit - b10 2 ;knit loops: [628 on yarn C2.2]. 
knit - b2 2 ;knit loops: [629 on yarn C2.2]. 
knit - b118 3 ;knit loops: [630 on yarn C3.3]. 
knit - b110 3 ;knit loops: [631 on yarn C3.3]. 
knit - b102 3 ;knit loops: [632 on yarn C3.3]. 
knit - b94 3 ;knit loops: [633 on yarn C3.3]. 
knit - b86 3 ;knit loops: [634 on yarn C3.3]. 
knit - b78 3 ;knit loops: [635 on yarn C3.3]. 
knit - b70 3 ;knit loops: [636 on yarn C3.3]. 
knit - b62 3 ;knit loops: [637 on yarn C3.3]. 
knit - b54 3 ;knit loops: [638 on yarn C3.3]. 
knit - b46 3 ;knit loops: [639 on yarn C3.3]. 
knit - b38 3 ;knit loops: [640 on yarn C3.3]. 
knit - b30 3 ;knit loops: [641 on yarn C3.3]. 
knit - b22 3 ;knit loops: [642 on yarn C3.3]. 
knit - b14 3 ;knit loops: [643 on yarn C3.3]. 
knit - b6 3 ;knit loops: [644 on yarn C3.3]. 
;KP Printout: 3: stripe 1: [b15, b19, b23, b27, b31, b35]
;Resetting to sheet s3:g4 of 4
; Peel sheet 0 relative to 3
; Peel sheet 1 relative to 3
; Peel sheet 2 relative to 3
xfer b2 f2 ;
xfer b6 f6 ;
xfer b10 f10 ;
xfer b14 f14 ;
xfer b18 f18 ;
xfer b22 f22 ;
xfer b26 f26 ;
xfer b30 f30 ;
xfer b34 f34 ;
xfer b38 f38 ;
xfer b42 f42 ;
xfer b46 f46 ;
xfer b50 f50 ;
xfer b54 f54 ;
xfer b58 f58 ;
xfer b62 f62 ;
xfer b66 f66 ;
xfer b70 f70 ;
xfer b74 f74 ;
xfer b78 f78 ;
xfer b82 f82 ;
xfer b86 f86 ;
xfer b90 f90 ;
xfer b94 f94 ;
xfer b98 f98 ;
xfer b102 f102 ;
xfer b106 f106 ;
xfer b110 f110 ;
xfer b114 f114 ;
xfer b118 f118 ;
; Peel sheet 3 relative to 3
xfer b1 f1 ;Return loops {534 on yarn C2.2} on b1 to f1
xfer b5 f5 ;Return loops {549 on yarn C3.3} on b5 to f5
xfer b9 f9 ;Return loops {535 on yarn C2.2} on b9 to f9
xfer b13 f13 ;Return loops {551 on yarn C3.3} on b13 to f13
xfer b17 f17 ;Return loops {536 on yarn C2.2} on b17 to f17
xfer b21 f21 ;Return loops {554 on yarn C3.3} on b21 to f21
xfer b25 f25 ;Return loops {537 on yarn C2.2} on b25 to f25
xfer b29 f29 ;Return loops {557 on yarn C3.3} on b29 to f29
xfer b33 f33 ;Return loops {538 on yarn C2.2} on b33 to f33
xfer b37 f37 ;Return loops {559 on yarn C3.3} on b37 to f37
xfer b41 f41 ;Return loops {539 on yarn C2.2} on b41 to f41
xfer b45 f45 ;Return loops {560 on yarn C3.3} on b45 to f45
xfer b49 f49 ;Return loops {540 on yarn C2.2} on b49 to f49
xfer b53 f53 ;Return loops {561 on yarn C3.3} on b53 to f53
xfer b57 f57 ;Return loops {541 on yarn C2.2} on b57 to f57
xfer b61 f61 ;Return loops {562 on yarn C3.3} on b61 to f61
xfer b65 f65 ;Return loops {542 on yarn C2.2} on b65 to f65
xfer b69 f69 ;Return loops {563 on yarn C3.3} on b69 to f69
xfer b73 f73 ;Return loops {543 on yarn C2.2} on b73 to f73
xfer b77 f77 ;Return loops {564 on yarn C3.3} on b77 to f77
xfer b81 f81 ;Return loops {544 on yarn C2.2} on b81 to f81
xfer b85 f85 ;Return loops {565 on yarn C3.3} on b85 to f85
xfer b89 f89 ;Return loops {545 on yarn C2.2} on b89 to f89
xfer b93 f93 ;Return loops {566 on yarn C3.3} on b93 to f93
xfer b97 f97 ;Return loops {546 on yarn C2.2} on b97 to f97
xfer b101 f101 ;Return loops {567 on yarn C3.3} on b101 to f101
xfer b105 f105 ;Return loops {547 on yarn C2.2} on b105 to f105
xfer b109 f109 ;Return loops {568 on yarn C3.3} on b109 to f109
xfer b113 f113 ;Return loops {548 on yarn C2.2} on b113 to f113
xfer b117 f117 ;Return loops {569 on yarn C3.3} on b117 to f117
knit + f1 1 ;knit loops: [645 on yarn C1.1]. 
knit + b3 1 ;knit loops: [646 on yarn C1.1]. 
knit + b7 1 ;knit loops: [647 on yarn C1.1]. 
knit + f9 1 ;knit loops: [648 on yarn C1.1]. 
knit + b11 1 ;knit loops: [649 on yarn C1.1]. 
knit + f17 1 ;knit loops: [650 on yarn C1.1]. 
knit + f25 1 ;knit loops: [651 on yarn C1.1]. 
knit + f33 1 ;knit loops: [652 on yarn C1.1]. 
knit + b39 1 ;knit loops: [653 on yarn C1.1]. 
knit + f41 1 ;knit loops: [654 on yarn C1.1]. 
knit + b43 1 ;knit loops: [655 on yarn C1.1]. 
knit + b47 1 ;knit loops: [656 on yarn C1.1]. 
knit + f49 1 ;knit loops: [657 on yarn C1.1]. 
knit + b51 1 ;knit loops: [658 on yarn C1.1]. 
knit + b55 1 ;knit loops: [659 on yarn C1.1]. 
knit + f57 1 ;knit loops: [660 on yarn C1.1]. 
knit + b59 1 ;knit loops: [661 on yarn C1.1]. 
knit + b63 1 ;knit loops: [662 on yarn C1.1]. 
knit + f65 1 ;knit loops: [663 on yarn C1.1]. 
knit + b67 1 ;knit loops: [664 on yarn C1.1]. 
knit + b71 1 ;knit loops: [665 on yarn C1.1]. 
knit + f73 1 ;knit loops: [666 on yarn C1.1]. 
knit + b75 1 ;knit loops: [667 on yarn C1.1]. 
knit + b79 1 ;knit loops: [668 on yarn C1.1]. 
knit + f81 1 ;knit loops: [669 on yarn C1.1]. 
knit + b83 1 ;knit loops: [670 on yarn C1.1]. 
knit + b87 1 ;knit loops: [671 on yarn C1.1]. 
knit + f89 1 ;knit loops: [672 on yarn C1.1]. 
knit + b91 1 ;knit loops: [673 on yarn C1.1]. 
knit + b95 1 ;knit loops: [674 on yarn C1.1]. 
knit + f97 1 ;knit loops: [675 on yarn C1.1]. 
knit + b99 1 ;knit loops: [676 on yarn C1.1]. 
knit + b103 1 ;knit loops: [677 on yarn C1.1]. 
knit + f105 1 ;knit loops: [678 on yarn C1.1]. 
knit + b107 1 ;knit loops: [679 on yarn C1.1]. 
knit + b111 1 ;knit loops: [680 on yarn C1.1]. 
knit + f113 1 ;knit loops: [681 on yarn C1.1]. 
knit + b115 1 ;knit loops: [682 on yarn C1.1]. 
knit + b119 1 ;knit loops: [683 on yarn C1.1]. 
knit + f5 2 ;knit loops: [684 on yarn C2.2]. 
knit + f13 2 ;knit loops: [685 on yarn C2.2]. 
knit + f21 2 ;knit loops: [686 on yarn C2.2]. 
knit + f29 2 ;knit loops: [687 on yarn C2.2]. 
knit + f37 2 ;knit loops: [688 on yarn C2.2]. 
knit + f45 2 ;knit loops: [689 on yarn C2.2]. 
knit + f53 2 ;knit loops: [690 on yarn C2.2]. 
knit + f61 2 ;knit loops: [691 on yarn C2.2]. 
knit + f69 2 ;knit loops: [692 on yarn C2.2]. 
knit + f77 2 ;knit loops: [693 on yarn C2.2]. 
knit + f85 2 ;knit loops: [694 on yarn C2.2]. 
knit + f93 2 ;knit loops: [695 on yarn C2.2]. 
knit + f101 2 ;knit loops: [696 on yarn C2.2]. 
knit + f109 2 ;knit loops: [697 on yarn C2.2]. 
knit + f117 2 ;knit loops: [698 on yarn C2.2]. 
knit + f1 3 ;knit loops: [699 on yarn C3.3]. 
knit + f9 3 ;knit loops: [700 on yarn C3.3]. 
knit + b15 3 ;knit loops: [701 on yarn C3.3]. 
knit + f17 3 ;knit loops: [702 on yarn C3.3]. 
knit + b19 3 ;knit loops: [703 on yarn C3.3]. 
knit + b23 3 ;knit loops: [704 on yarn C3.3]. 
knit + f25 3 ;knit loops: [705 on yarn C3.3]. 
knit + b27 3 ;knit loops: [706 on yarn C3.3]. 
knit + b31 3 ;knit loops: [707 on yarn C3.3]. 
knit + f33 3 ;knit loops: [708 on yarn C3.3]. 
knit + b35 3 ;knit loops: [709 on yarn C3.3]. 
knit + f41 3 ;knit loops: [710 on yarn C3.3]. 
knit + f49 3 ;knit loops: [711 on yarn C3.3]. 
knit + f57 3 ;knit loops: [712 on yarn C3.3]. 
knit + f65 3 ;knit loops: [713 on yarn C3.3]. 
knit + f73 3 ;knit loops: [714 on yarn C3.3]. 
knit + f81 3 ;knit loops: [715 on yarn C3.3]. 
knit + f89 3 ;knit loops: [716 on yarn C3.3]. 
knit + f97 3 ;knit loops: [717 on yarn C3.3]. 
knit + f105 3 ;knit loops: [718 on yarn C3.3]. 
knit + f113 3 ;knit loops: [719 on yarn C3.3]. 
;KP Printout: 4: stripe 0: [f16, f20, f24, f28, f32, f36]
;Resetting to sheet s0:g4 of 4
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f5 b5 ;
xfer f9 b9 ;
xfer f13 b13 ;
xfer f17 b17 ;
xfer f21 b21 ;
xfer f25 b25 ;
xfer f29 b29 ;
xfer f33 b33 ;
xfer f37 b37 ;
xfer f41 b41 ;
xfer f45 b45 ;
xfer f49 b49 ;
xfer f53 b53 ;
xfer f57 b57 ;
xfer f61 b61 ;
xfer f65 b65 ;
xfer f69 b69 ;
xfer f73 b73 ;
xfer f77 b77 ;
xfer f81 b81 ;
xfer f85 b85 ;
xfer f89 b89 ;
xfer f93 b93 ;
xfer f97 b97 ;
xfer f101 b101 ;
xfer f105 b105 ;
xfer f109 b109 ;
xfer f113 b113 ;
xfer f117 b117 ;
; Peel sheet 2 relative to 0
; Peel sheet 3 relative to 0
xfer f2 b2 ;return loops {629 on yarn C2.2} on f2 to b2
xfer f6 b6 ;return loops {644 on yarn C3.3} on f6 to b6
xfer f10 b10 ;return loops {628 on yarn C2.2} on f10 to b10
xfer f14 b14 ;return loops {643 on yarn C3.3} on f14 to b14
xfer f18 b18 ;return loops {625 on yarn C2.2} on f18 to b18
xfer f22 b22 ;return loops {642 on yarn C3.3} on f22 to b22
xfer f26 b26 ;return loops {622 on yarn C2.2} on f26 to b26
xfer f30 b30 ;return loops {641 on yarn C3.3} on f30 to b30
xfer f34 b34 ;return loops {619 on yarn C2.2} on f34 to b34
xfer f38 b38 ;return loops {640 on yarn C3.3} on f38 to b38
xfer f42 b42 ;return loops {618 on yarn C2.2} on f42 to b42
xfer f46 b46 ;return loops {639 on yarn C3.3} on f46 to b46
xfer f50 b50 ;return loops {617 on yarn C2.2} on f50 to b50
xfer f54 b54 ;return loops {638 on yarn C3.3} on f54 to b54
xfer f58 b58 ;return loops {616 on yarn C2.2} on f58 to b58
xfer f62 b62 ;return loops {637 on yarn C3.3} on f62 to b62
xfer f66 b66 ;return loops {615 on yarn C2.2} on f66 to b66
xfer f70 b70 ;return loops {636 on yarn C3.3} on f70 to b70
xfer f74 b74 ;return loops {614 on yarn C2.2} on f74 to b74
xfer f78 b78 ;return loops {635 on yarn C3.3} on f78 to b78
xfer f82 b82 ;return loops {613 on yarn C2.2} on f82 to b82
xfer f86 b86 ;return loops {634 on yarn C3.3} on f86 to b86
xfer f90 b90 ;return loops {612 on yarn C2.2} on f90 to b90
xfer f94 b94 ;return loops {633 on yarn C3.3} on f94 to b94
xfer f98 b98 ;return loops {611 on yarn C2.2} on f98 to b98
xfer f102 b102 ;return loops {632 on yarn C3.3} on f102 to b102
xfer f106 b106 ;return loops {610 on yarn C2.2} on f106 to b106
xfer f110 b110 ;return loops {631 on yarn C3.3} on f110 to b110
xfer f114 b114 ;return loops {609 on yarn C2.2} on f114 to b114
xfer f118 b118 ;return loops {630 on yarn C3.3} on f118 to b118
knit - f116 1 ;knit loops: [720 on yarn C1.1]. 
knit - b114 1 ;knit loops: [721 on yarn C1.1]. 
knit - f112 1 ;knit loops: [722 on yarn C1.1]. 
knit - f108 1 ;knit loops: [723 on yarn C1.1]. 
knit - b106 1 ;knit loops: [724 on yarn C1.1]. 
knit - f104 1 ;knit loops: [725 on yarn C1.1]. 
knit - f100 1 ;knit loops: [726 on yarn C1.1]. 
knit - b98 1 ;knit loops: [727 on yarn C1.1]. 
knit - f96 1 ;knit loops: [728 on yarn C1.1]. 
knit - f92 1 ;knit loops: [729 on yarn C1.1]. 
knit - b90 1 ;knit loops: [730 on yarn C1.1]. 
knit - f88 1 ;knit loops: [731 on yarn C1.1]. 
knit - f84 1 ;knit loops: [732 on yarn C1.1]. 
knit - b82 1 ;knit loops: [733 on yarn C1.1]. 
knit - f80 1 ;knit loops: [734 on yarn C1.1]. 
knit - f76 1 ;knit loops: [735 on yarn C1.1]. 
knit - b74 1 ;knit loops: [736 on yarn C1.1]. 
knit - f72 1 ;knit loops: [737 on yarn C1.1]. 
knit - f68 1 ;knit loops: [738 on yarn C1.1]. 
knit - b66 1 ;knit loops: [739 on yarn C1.1]. 
knit - f64 1 ;knit loops: [740 on yarn C1.1]. 
knit - f60 1 ;knit loops: [741 on yarn C1.1]. 
knit - b58 1 ;knit loops: [742 on yarn C1.1]. 
knit - f56 1 ;knit loops: [743 on yarn C1.1]. 
knit - f52 1 ;knit loops: [744 on yarn C1.1]. 
knit - b50 1 ;knit loops: [745 on yarn C1.1]. 
knit - f48 1 ;knit loops: [746 on yarn C1.1]. 
knit - f44 1 ;knit loops: [747 on yarn C1.1]. 
knit - b42 1 ;knit loops: [748 on yarn C1.1]. 
knit - f40 1 ;knit loops: [749 on yarn C1.1]. 
knit - b34 1 ;knit loops: [750 on yarn C1.1]. 
knit - b26 1 ;knit loops: [751 on yarn C1.1]. 
knit - b18 1 ;knit loops: [752 on yarn C1.1]. 
knit - f12 1 ;knit loops: [753 on yarn C1.1]. 
knit - b10 1 ;knit loops: [754 on yarn C1.1]. 
knit - f8 1 ;knit loops: [755 on yarn C1.1]. 
knit - f4 1 ;knit loops: [756 on yarn C1.1]. 
knit - b2 1 ;knit loops: [757 on yarn C1.1]. 
knit - f0 1 ;knit loops: [758 on yarn C1.1]. 
knit - b118 2 ;knit loops: [759 on yarn C2.2]. 
knit - b110 2 ;knit loops: [760 on yarn C2.2]. 
knit - b102 2 ;knit loops: [761 on yarn C2.2]. 
knit - b94 2 ;knit loops: [762 on yarn C2.2]. 
knit - b86 2 ;knit loops: [763 on yarn C2.2]. 
knit - b78 2 ;knit loops: [764 on yarn C2.2]. 
knit - b70 2 ;knit loops: [765 on yarn C2.2]. 
knit - b62 2 ;knit loops: [766 on yarn C2.2]. 
knit - b54 2 ;knit loops: [767 on yarn C2.2]. 
knit - b46 2 ;knit loops: [768 on yarn C2.2]. 
knit - b38 2 ;knit loops: [769 on yarn C2.2]. 
knit - f36 2 ;knit loops: [770 on yarn C2.2]. 
knit - f32 2 ;knit loops: [771 on yarn C2.2]. 
knit - b30 2 ;knit loops: [772 on yarn C2.2]. 
knit - f28 2 ;knit loops: [773 on yarn C2.2]. 
knit - f24 2 ;knit loops: [774 on yarn C2.2]. 
knit - b22 2 ;knit loops: [775 on yarn C2.2]. 
knit - f20 2 ;knit loops: [776 on yarn C2.2]. 
knit - f16 2 ;knit loops: [777 on yarn C2.2]. 
knit - b14 2 ;knit loops: [778 on yarn C2.2]. 
knit - b6 2 ;knit loops: [779 on yarn C2.2]. 
knit - b114 3 ;knit loops: [780 on yarn C3.3]. 
knit - b106 3 ;knit loops: [781 on yarn C3.3]. 
knit - b98 3 ;knit loops: [782 on yarn C3.3]. 
knit - b90 3 ;knit loops: [783 on yarn C3.3]. 
knit - b82 3 ;knit loops: [784 on yarn C3.3]. 
knit - b74 3 ;knit loops: [785 on yarn C3.3]. 
knit - b66 3 ;knit loops: [786 on yarn C3.3]. 
knit - b58 3 ;knit loops: [787 on yarn C3.3]. 
knit - b50 3 ;knit loops: [788 on yarn C3.3]. 
knit - b42 3 ;knit loops: [789 on yarn C3.3]. 
knit - b34 3 ;knit loops: [790 on yarn C3.3]. 
knit - b26 3 ;knit loops: [791 on yarn C3.3]. 
knit - b18 3 ;knit loops: [792 on yarn C3.3]. 
knit - b10 3 ;knit loops: [793 on yarn C3.3]. 
knit - b2 3 ;knit loops: [794 on yarn C3.3]. 
;KP Printout: 4: stripe 1: [b19, b23, b27, b31, b35, b39]
;Resetting to sheet s3:g4 of 4
; Peel sheet 0 relative to 3
; Peel sheet 1 relative to 3
; Peel sheet 2 relative to 3
xfer b2 f2 ;
xfer b6 f6 ;
xfer b10 f10 ;
xfer b14 f14 ;
xfer b18 f18 ;
xfer b22 f22 ;
xfer b26 f26 ;
xfer b30 f30 ;
xfer b34 f34 ;
xfer b38 f38 ;
xfer b42 f42 ;
xfer b46 f46 ;
xfer b50 f50 ;
xfer b54 f54 ;
xfer b58 f58 ;
xfer b62 f62 ;
xfer b66 f66 ;
xfer b70 f70 ;
xfer b74 f74 ;
xfer b78 f78 ;
xfer b82 f82 ;
xfer b86 f86 ;
xfer b90 f90 ;
xfer b94 f94 ;
xfer b98 f98 ;
xfer b102 f102 ;
xfer b106 f106 ;
xfer b110 f110 ;
xfer b114 f114 ;
xfer b118 f118 ;
; Peel sheet 3 relative to 3
xfer b1 f1 ;Return loops {699 on yarn C3.3} on b1 to f1
xfer b5 f5 ;Return loops {684 on yarn C2.2} on b5 to f5
xfer b9 f9 ;Return loops {700 on yarn C3.3} on b9 to f9
xfer b13 f13 ;Return loops {685 on yarn C2.2} on b13 to f13
xfer b17 f17 ;Return loops {702 on yarn C3.3} on b17 to f17
xfer b21 f21 ;Return loops {686 on yarn C2.2} on b21 to f21
xfer b25 f25 ;Return loops {705 on yarn C3.3} on b25 to f25
xfer b29 f29 ;Return loops {687 on yarn C2.2} on b29 to f29
xfer b33 f33 ;Return loops {708 on yarn C3.3} on b33 to f33
xfer b37 f37 ;Return loops {688 on yarn C2.2} on b37 to f37
xfer b41 f41 ;Return loops {710 on yarn C3.3} on b41 to f41
xfer b45 f45 ;Return loops {689 on yarn C2.2} on b45 to f45
xfer b49 f49 ;Return loops {711 on yarn C3.3} on b49 to f49
xfer b53 f53 ;Return loops {690 on yarn C2.2} on b53 to f53
xfer b57 f57 ;Return loops {712 on yarn C3.3} on b57 to f57
xfer b61 f61 ;Return loops {691 on yarn C2.2} on b61 to f61
xfer b65 f65 ;Return loops {713 on yarn C3.3} on b65 to f65
xfer b69 f69 ;Return loops {692 on yarn C2.2} on b69 to f69
xfer b73 f73 ;Return loops {714 on yarn C3.3} on b73 to f73
xfer b77 f77 ;Return loops {693 on yarn C2.2} on b77 to f77
xfer b81 f81 ;Return loops {715 on yarn C3.3} on b81 to f81
xfer b85 f85 ;Return loops {694 on yarn C2.2} on b85 to f85
xfer b89 f89 ;Return loops {716 on yarn C3.3} on b89 to f89
xfer b93 f93 ;Return loops {695 on yarn C2.2} on b93 to f93
xfer b97 f97 ;Return loops {717 on yarn C3.3} on b97 to f97
xfer b101 f101 ;Return loops {696 on yarn C2.2} on b101 to f101
xfer b105 f105 ;Return loops {718 on yarn C3.3} on b105 to f105
xfer b109 f109 ;Return loops {697 on yarn C2.2} on b109 to f109
xfer b113 f113 ;Return loops {719 on yarn C3.3} on b113 to f113
xfer b117 f117 ;Return loops {698 on yarn C2.2} on b117 to f117
knit + b3 1 ;knit loops: [795 on yarn C1.1]. 
knit + f5 1 ;knit loops: [796 on yarn C1.1]. 
knit + b7 1 ;knit loops: [797 on yarn C1.1]. 
knit + b11 1 ;knit loops: [798 on yarn C1.1]. 
knit + f13 1 ;knit loops: [799 on yarn C1.1]. 
knit + b15 1 ;knit loops: [800 on yarn C1.1]. 
knit + f21 1 ;knit loops: [801 on yarn C1.1]. 
knit + f29 1 ;knit loops: [802 on yarn C1.1]. 
knit + f37 1 ;knit loops: [803 on yarn C1.1]. 
knit + b43 1 ;knit loops: [804 on yarn C1.1]. 
knit + f45 1 ;knit loops: [805 on yarn C1.1]. 
knit + b47 1 ;knit loops: [806 on yarn C1.1]. 
knit + b51 1 ;knit loops: [807 on yarn C1.1]. 
knit + f53 1 ;knit loops: [808 on yarn C1.1]. 
knit + b55 1 ;knit loops: [809 on yarn C1.1]. 
knit + b59 1 ;knit loops: [810 on yarn C1.1]. 
knit + f61 1 ;knit loops: [811 on yarn C1.1]. 
knit + b63 1 ;knit loops: [812 on yarn C1.1]. 
knit + b67 1 ;knit loops: [813 on yarn C1.1]. 
knit + f69 1 ;knit loops: [814 on yarn C1.1]. 
knit + b71 1 ;knit loops: [815 on yarn C1.1]. 
knit + b75 1 ;knit loops: [816 on yarn C1.1]. 
knit + f77 1 ;knit loops: [817 on yarn C1.1]. 
knit + b79 1 ;knit loops: [818 on yarn C1.1]. 
knit + b83 1 ;knit loops: [819 on yarn C1.1]. 
knit + f85 1 ;knit loops: [820 on yarn C1.1]. 
knit + b87 1 ;knit loops: [821 on yarn C1.1]. 
knit + b91 1 ;knit loops: [822 on yarn C1.1]. 
knit + f93 1 ;knit loops: [823 on yarn C1.1]. 
knit + b95 1 ;knit loops: [824 on yarn C1.1]. 
knit + b99 1 ;knit loops: [825 on yarn C1.1]. 
knit + f101 1 ;knit loops: [826 on yarn C1.1]. 
knit + b103 1 ;knit loops: [827 on yarn C1.1]. 
knit + b107 1 ;knit loops: [828 on yarn C1.1]. 
knit + f109 1 ;knit loops: [829 on yarn C1.1]. 
knit + b111 1 ;knit loops: [830 on yarn C1.1]. 
knit + b115 1 ;knit loops: [831 on yarn C1.1]. 
knit + f117 1 ;knit loops: [832 on yarn C1.1]. 
knit + b119 1 ;knit loops: [833 on yarn C1.1]. 
knit + f1 2 ;knit loops: [834 on yarn C2.2]. 
knit + f9 2 ;knit loops: [835 on yarn C2.2]. 
knit + f17 2 ;knit loops: [836 on yarn C2.2]. 
knit + f25 2 ;knit loops: [837 on yarn C2.2]. 
knit + f33 2 ;knit loops: [838 on yarn C2.2]. 
knit + f41 2 ;knit loops: [839 on yarn C2.2]. 
knit + f49 2 ;knit loops: [840 on yarn C2.2]. 
knit + f57 2 ;knit loops: [841 on yarn C2.2]. 
knit + f65 2 ;knit loops: [842 on yarn C2.2]. 
knit + f73 2 ;knit loops: [843 on yarn C2.2]. 
knit + f81 2 ;knit loops: [844 on yarn C2.2]. 
knit + f89 2 ;knit loops: [845 on yarn C2.2]. 
knit + f97 2 ;knit loops: [846 on yarn C2.2]. 
knit + f105 2 ;knit loops: [847 on yarn C2.2]. 
knit + f113 2 ;knit loops: [848 on yarn C2.2]. 
knit + f5 3 ;knit loops: [849 on yarn C3.3]. 
knit + f13 3 ;knit loops: [850 on yarn C3.3]. 
knit + b19 3 ;knit loops: [851 on yarn C3.3]. 
knit + f21 3 ;knit loops: [852 on yarn C3.3]. 
knit + b23 3 ;knit loops: [853 on yarn C3.3]. 
knit + b27 3 ;knit loops: [854 on yarn C3.3]. 
knit + f29 3 ;knit loops: [855 on yarn C3.3]. 
knit + b31 3 ;knit loops: [856 on yarn C3.3]. 
knit + b35 3 ;knit loops: [857 on yarn C3.3]. 
knit + f37 3 ;knit loops: [858 on yarn C3.3]. 
knit + b39 3 ;knit loops: [859 on yarn C3.3]. 
knit + f45 3 ;knit loops: [860 on yarn C3.3]. 
knit + f53 3 ;knit loops: [861 on yarn C3.3]. 
knit + f61 3 ;knit loops: [862 on yarn C3.3]. 
knit + f69 3 ;knit loops: [863 on yarn C3.3]. 
knit + f77 3 ;knit loops: [864 on yarn C3.3]. 
knit + f85 3 ;knit loops: [865 on yarn C3.3]. 
knit + f93 3 ;knit loops: [866 on yarn C3.3]. 
knit + f101 3 ;knit loops: [867 on yarn C3.3]. 
knit + f109 3 ;knit loops: [868 on yarn C3.3]. 
knit + f117 3 ;knit loops: [869 on yarn C3.3]. 
;KP Printout: 5: stripe 0: [f20, f24, f28, f32, f36, f40]
;Resetting to sheet s0:g4 of 4
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f5 b5 ;
xfer f9 b9 ;
xfer f13 b13 ;
xfer f17 b17 ;
xfer f21 b21 ;
xfer f25 b25 ;
xfer f29 b29 ;
xfer f33 b33 ;
xfer f37 b37 ;
xfer f41 b41 ;
xfer f45 b45 ;
xfer f49 b49 ;
xfer f53 b53 ;
xfer f57 b57 ;
xfer f61 b61 ;
xfer f65 b65 ;
xfer f69 b69 ;
xfer f73 b73 ;
xfer f77 b77 ;
xfer f81 b81 ;
xfer f85 b85 ;
xfer f89 b89 ;
xfer f93 b93 ;
xfer f97 b97 ;
xfer f101 b101 ;
xfer f105 b105 ;
xfer f109 b109 ;
xfer f113 b113 ;
xfer f117 b117 ;
; Peel sheet 2 relative to 0
; Peel sheet 3 relative to 0
xfer f2 b2 ;return loops {794 on yarn C3.3} on f2 to b2
xfer f6 b6 ;return loops {779 on yarn C2.2} on f6 to b6
xfer f10 b10 ;return loops {793 on yarn C3.3} on f10 to b10
xfer f14 b14 ;return loops {778 on yarn C2.2} on f14 to b14
xfer f18 b18 ;return loops {792 on yarn C3.3} on f18 to b18
xfer f22 b22 ;return loops {775 on yarn C2.2} on f22 to b22
xfer f26 b26 ;return loops {791 on yarn C3.3} on f26 to b26
xfer f30 b30 ;return loops {772 on yarn C2.2} on f30 to b30
xfer f34 b34 ;return loops {790 on yarn C3.3} on f34 to b34
xfer f38 b38 ;return loops {769 on yarn C2.2} on f38 to b38
xfer f42 b42 ;return loops {789 on yarn C3.3} on f42 to b42
xfer f46 b46 ;return loops {768 on yarn C2.2} on f46 to b46
xfer f50 b50 ;return loops {788 on yarn C3.3} on f50 to b50
xfer f54 b54 ;return loops {767 on yarn C2.2} on f54 to b54
xfer f58 b58 ;return loops {787 on yarn C3.3} on f58 to b58
xfer f62 b62 ;return loops {766 on yarn C2.2} on f62 to b62
xfer f66 b66 ;return loops {786 on yarn C3.3} on f66 to b66
xfer f70 b70 ;return loops {765 on yarn C2.2} on f70 to b70
xfer f74 b74 ;return loops {785 on yarn C3.3} on f74 to b74
xfer f78 b78 ;return loops {764 on yarn C2.2} on f78 to b78
xfer f82 b82 ;return loops {784 on yarn C3.3} on f82 to b82
xfer f86 b86 ;return loops {763 on yarn C2.2} on f86 to b86
xfer f90 b90 ;return loops {783 on yarn C3.3} on f90 to b90
xfer f94 b94 ;return loops {762 on yarn C2.2} on f94 to b94
xfer f98 b98 ;return loops {782 on yarn C3.3} on f98 to b98
xfer f102 b102 ;return loops {761 on yarn C2.2} on f102 to b102
xfer f106 b106 ;return loops {781 on yarn C3.3} on f106 to b106
xfer f110 b110 ;return loops {760 on yarn C2.2} on f110 to b110
xfer f114 b114 ;return loops {780 on yarn C3.3} on f114 to b114
xfer f118 b118 ;return loops {759 on yarn C2.2} on f118 to b118
knit - b118 1 ;knit loops: [870 on yarn C1.1]. 
knit - f116 1 ;knit loops: [871 on yarn C1.1]. 
knit - f112 1 ;knit loops: [872 on yarn C1.1]. 
knit - b110 1 ;knit loops: [873 on yarn C1.1]. 
knit - f108 1 ;knit loops: [874 on yarn C1.1]. 
knit - f104 1 ;knit loops: [875 on yarn C1.1]. 
knit - b102 1 ;knit loops: [876 on yarn C1.1]. 
knit - f100 1 ;knit loops: [877 on yarn C1.1]. 
knit - f96 1 ;knit loops: [878 on yarn C1.1]. 
knit - b94 1 ;knit loops: [879 on yarn C1.1]. 
knit - f92 1 ;knit loops: [880 on yarn C1.1]. 
knit - f88 1 ;knit loops: [881 on yarn C1.1]. 
knit - b86 1 ;knit loops: [882 on yarn C1.1]. 
knit - f84 1 ;knit loops: [883 on yarn C1.1]. 
knit - f80 1 ;knit loops: [884 on yarn C1.1]. 
knit - b78 1 ;knit loops: [885 on yarn C1.1]. 
knit - f76 1 ;knit loops: [886 on yarn C1.1]. 
knit - f72 1 ;knit loops: [887 on yarn C1.1]. 
knit - b70 1 ;knit loops: [888 on yarn C1.1]. 
knit - f68 1 ;knit loops: [889 on yarn C1.1]. 
knit - f64 1 ;knit loops: [890 on yarn C1.1]. 
knit - b62 1 ;knit loops: [891 on yarn C1.1]. 
knit - f60 1 ;knit loops: [892 on yarn C1.1]. 
knit - f56 1 ;knit loops: [893 on yarn C1.1]. 
knit - b54 1 ;knit loops: [894 on yarn C1.1]. 
knit - f52 1 ;knit loops: [895 on yarn C1.1]. 
knit - f48 1 ;knit loops: [896 on yarn C1.1]. 
knit - b46 1 ;knit loops: [897 on yarn C1.1]. 
knit - f44 1 ;knit loops: [898 on yarn C1.1]. 
knit - b38 1 ;knit loops: [899 on yarn C1.1]. 
knit - b30 1 ;knit loops: [900 on yarn C1.1]. 
knit - b22 1 ;knit loops: [901 on yarn C1.1]. 
knit - f16 1 ;knit loops: [902 on yarn C1.1]. 
knit - b14 1 ;knit loops: [903 on yarn C1.1]. 
knit - f12 1 ;knit loops: [904 on yarn C1.1]. 
knit - f8 1 ;knit loops: [905 on yarn C1.1]. 
knit - b6 1 ;knit loops: [906 on yarn C1.1]. 
knit - f4 1 ;knit loops: [907 on yarn C1.1]. 
knit - f0 1 ;knit loops: [908 on yarn C1.1]. 
knit - b114 2 ;knit loops: [909 on yarn C2.2]. 
knit - b106 2 ;knit loops: [910 on yarn C2.2]. 
knit - b98 2 ;knit loops: [911 on yarn C2.2]. 
knit - b90 2 ;knit loops: [912 on yarn C2.2]. 
knit - b82 2 ;knit loops: [913 on yarn C2.2]. 
knit - b74 2 ;knit loops: [914 on yarn C2.2]. 
knit - b66 2 ;knit loops: [915 on yarn C2.2]. 
knit - b58 2 ;knit loops: [916 on yarn C2.2]. 
knit - b50 2 ;knit loops: [917 on yarn C2.2]. 
knit - b42 2 ;knit loops: [918 on yarn C2.2]. 
knit - f40 2 ;knit loops: [919 on yarn C2.2]. 
knit - f36 2 ;knit loops: [920 on yarn C2.2]. 
knit - b34 2 ;knit loops: [921 on yarn C2.2]. 
knit - f32 2 ;knit loops: [922 on yarn C2.2]. 
knit - f28 2 ;knit loops: [923 on yarn C2.2]. 
knit - b26 2 ;knit loops: [924 on yarn C2.2]. 
knit - f24 2 ;knit loops: [925 on yarn C2.2]. 
knit - f20 2 ;knit loops: [926 on yarn C2.2]. 
knit - b18 2 ;knit loops: [927 on yarn C2.2]. 
knit - b10 2 ;knit loops: [928 on yarn C2.2]. 
knit - b2 2 ;knit loops: [929 on yarn C2.2]. 
knit - b118 3 ;knit loops: [930 on yarn C3.3]. 
knit - b110 3 ;knit loops: [931 on yarn C3.3]. 
knit - b102 3 ;knit loops: [932 on yarn C3.3]. 
knit - b94 3 ;knit loops: [933 on yarn C3.3]. 
knit - b86 3 ;knit loops: [934 on yarn C3.3]. 
knit - b78 3 ;knit loops: [935 on yarn C3.3]. 
knit - b70 3 ;knit loops: [936 on yarn C3.3]. 
knit - b62 3 ;knit loops: [937 on yarn C3.3]. 
knit - b54 3 ;knit loops: [938 on yarn C3.3]. 
knit - b46 3 ;knit loops: [939 on yarn C3.3]. 
knit - b38 3 ;knit loops: [940 on yarn C3.3]. 
knit - b30 3 ;knit loops: [941 on yarn C3.3]. 
knit - b22 3 ;knit loops: [942 on yarn C3.3]. 
knit - b14 3 ;knit loops: [943 on yarn C3.3]. 
knit - b6 3 ;knit loops: [944 on yarn C3.3]. 
;KP Printout: 5: stripe 1: [b23, b27, b31, b35, b39, b43]
;Resetting to sheet s3:g4 of 4
; Peel sheet 0 relative to 3
; Peel sheet 1 relative to 3
; Peel sheet 2 relative to 3
xfer b2 f2 ;
xfer b6 f6 ;
xfer b10 f10 ;
xfer b14 f14 ;
xfer b18 f18 ;
xfer b22 f22 ;
xfer b26 f26 ;
xfer b30 f30 ;
xfer b34 f34 ;
xfer b38 f38 ;
xfer b42 f42 ;
xfer b46 f46 ;
xfer b50 f50 ;
xfer b54 f54 ;
xfer b58 f58 ;
xfer b62 f62 ;
xfer b66 f66 ;
xfer b70 f70 ;
xfer b74 f74 ;
xfer b78 f78 ;
xfer b82 f82 ;
xfer b86 f86 ;
xfer b90 f90 ;
xfer b94 f94 ;
xfer b98 f98 ;
xfer b102 f102 ;
xfer b106 f106 ;
xfer b110 f110 ;
xfer b114 f114 ;
xfer b118 f118 ;
; Peel sheet 3 relative to 3
xfer b1 f1 ;Return loops {834 on yarn C2.2} on b1 to f1
xfer b5 f5 ;Return loops {849 on yarn C3.3} on b5 to f5
xfer b9 f9 ;Return loops {835 on yarn C2.2} on b9 to f9
xfer b13 f13 ;Return loops {850 on yarn C3.3} on b13 to f13
xfer b17 f17 ;Return loops {836 on yarn C2.2} on b17 to f17
xfer b21 f21 ;Return loops {852 on yarn C3.3} on b21 to f21
xfer b25 f25 ;Return loops {837 on yarn C2.2} on b25 to f25
xfer b29 f29 ;Return loops {855 on yarn C3.3} on b29 to f29
xfer b33 f33 ;Return loops {838 on yarn C2.2} on b33 to f33
xfer b37 f37 ;Return loops {858 on yarn C3.3} on b37 to f37
xfer b41 f41 ;Return loops {839 on yarn C2.2} on b41 to f41
xfer b45 f45 ;Return loops {860 on yarn C3.3} on b45 to f45
xfer b49 f49 ;Return loops {840 on yarn C2.2} on b49 to f49
xfer b53 f53 ;Return loops {861 on yarn C3.3} on b53 to f53
xfer b57 f57 ;Return loops {841 on yarn C2.2} on b57 to f57
xfer b61 f61 ;Return loops {862 on yarn C3.3} on b61 to f61
xfer b65 f65 ;Return loops {842 on yarn C2.2} on b65 to f65
xfer b69 f69 ;Return loops {863 on yarn C3.3} on b69 to f69
xfer b73 f73 ;Return loops {843 on yarn C2.2} on b73 to f73
xfer b77 f77 ;Return loops {864 on yarn C3.3} on b77 to f77
xfer b81 f81 ;Return loops {844 on yarn C2.2} on b81 to f81
xfer b85 f85 ;Return loops {865 on yarn C3.3} on b85 to f85
xfer b89 f89 ;Return loops {845 on yarn C2.2} on b89 to f89
xfer b93 f93 ;Return loops {866 on yarn C3.3} on b93 to f93
xfer b97 f97 ;Return loops {846 on yarn C2.2} on b97 to f97
xfer b101 f101 ;Return loops {867 on yarn C3.3} on b101 to f101
xfer b105 f105 ;Return loops {847 on yarn C2.2} on b105 to f105
xfer b109 f109 ;Return loops {868 on yarn C3.3} on b109 to f109
xfer b113 f113 ;Return loops {848 on yarn C2.2} on b113 to f113
xfer b117 f117 ;Return loops {869 on yarn C3.3} on b117 to f117
knit + f1 1 ;knit loops: [945 on yarn C1.1]. 
knit + b3 1 ;knit loops: [946 on yarn C1.1]. 
knit + b7 1 ;knit loops: [947 on yarn C1.1]. 
knit + f9 1 ;knit loops: [948 on yarn C1.1]. 
knit + b11 1 ;knit loops: [949 on yarn C1.1]. 
knit + b15 1 ;knit loops: [950 on yarn C1.1]. 
knit + f17 1 ;knit loops: [951 on yarn C1.1]. 
knit + b19 1 ;knit loops: [952 on yarn C1.1]. 
knit + f25 1 ;knit loops: [953 on yarn C1.1]. 
knit + f33 1 ;knit loops: [954 on yarn C1.1]. 
knit + f41 1 ;knit loops: [955 on yarn C1.1]. 
knit + b47 1 ;knit loops: [956 on yarn C1.1]. 
knit + f49 1 ;knit loops: [957 on yarn C1.1]. 
knit + b51 1 ;knit loops: [958 on yarn C1.1]. 
knit + b55 1 ;knit loops: [959 on yarn C1.1]. 
knit + f57 1 ;knit loops: [960 on yarn C1.1]. 
knit + b59 1 ;knit loops: [961 on yarn C1.1]. 
knit + b63 1 ;knit loops: [962 on yarn C1.1]. 
knit + f65 1 ;knit loops: [963 on yarn C1.1]. 
knit + b67 1 ;knit loops: [964 on yarn C1.1]. 
knit + b71 1 ;knit loops: [965 on yarn C1.1]. 
knit + f73 1 ;knit loops: [966 on yarn C1.1]. 
knit + b75 1 ;knit loops: [967 on yarn C1.1]. 
knit + b79 1 ;knit loops: [968 on yarn C1.1]. 
knit + f81 1 ;knit loops: [969 on yarn C1.1]. 
knit + b83 1 ;knit loops: [970 on yarn C1.1]. 
knit + b87 1 ;knit loops: [971 on yarn C1.1]. 
knit + f89 1 ;knit loops: [972 on yarn C1.1]. 
knit + b91 1 ;knit loops: [973 on yarn C1.1]. 
knit + b95 1 ;knit loops: [974 on yarn C1.1]. 
knit + f97 1 ;knit loops: [975 on yarn C1.1]. 
knit + b99 1 ;knit loops: [976 on yarn C1.1]. 
knit + b103 1 ;knit loops: [977 on yarn C1.1]. 
knit + f105 1 ;knit loops: [978 on yarn C1.1]. 
knit + b107 1 ;knit loops: [979 on yarn C1.1]. 
knit + b111 1 ;knit loops: [980 on yarn C1.1]. 
knit + f113 1 ;knit loops: [981 on yarn C1.1]. 
knit + b115 1 ;knit loops: [982 on yarn C1.1]. 
knit + b119 1 ;knit loops: [983 on yarn C1.1]. 
knit + f5 2 ;knit loops: [984 on yarn C2.2]. 
knit + f13 2 ;knit loops: [985 on yarn C2.2]. 
knit + f21 2 ;knit loops: [986 on yarn C2.2]. 
knit + f29 2 ;knit loops: [987 on yarn C2.2]. 
knit + f37 2 ;knit loops: [988 on yarn C2.2]. 
knit + f45 2 ;knit loops: [989 on yarn C2.2]. 
knit + f53 2 ;knit loops: [990 on yarn C2.2]. 
knit + f61 2 ;knit loops: [991 on yarn C2.2]. 
knit + f69 2 ;knit loops: [992 on yarn C2.2]. 
knit + f77 2 ;knit loops: [993 on yarn C2.2]. 
knit + f85 2 ;knit loops: [994 on yarn C2.2]. 
knit + f93 2 ;knit loops: [995 on yarn C2.2]. 
knit + f101 2 ;knit loops: [996 on yarn C2.2]. 
knit + f109 2 ;knit loops: [997 on yarn C2.2]. 
knit + f117 2 ;knit loops: [998 on yarn C2.2]. 
knit + f1 3 ;knit loops: [999 on yarn C3.3]. 
knit + f9 3 ;knit loops: [1000 on yarn C3.3]. 
knit + f17 3 ;knit loops: [1001 on yarn C3.3]. 
knit + b23 3 ;knit loops: [1002 on yarn C3.3]. 
knit + f25 3 ;knit loops: [1003 on yarn C3.3]. 
knit + b27 3 ;knit loops: [1004 on yarn C3.3]. 
knit + b31 3 ;knit loops: [1005 on yarn C3.3]. 
knit + f33 3 ;knit loops: [1006 on yarn C3.3]. 
knit + b35 3 ;knit loops: [1007 on yarn C3.3]. 
knit + b39 3 ;knit loops: [1008 on yarn C3.3]. 
knit + f41 3 ;knit loops: [1009 on yarn C3.3]. 
knit + b43 3 ;knit loops: [1010 on yarn C3.3]. 
knit + f49 3 ;knit loops: [1011 on yarn C3.3]. 
knit + f57 3 ;knit loops: [1012 on yarn C3.3]. 
knit + f65 3 ;knit loops: [1013 on yarn C3.3]. 
knit + f73 3 ;knit loops: [1014 on yarn C3.3]. 
knit + f81 3 ;knit loops: [1015 on yarn C3.3]. 
knit + f89 3 ;knit loops: [1016 on yarn C3.3]. 
knit + f97 3 ;knit loops: [1017 on yarn C3.3]. 
knit + f105 3 ;knit loops: [1018 on yarn C3.3]. 
knit + f113 3 ;knit loops: [1019 on yarn C3.3]. 
;KP Printout: 6: stripe 0: [f24, f28, f32, f36, f40, f44]
;Resetting to sheet s0:g4 of 4
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f5 b5 ;
xfer f9 b9 ;
xfer f13 b13 ;
xfer f17 b17 ;
xfer f21 b21 ;
xfer f25 b25 ;
xfer f29 b29 ;
xfer f33 b33 ;
xfer f37 b37 ;
xfer f41 b41 ;
xfer f45 b45 ;
xfer f49 b49 ;
xfer f53 b53 ;
xfer f57 b57 ;
xfer f61 b61 ;
xfer f65 b65 ;
xfer f69 b69 ;
xfer f73 b73 ;
xfer f77 b77 ;
xfer f81 b81 ;
xfer f85 b85 ;
xfer f89 b89 ;
xfer f93 b93 ;
xfer f97 b97 ;
xfer f101 b101 ;
xfer f105 b105 ;
xfer f109 b109 ;
xfer f113 b113 ;
xfer f117 b117 ;
; Peel sheet 2 relative to 0
; Peel sheet 3 relative to 0
xfer f2 b2 ;return loops {929 on yarn C2.2} on f2 to b2
xfer f6 b6 ;return loops {944 on yarn C3.3} on f6 to b6
xfer f10 b10 ;return loops {928 on yarn C2.2} on f10 to b10
xfer f14 b14 ;return loops {943 on yarn C3.3} on f14 to b14
xfer f18 b18 ;return loops {927 on yarn C2.2} on f18 to b18
xfer f22 b22 ;return loops {942 on yarn C3.3} on f22 to b22
xfer f26 b26 ;return loops {924 on yarn C2.2} on f26 to b26
xfer f30 b30 ;return loops {941 on yarn C3.3} on f30 to b30
xfer f34 b34 ;return loops {921 on yarn C2.2} on f34 to b34
xfer f38 b38 ;return loops {940 on yarn C3.3} on f38 to b38
xfer f42 b42 ;return loops {918 on yarn C2.2} on f42 to b42
xfer f46 b46 ;return loops {939 on yarn C3.3} on f46 to b46
xfer f50 b50 ;return loops {917 on yarn C2.2} on f50 to b50
xfer f54 b54 ;return loops {938 on yarn C3.3} on f54 to b54
xfer f58 b58 ;return loops {916 on yarn C2.2} on f58 to b58
xfer f62 b62 ;return loops {937 on yarn C3.3} on f62 to b62
xfer f66 b66 ;return loops {915 on yarn C2.2} on f66 to b66
xfer f70 b70 ;return loops {936 on yarn C3.3} on f70 to b70
xfer f74 b74 ;return loops {914 on yarn C2.2} on f74 to b74
xfer f78 b78 ;return loops {935 on yarn C3.3} on f78 to b78
xfer f82 b82 ;return loops {913 on yarn C2.2} on f82 to b82
xfer f86 b86 ;return loops {934 on yarn C3.3} on f86 to b86
xfer f90 b90 ;return loops {912 on yarn C2.2} on f90 to b90
xfer f94 b94 ;return loops {933 on yarn C3.3} on f94 to b94
xfer f98 b98 ;return loops {911 on yarn C2.2} on f98 to b98
xfer f102 b102 ;return loops {932 on yarn C3.3} on f102 to b102
xfer f106 b106 ;return loops {910 on yarn C2.2} on f106 to b106
xfer f110 b110 ;return loops {931 on yarn C3.3} on f110 to b110
xfer f114 b114 ;return loops {909 on yarn C2.2} on f114 to b114
xfer f118 b118 ;return loops {930 on yarn C3.3} on f118 to b118
knit - f116 1 ;knit loops: [1020 on yarn C1.1]. 
knit - b114 1 ;knit loops: [1021 on yarn C1.1]. 
knit - f112 1 ;knit loops: [1022 on yarn C1.1]. 
knit - f108 1 ;knit loops: [1023 on yarn C1.1]. 
knit - b106 1 ;knit loops: [1024 on yarn C1.1]. 
knit - f104 1 ;knit loops: [1025 on yarn C1.1]. 
knit - f100 1 ;knit loops: [1026 on yarn C1.1]. 
knit - b98 1 ;knit loops: [1027 on yarn C1.1]. 
knit - f96 1 ;knit loops: [1028 on yarn C1.1]. 
knit - f92 1 ;knit loops: [1029 on yarn C1.1]. 
knit - b90 1 ;knit loops: [1030 on yarn C1.1]. 
knit - f88 1 ;knit loops: [1031 on yarn C1.1]. 
knit - f84 1 ;knit loops: [1032 on yarn C1.1]. 
knit - b82 1 ;knit loops: [1033 on yarn C1.1]. 
knit - f80 1 ;knit loops: [1034 on yarn C1.1]. 
knit - f76 1 ;knit loops: [1035 on yarn C1.1]. 
knit - b74 1 ;knit loops: [1036 on yarn C1.1]. 
knit - f72 1 ;knit loops: [1037 on yarn C1.1]. 
knit - f68 1 ;knit loops: [1038 on yarn C1.1]. 
knit - b66 1 ;knit loops: [1039 on yarn C1.1]. 
knit - f64 1 ;knit loops: [1040 on yarn C1.1]. 
knit - f60 1 ;knit loops: [1041 on yarn C1.1]. 
knit - b58 1 ;knit loops: [1042 on yarn C1.1]. 
knit - f56 1 ;knit loops: [1043 on yarn C1.1]. 
knit - f52 1 ;knit loops: [1044 on yarn C1.1]. 
knit - b50 1 ;knit loops: [1045 on yarn C1.1]. 
knit - f48 1 ;knit loops: [1046 on yarn C1.1]. 
knit - b42 1 ;knit loops: [1047 on yarn C1.1]. 
knit - b34 1 ;knit loops: [1048 on yarn C1.1]. 
knit - b26 1 ;knit loops: [1049 on yarn C1.1]. 
knit - f20 1 ;knit loops: [1050 on yarn C1.1]. 
knit - b18 1 ;knit loops: [1051 on yarn C1.1]. 
knit - f16 1 ;knit loops: [1052 on yarn C1.1]. 
knit - f12 1 ;knit loops: [1053 on yarn C1.1]. 
knit - b10 1 ;knit loops: [1054 on yarn C1.1]. 
knit - f8 1 ;knit loops: [1055 on yarn C1.1]. 
knit - f4 1 ;knit loops: [1056 on yarn C1.1]. 
knit - b2 1 ;knit loops: [1057 on yarn C1.1]. 
knit - f0 1 ;knit loops: [1058 on yarn C1.1]. 
knit - b118 2 ;knit loops: [1059 on yarn C2.2]. 
knit - b110 2 ;knit loops: [1060 on yarn C2.2]. 
knit - b102 2 ;knit loops: [1061 on yarn C2.2]. 
knit - b94 2 ;knit loops: [1062 on yarn C2.2]. 
knit - b86 2 ;knit loops: [1063 on yarn C2.2]. 
knit - b78 2 ;knit loops: [1064 on yarn C2.2]. 
knit - b70 2 ;knit loops: [1065 on yarn C2.2]. 
knit - b62 2 ;knit loops: [1066 on yarn C2.2]. 
knit - b54 2 ;knit loops: [1067 on yarn C2.2]. 
knit - b46 2 ;knit loops: [1068 on yarn C2.2]. 
knit - f44 2 ;knit loops: [1069 on yarn C2.2]. 
knit - f40 2 ;knit loops: [1070 on yarn C2.2]. 
knit - b38 2 ;knit loops: [1071 on yarn C2.2]. 
knit - f36 2 ;knit loops: [1072 on yarn C2.2]. 
knit - f32 2 ;knit loops: [1073 on yarn C2.2]. 
knit - b30 2 ;knit loops: [1074 on yarn C2.2]. 
knit - f28 2 ;knit loops: [1075 on yarn C2.2]. 
knit - f24 2 ;knit loops: [1076 on yarn C2.2]. 
knit - b22 2 ;knit loops: [1077 on yarn C2.2]. 
knit - b14 2 ;knit loops: [1078 on yarn C2.2]. 
knit - b6 2 ;knit loops: [1079 on yarn C2.2]. 
knit - b114 3 ;knit loops: [1080 on yarn C3.3]. 
knit - b106 3 ;knit loops: [1081 on yarn C3.3]. 
knit - b98 3 ;knit loops: [1082 on yarn C3.3]. 
knit - b90 3 ;knit loops: [1083 on yarn C3.3]. 
knit - b82 3 ;knit loops: [1084 on yarn C3.3]. 
knit - b74 3 ;knit loops: [1085 on yarn C3.3]. 
knit - b66 3 ;knit loops: [1086 on yarn C3.3]. 
knit - b58 3 ;knit loops: [1087 on yarn C3.3]. 
knit - b50 3 ;knit loops: [1088 on yarn C3.3]. 
knit - b42 3 ;knit loops: [1089 on yarn C3.3]. 
knit - b34 3 ;knit loops: [1090 on yarn C3.3]. 
knit - b26 3 ;knit loops: [1091 on yarn C3.3]. 
knit - b18 3 ;knit loops: [1092 on yarn C3.3]. 
knit - b10 3 ;knit loops: [1093 on yarn C3.3]. 
knit - b2 3 ;knit loops: [1094 on yarn C3.3]. 
;KP Printout: 6: stripe 1: [b27, b31, b35, b39, b43, b47]
;Resetting to sheet s3:g4 of 4
; Peel sheet 0 relative to 3
; Peel sheet 1 relative to 3
; Peel sheet 2 relative to 3
xfer b2 f2 ;
xfer b6 f6 ;
xfer b10 f10 ;
xfer b14 f14 ;
xfer b18 f18 ;
xfer b22 f22 ;
xfer b26 f26 ;
xfer b30 f30 ;
xfer b34 f34 ;
xfer b38 f38 ;
xfer b42 f42 ;
xfer b46 f46 ;
xfer b50 f50 ;
xfer b54 f54 ;
xfer b58 f58 ;
xfer b62 f62 ;
xfer b66 f66 ;
xfer b70 f70 ;
xfer b74 f74 ;
xfer b78 f78 ;
xfer b82 f82 ;
xfer b86 f86 ;
xfer b90 f90 ;
xfer b94 f94 ;
xfer b98 f98 ;
xfer b102 f102 ;
xfer b106 f106 ;
xfer b110 f110 ;
xfer b114 f114 ;
xfer b118 f118 ;
; Peel sheet 3 relative to 3
xfer b1 f1 ;Return loops {999 on yarn C3.3} on b1 to f1
xfer b5 f5 ;Return loops {984 on yarn C2.2} on b5 to f5
xfer b9 f9 ;Return loops {1000 on yarn C3.3} on b9 to f9
xfer b13 f13 ;Return loops {985 on yarn C2.2} on b13 to f13
xfer b17 f17 ;Return loops {1001 on yarn C3.3} on b17 to f17
xfer b21 f21 ;Return loops {986 on yarn C2.2} on b21 to f21
xfer b25 f25 ;Return loops {1003 on yarn C3.3} on b25 to f25
xfer b29 f29 ;Return loops {987 on yarn C2.2} on b29 to f29
xfer b33 f33 ;Return loops {1006 on yarn C3.3} on b33 to f33
xfer b37 f37 ;Return loops {988 on yarn C2.2} on b37 to f37
xfer b41 f41 ;Return loops {1009 on yarn C3.3} on b41 to f41
xfer b45 f45 ;Return loops {989 on yarn C2.2} on b45 to f45
xfer b49 f49 ;Return loops {1011 on yarn C3.3} on b49 to f49
xfer b53 f53 ;Return loops {990 on yarn C2.2} on b53 to f53
xfer b57 f57 ;Return loops {1012 on yarn C3.3} on b57 to f57
xfer b61 f61 ;Return loops {991 on yarn C2.2} on b61 to f61
xfer b65 f65 ;Return loops {1013 on yarn C3.3} on b65 to f65
xfer b69 f69 ;Return loops {992 on yarn C2.2} on b69 to f69
xfer b73 f73 ;Return loops {1014 on yarn C3.3} on b73 to f73
xfer b77 f77 ;Return loops {993 on yarn C2.2} on b77 to f77
xfer b81 f81 ;Return loops {1015 on yarn C3.3} on b81 to f81
xfer b85 f85 ;Return loops {994 on yarn C2.2} on b85 to f85
xfer b89 f89 ;Return loops {1016 on yarn C3.3} on b89 to f89
xfer b93 f93 ;Return loops {995 on yarn C2.2} on b93 to f93
xfer b97 f97 ;Return loops {1017 on yarn C3.3} on b97 to f97
xfer b101 f101 ;Return loops {996 on yarn C2.2} on b101 to f101
xfer b105 f105 ;Return loops {1018 on yarn C3.3} on b105 to f105
xfer b109 f109 ;Return loops {997 on yarn C2.2} on b109 to f109
xfer b113 f113 ;Return loops {1019 on yarn C3.3} on b113 to f113
xfer b117 f117 ;Return loops {998 on yarn C2.2} on b117 to f117
knit + b3 1 ;knit loops: [1095 on yarn C1.1]. 
knit + f5 1 ;knit loops: [1096 on yarn C1.1]. 
knit + b7 1 ;knit loops: [1097 on yarn C1.1]. 
knit + b11 1 ;knit loops: [1098 on yarn C1.1]. 
knit + f13 1 ;knit loops: [1099 on yarn C1.1]. 
knit + b15 1 ;knit loops: [1100 on yarn C1.1]. 
knit + b19 1 ;knit loops: [1101 on yarn C1.1]. 
knit + f21 1 ;knit loops: [1102 on yarn C1.1]. 
knit + b23 1 ;knit loops: [1103 on yarn C1.1]. 
knit + f29 1 ;knit loops: [1104 on yarn C1.1]. 
knit + f37 1 ;knit loops: [1105 on yarn C1.1]. 
knit + f45 1 ;knit loops: [1106 on yarn C1.1]. 
knit + b51 1 ;knit loops: [1107 on yarn C1.1]. 
knit + f53 1 ;knit loops: [1108 on yarn C1.1]. 
knit + b55 1 ;knit loops: [1109 on yarn C1.1]. 
knit + b59 1 ;knit loops: [1110 on yarn C1.1]. 
knit + f61 1 ;knit loops: [1111 on yarn C1.1]. 
knit + b63 1 ;knit loops: [1112 on yarn C1.1]. 
knit + b67 1 ;knit loops: [1113 on yarn C1.1]. 
knit + f69 1 ;knit loops: [1114 on yarn C1.1]. 
knit + b71 1 ;knit loops: [1115 on yarn C1.1]. 
knit + b75 1 ;knit loops: [1116 on yarn C1.1]. 
knit + f77 1 ;knit loops: [1117 on yarn C1.1]. 
knit + b79 1 ;knit loops: [1118 on yarn C1.1]. 
knit + b83 1 ;knit loops: [1119 on yarn C1.1]. 
knit + f85 1 ;knit loops: [1120 on yarn C1.1]. 
knit + b87 1 ;knit loops: [1121 on yarn C1.1]. 
knit + b91 1 ;knit loops: [1122 on yarn C1.1]. 
knit + f93 1 ;knit loops: [1123 on yarn C1.1]. 
knit + b95 1 ;knit loops: [1124 on yarn C1.1]. 
knit + b99 1 ;knit loops: [1125 on yarn C1.1]. 
knit + f101 1 ;knit loops: [1126 on yarn C1.1]. 
knit + b103 1 ;knit loops: [1127 on yarn C1.1]. 
knit + b107 1 ;knit loops: [1128 on yarn C1.1]. 
knit + f109 1 ;knit loops: [1129 on yarn C1.1]. 
knit + b111 1 ;knit loops: [1130 on yarn C1.1]. 
knit + b115 1 ;knit loops: [1131 on yarn C1.1]. 
knit + f117 1 ;knit loops: [1132 on yarn C1.1]. 
knit + b119 1 ;knit loops: [1133 on yarn C1.1]. 
knit + f1 2 ;knit loops: [1134 on yarn C2.2]. 
knit + f9 2 ;knit loops: [1135 on yarn C2.2]. 
knit + f17 2 ;knit loops: [1136 on yarn C2.2]. 
knit + f25 2 ;knit loops: [1137 on yarn C2.2]. 
knit + f33 2 ;knit loops: [1138 on yarn C2.2]. 
knit + f41 2 ;knit loops: [1139 on yarn C2.2]. 
knit + f49 2 ;knit loops: [1140 on yarn C2.2]. 
knit + f57 2 ;knit loops: [1141 on yarn C2.2]. 
knit + f65 2 ;knit loops: [1142 on yarn C2.2]. 
knit + f73 2 ;knit loops: [1143 on yarn C2.2]. 
knit + f81 2 ;knit loops: [1144 on yarn C2.2]. 
knit + f89 2 ;knit loops: [1145 on yarn C2.2]. 
knit + f97 2 ;knit loops: [1146 on yarn C2.2]. 
knit + f105 2 ;knit loops: [1147 on yarn C2.2]. 
knit + f113 2 ;knit loops: [1148 on yarn C2.2]. 
knit + f5 3 ;knit loops: [1149 on yarn C3.3]. 
knit + f13 3 ;knit loops: [1150 on yarn C3.3]. 
knit + f21 3 ;knit loops: [1151 on yarn C3.3]. 
knit + b27 3 ;knit loops: [1152 on yarn C3.3]. 
knit + f29 3 ;knit loops: [1153 on yarn C3.3]. 
knit + b31 3 ;knit loops: [1154 on yarn C3.3]. 
knit + b35 3 ;knit loops: [1155 on yarn C3.3]. 
knit + f37 3 ;knit loops: [1156 on yarn C3.3]. 
knit + b39 3 ;knit loops: [1157 on yarn C3.3]. 
knit + b43 3 ;knit loops: [1158 on yarn C3.3]. 
knit + f45 3 ;knit loops: [1159 on yarn C3.3]. 
knit + b47 3 ;knit loops: [1160 on yarn C3.3]. 
knit + f53 3 ;knit loops: [1161 on yarn C3.3]. 
knit + f61 3 ;knit loops: [1162 on yarn C3.3]. 
knit + f69 3 ;knit loops: [1163 on yarn C3.3]. 
knit + f77 3 ;knit loops: [1164 on yarn C3.3]. 
knit + f85 3 ;knit loops: [1165 on yarn C3.3]. 
knit + f93 3 ;knit loops: [1166 on yarn C3.3]. 
knit + f101 3 ;knit loops: [1167 on yarn C3.3]. 
knit + f109 3 ;knit loops: [1168 on yarn C3.3]. 
knit + f117 3 ;knit loops: [1169 on yarn C3.3]. 
;KP Printout: 7: stripe 0: [f28, f32, f36, f40, f44, f48]
;Resetting to sheet s0:g4 of 4
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f5 b5 ;
xfer f9 b9 ;
xfer f13 b13 ;
xfer f17 b17 ;
xfer f21 b21 ;
xfer f25 b25 ;
xfer f29 b29 ;
xfer f33 b33 ;
xfer f37 b37 ;
xfer f41 b41 ;
xfer f45 b45 ;
xfer f49 b49 ;
xfer f53 b53 ;
xfer f57 b57 ;
xfer f61 b61 ;
xfer f65 b65 ;
xfer f69 b69 ;
xfer f73 b73 ;
xfer f77 b77 ;
xfer f81 b81 ;
xfer f85 b85 ;
xfer f89 b89 ;
xfer f93 b93 ;
xfer f97 b97 ;
xfer f101 b101 ;
xfer f105 b105 ;
xfer f109 b109 ;
xfer f113 b113 ;
xfer f117 b117 ;
; Peel sheet 2 relative to 0
; Peel sheet 3 relative to 0
xfer f2 b2 ;return loops {1094 on yarn C3.3} on f2 to b2
xfer f6 b6 ;return loops {1079 on yarn C2.2} on f6 to b6
xfer f10 b10 ;return loops {1093 on yarn C3.3} on f10 to b10
xfer f14 b14 ;return loops {1078 on yarn C2.2} on f14 to b14
xfer f18 b18 ;return loops {1092 on yarn C3.3} on f18 to b18
xfer f22 b22 ;return loops {1077 on yarn C2.2} on f22 to b22
xfer f26 b26 ;return loops {1091 on yarn C3.3} on f26 to b26
xfer f30 b30 ;return loops {1074 on yarn C2.2} on f30 to b30
xfer f34 b34 ;return loops {1090 on yarn C3.3} on f34 to b34
xfer f38 b38 ;return loops {1071 on yarn C2.2} on f38 to b38
xfer f42 b42 ;return loops {1089 on yarn C3.3} on f42 to b42
xfer f46 b46 ;return loops {1068 on yarn C2.2} on f46 to b46
xfer f50 b50 ;return loops {1088 on yarn C3.3} on f50 to b50
xfer f54 b54 ;return loops {1067 on yarn C2.2} on f54 to b54
xfer f58 b58 ;return loops {1087 on yarn C3.3} on f58 to b58
xfer f62 b62 ;return loops {1066 on yarn C2.2} on f62 to b62
xfer f66 b66 ;return loops {1086 on yarn C3.3} on f66 to b66
xfer f70 b70 ;return loops {1065 on yarn C2.2} on f70 to b70
xfer f74 b74 ;return loops {1085 on yarn C3.3} on f74 to b74
xfer f78 b78 ;return loops {1064 on yarn C2.2} on f78 to b78
xfer f82 b82 ;return loops {1084 on yarn C3.3} on f82 to b82
xfer f86 b86 ;return loops {1063 on yarn C2.2} on f86 to b86
xfer f90 b90 ;return loops {1083 on yarn C3.3} on f90 to b90
xfer f94 b94 ;return loops {1062 on yarn C2.2} on f94 to b94
xfer f98 b98 ;return loops {1082 on yarn C3.3} on f98 to b98
xfer f102 b102 ;return loops {1061 on yarn C2.2} on f102 to b102
xfer f106 b106 ;return loops {1081 on yarn C3.3} on f106 to b106
xfer f110 b110 ;return loops {1060 on yarn C2.2} on f110 to b110
xfer f114 b114 ;return loops {1080 on yarn C3.3} on f114 to b114
xfer f118 b118 ;return loops {1059 on yarn C2.2} on f118 to b118
knit - b118 1 ;knit loops: [1170 on yarn C1.1]. 
knit - f116 1 ;knit loops: [1171 on yarn C1.1]. 
knit - f112 1 ;knit loops: [1172 on yarn C1.1]. 
knit - b110 1 ;knit loops: [1173 on yarn C1.1]. 
knit - f108 1 ;knit loops: [1174 on yarn C1.1]. 
knit - f104 1 ;knit loops: [1175 on yarn C1.1]. 
knit - b102 1 ;knit loops: [1176 on yarn C1.1]. 
knit - f100 1 ;knit loops: [1177 on yarn C1.1]. 
knit - f96 1 ;knit loops: [1178 on yarn C1.1]. 
knit - b94 1 ;knit loops: [1179 on yarn C1.1]. 
knit - f92 1 ;knit loops: [1180 on yarn C1.1]. 
knit - f88 1 ;knit loops: [1181 on yarn C1.1]. 
knit - b86 1 ;knit loops: [1182 on yarn C1.1]. 
knit - f84 1 ;knit loops: [1183 on yarn C1.1]. 
knit - f80 1 ;knit loops: [1184 on yarn C1.1]. 
knit - b78 1 ;knit loops: [1185 on yarn C1.1]. 
knit - f76 1 ;knit loops: [1186 on yarn C1.1]. 
knit - f72 1 ;knit loops: [1187 on yarn C1.1]. 
knit - b70 1 ;knit loops: [1188 on yarn C1.1]. 
knit - f68 1 ;knit loops: [1189 on yarn C1.1]. 
knit - f64 1 ;knit loops: [1190 on yarn C1.1]. 
knit - b62 1 ;knit loops: [1191 on yarn C1.1]. 
knit - f60 1 ;knit loops: [1192 on yarn C1.1]. 
knit - f56 1 ;knit loops: [1193 on yarn C1.1]. 
knit - b54 1 ;knit loops: [1194 on yarn C1.1]. 
knit - f52 1 ;knit loops: [1195 on yarn C1.1]. 
knit - b46 1 ;knit loops: [1196 on yarn C1.1]. 
knit - b38 1 ;knit loops: [1197 on yarn C1.1]. 
knit - b30 1 ;knit loops: [1198 on yarn C1.1]. 
knit - f24 1 ;knit loops: [1199 on yarn C1.1]. 
knit - b22 1 ;knit loops: [1200 on yarn C1.1]. 
knit - f20 1 ;knit loops: [1201 on yarn C1.1]. 
knit - f16 1 ;knit loops: [1202 on yarn C1.1]. 
knit - b14 1 ;knit loops: [1203 on yarn C1.1]. 
knit - f12 1 ;knit loops: [1204 on yarn C1.1]. 
knit - f8 1 ;knit loops: [1205 on yarn C1.1]. 
knit - b6 1 ;knit loops: [1206 on yarn C1.1]. 
knit - f4 1 ;knit loops: [1207 on yarn C1.1]. 
knit - f0 1 ;knit loops: [1208 on yarn C1.1]. 
knit - b114 2 ;knit loops: [1209 on yarn C2.2]. 
knit - b106 2 ;knit loops: [1210 on yarn C2.2]. 
knit - b98 2 ;knit loops: [1211 on yarn C2.2]. 
knit - b90 2 ;knit loops: [1212 on yarn C2.2]. 
knit - b82 2 ;knit loops: [1213 on yarn C2.2]. 
knit - b74 2 ;knit loops: [1214 on yarn C2.2]. 
knit - b66 2 ;knit loops: [1215 on yarn C2.2]. 
knit - b58 2 ;knit loops: [1216 on yarn C2.2]. 
knit - b50 2 ;knit loops: [1217 on yarn C2.2]. 
knit - f48 2 ;knit loops: [1218 on yarn C2.2]. 
knit - f44 2 ;knit loops: [1219 on yarn C2.2]. 
knit - b42 2 ;knit loops: [1220 on yarn C2.2]. 
knit - f40 2 ;knit loops: [1221 on yarn C2.2]. 
knit - f36 2 ;knit loops: [1222 on yarn C2.2]. 
knit - b34 2 ;knit loops: [1223 on yarn C2.2]. 
knit - f32 2 ;knit loops: [1224 on yarn C2.2]. 
knit - f28 2 ;knit loops: [1225 on yarn C2.2]. 
knit - b26 2 ;knit loops: [1226 on yarn C2.2]. 
knit - b18 2 ;knit loops: [1227 on yarn C2.2]. 
knit - b10 2 ;knit loops: [1228 on yarn C2.2]. 
knit - b2 2 ;knit loops: [1229 on yarn C2.2]. 
knit - b118 3 ;knit loops: [1230 on yarn C3.3]. 
knit - b110 3 ;knit loops: [1231 on yarn C3.3]. 
knit - b102 3 ;knit loops: [1232 on yarn C3.3]. 
knit - b94 3 ;knit loops: [1233 on yarn C3.3]. 
knit - b86 3 ;knit loops: [1234 on yarn C3.3]. 
knit - b78 3 ;knit loops: [1235 on yarn C3.3]. 
knit - b70 3 ;knit loops: [1236 on yarn C3.3]. 
knit - b62 3 ;knit loops: [1237 on yarn C3.3]. 
knit - b54 3 ;knit loops: [1238 on yarn C3.3]. 
knit - b46 3 ;knit loops: [1239 on yarn C3.3]. 
knit - b38 3 ;knit loops: [1240 on yarn C3.3]. 
knit - b30 3 ;knit loops: [1241 on yarn C3.3]. 
knit - b22 3 ;knit loops: [1242 on yarn C3.3]. 
knit - b14 3 ;knit loops: [1243 on yarn C3.3]. 
knit - b6 3 ;knit loops: [1244 on yarn C3.3]. 
;KP Printout: 7: stripe 1: [b31, b35, b39, b43, b47, b51]
;Resetting to sheet s3:g4 of 4
; Peel sheet 0 relative to 3
; Peel sheet 1 relative to 3
; Peel sheet 2 relative to 3
xfer b2 f2 ;
xfer b6 f6 ;
xfer b10 f10 ;
xfer b14 f14 ;
xfer b18 f18 ;
xfer b22 f22 ;
xfer b26 f26 ;
xfer b30 f30 ;
xfer b34 f34 ;
xfer b38 f38 ;
xfer b42 f42 ;
xfer b46 f46 ;
xfer b50 f50 ;
xfer b54 f54 ;
xfer b58 f58 ;
xfer b62 f62 ;
xfer b66 f66 ;
xfer b70 f70 ;
xfer b74 f74 ;
xfer b78 f78 ;
xfer b82 f82 ;
xfer b86 f86 ;
xfer b90 f90 ;
xfer b94 f94 ;
xfer b98 f98 ;
xfer b102 f102 ;
xfer b106 f106 ;
xfer b110 f110 ;
xfer b114 f114 ;
xfer b118 f118 ;
; Peel sheet 3 relative to 3
xfer b1 f1 ;Return loops {1134 on yarn C2.2} on b1 to f1
xfer b5 f5 ;Return loops {1149 on yarn C3.3} on b5 to f5
xfer b9 f9 ;Return loops {1135 on yarn C2.2} on b9 to f9
xfer b13 f13 ;Return loops {1150 on yarn C3.3} on b13 to f13
xfer b17 f17 ;Return loops {1136 on yarn C2.2} on b17 to f17
xfer b21 f21 ;Return loops {1151 on yarn C3.3} on b21 to f21
xfer b25 f25 ;Return loops {1137 on yarn C2.2} on b25 to f25
xfer b29 f29 ;Return loops {1153 on yarn C3.3} on b29 to f29
xfer b33 f33 ;Return loops {1138 on yarn C2.2} on b33 to f33
xfer b37 f37 ;Return loops {1156 on yarn C3.3} on b37 to f37
xfer b41 f41 ;Return loops {1139 on yarn C2.2} on b41 to f41
xfer b45 f45 ;Return loops {1159 on yarn C3.3} on b45 to f45
xfer b49 f49 ;Return loops {1140 on yarn C2.2} on b49 to f49
xfer b53 f53 ;Return loops {1161 on yarn C3.3} on b53 to f53
xfer b57 f57 ;Return loops {1141 on yarn C2.2} on b57 to f57
xfer b61 f61 ;Return loops {1162 on yarn C3.3} on b61 to f61
xfer b65 f65 ;Return loops {1142 on yarn C2.2} on b65 to f65
xfer b69 f69 ;Return loops {1163 on yarn C3.3} on b69 to f69
xfer b73 f73 ;Return loops {1143 on yarn C2.2} on b73 to f73
xfer b77 f77 ;Return loops {1164 on yarn C3.3} on b77 to f77
xfer b81 f81 ;Return loops {1144 on yarn C2.2} on b81 to f81
xfer b85 f85 ;Return loops {1165 on yarn C3.3} on b85 to f85
xfer b89 f89 ;Return loops {1145 on yarn C2.2} on b89 to f89
xfer b93 f93 ;Return loops {1166 on yarn C3.3} on b93 to f93
xfer b97 f97 ;Return loops {1146 on yarn C2.2} on b97 to f97
xfer b101 f101 ;Return loops {1167 on yarn C3.3} on b101 to f101
xfer b105 f105 ;Return loops {1147 on yarn C2.2} on b105 to f105
xfer b109 f109 ;Return loops {1168 on yarn C3.3} on b109 to f109
xfer b113 f113 ;Return loops {1148 on yarn C2.2} on b113 to f113
xfer b117 f117 ;Return loops {1169 on yarn C3.3} on b117 to f117
knit + f1 1 ;knit loops: [1245 on yarn C1.1]. 
knit + b3 1 ;knit loops: [1246 on yarn C1.1]. 
knit + b7 1 ;knit loops: [1247 on yarn C1.1]. 
knit + f9 1 ;knit loops: [1248 on yarn C1.1]. 
knit + b11 1 ;knit loops: [1249 on yarn C1.1]. 
knit + b15 1 ;knit loops: [1250 on yarn C1.1]. 
knit + f17 1 ;knit loops: [1251 on yarn C1.1]. 
knit + b19 1 ;knit loops: [1252 on yarn C1.1]. 
knit + b23 1 ;knit loops: [1253 on yarn C1.1]. 
knit + f25 1 ;knit loops: [1254 on yarn C1.1]. 
knit + b27 1 ;knit loops: [1255 on yarn C1.1]. 
knit + f33 1 ;knit loops: [1256 on yarn C1.1]. 
knit + f41 1 ;knit loops: [1257 on yarn C1.1]. 
knit + f49 1 ;knit loops: [1258 on yarn C1.1]. 
knit + b55 1 ;knit loops: [1259 on yarn C1.1]. 
knit + f57 1 ;knit loops: [1260 on yarn C1.1]. 
knit + b59 1 ;knit loops: [1261 on yarn C1.1]. 
knit + b63 1 ;knit loops: [1262 on yarn C1.1]. 
knit + f65 1 ;knit loops: [1263 on yarn C1.1]. 
knit + b67 1 ;knit loops: [1264 on yarn C1.1]. 
knit + b71 1 ;knit loops: [1265 on yarn C1.1]. 
knit + f73 1 ;knit loops: [1266 on yarn C1.1]. 
knit + b75 1 ;knit loops: [1267 on yarn C1.1]. 
knit + b79 1 ;knit loops: [1268 on yarn C1.1]. 
knit + f81 1 ;knit loops: [1269 on yarn C1.1]. 
knit + b83 1 ;knit loops: [1270 on yarn C1.1]. 
knit + b87 1 ;knit loops: [1271 on yarn C1.1]. 
knit + f89 1 ;knit loops: [1272 on yarn C1.1]. 
knit + b91 1 ;knit loops: [1273 on yarn C1.1]. 
knit + b95 1 ;knit loops: [1274 on yarn C1.1]. 
knit + f97 1 ;knit loops: [1275 on yarn C1.1]. 
knit + b99 1 ;knit loops: [1276 on yarn C1.1]. 
knit + b103 1 ;knit loops: [1277 on yarn C1.1]. 
knit + f105 1 ;knit loops: [1278 on yarn C1.1]. 
knit + b107 1 ;knit loops: [1279 on yarn C1.1]. 
knit + b111 1 ;knit loops: [1280 on yarn C1.1]. 
knit + f113 1 ;knit loops: [1281 on yarn C1.1]. 
knit + b115 1 ;knit loops: [1282 on yarn C1.1]. 
knit + b119 1 ;knit loops: [1283 on yarn C1.1]. 
knit + f5 2 ;knit loops: [1284 on yarn C2.2]. 
knit + f13 2 ;knit loops: [1285 on yarn C2.2]. 
knit + f21 2 ;knit loops: [1286 on yarn C2.2]. 
knit + f29 2 ;knit loops: [1287 on yarn C2.2]. 
knit + f37 2 ;knit loops: [1288 on yarn C2.2]. 
knit + f45 2 ;knit loops: [1289 on yarn C2.2]. 
knit + f53 2 ;knit loops: [1290 on yarn C2.2]. 
knit + f61 2 ;knit loops: [1291 on yarn C2.2]. 
knit + f69 2 ;knit loops: [1292 on yarn C2.2]. 
knit + f77 2 ;knit loops: [1293 on yarn C2.2]. 
knit + f85 2 ;knit loops: [1294 on yarn C2.2]. 
knit + f93 2 ;knit loops: [1295 on yarn C2.2]. 
knit + f101 2 ;knit loops: [1296 on yarn C2.2]. 
knit + f109 2 ;knit loops: [1297 on yarn C2.2]. 
knit + f117 2 ;knit loops: [1298 on yarn C2.2]. 
knit + f1 3 ;knit loops: [1299 on yarn C3.3]. 
knit + f9 3 ;knit loops: [1300 on yarn C3.3]. 
knit + f17 3 ;knit loops: [1301 on yarn C3.3]. 
knit + f25 3 ;knit loops: [1302 on yarn C3.3]. 
knit + b31 3 ;knit loops: [1303 on yarn C3.3]. 
knit + f33 3 ;knit loops: [1304 on yarn C3.3]. 
knit + b35 3 ;knit loops: [1305 on yarn C3.3]. 
knit + b39 3 ;knit loops: [1306 on yarn C3.3]. 
knit + f41 3 ;knit loops: [1307 on yarn C3.3]. 
knit + b43 3 ;knit loops: [1308 on yarn C3.3]. 
knit + b47 3 ;knit loops: [1309 on yarn C3.3]. 
knit + f49 3 ;knit loops: [1310 on yarn C3.3]. 
knit + b51 3 ;knit loops: [1311 on yarn C3.3]. 
knit + f57 3 ;knit loops: [1312 on yarn C3.3]. 
knit + f65 3 ;knit loops: [1313 on yarn C3.3]. 
knit + f73 3 ;knit loops: [1314 on yarn C3.3]. 
knit + f81 3 ;knit loops: [1315 on yarn C3.3]. 
knit + f89 3 ;knit loops: [1316 on yarn C3.3]. 
knit + f97 3 ;knit loops: [1317 on yarn C3.3]. 
knit + f105 3 ;knit loops: [1318 on yarn C3.3]. 
knit + f113 3 ;knit loops: [1319 on yarn C3.3]. 
;KP Printout: 8: stripe 0: [f32, f36, f40, f44, f48, f52]
;Resetting to sheet s0:g4 of 4
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f5 b5 ;
xfer f9 b9 ;
xfer f13 b13 ;
xfer f17 b17 ;
xfer f21 b21 ;
xfer f25 b25 ;
xfer f29 b29 ;
xfer f33 b33 ;
xfer f37 b37 ;
xfer f41 b41 ;
xfer f45 b45 ;
xfer f49 b49 ;
xfer f53 b53 ;
xfer f57 b57 ;
xfer f61 b61 ;
xfer f65 b65 ;
xfer f69 b69 ;
xfer f73 b73 ;
xfer f77 b77 ;
xfer f81 b81 ;
xfer f85 b85 ;
xfer f89 b89 ;
xfer f93 b93 ;
xfer f97 b97 ;
xfer f101 b101 ;
xfer f105 b105 ;
xfer f109 b109 ;
xfer f113 b113 ;
xfer f117 b117 ;
; Peel sheet 2 relative to 0
; Peel sheet 3 relative to 0
xfer f2 b2 ;return loops {1229 on yarn C2.2} on f2 to b2
xfer f6 b6 ;return loops {1244 on yarn C3.3} on f6 to b6
xfer f10 b10 ;return loops {1228 on yarn C2.2} on f10 to b10
xfer f14 b14 ;return loops {1243 on yarn C3.3} on f14 to b14
xfer f18 b18 ;return loops {1227 on yarn C2.2} on f18 to b18
xfer f22 b22 ;return loops {1242 on yarn C3.3} on f22 to b22
xfer f26 b26 ;return loops {1226 on yarn C2.2} on f26 to b26
xfer f30 b30 ;return loops {1241 on yarn C3.3} on f30 to b30
xfer f34 b34 ;return loops {1223 on yarn C2.2} on f34 to b34
xfer f38 b38 ;return loops {1240 on yarn C3.3} on f38 to b38
xfer f42 b42 ;return loops {1220 on yarn C2.2} on f42 to b42
xfer f46 b46 ;return loops {1239 on yarn C3.3} on f46 to b46
xfer f50 b50 ;return loops {1217 on yarn C2.2} on f50 to b50
xfer f54 b54 ;return loops {1238 on yarn C3.3} on f54 to b54
xfer f58 b58 ;return loops {1216 on yarn C2.2} on f58 to b58
xfer f62 b62 ;return loops {1237 on yarn C3.3} on f62 to b62
xfer f66 b66 ;return loops {1215 on yarn C2.2} on f66 to b66
xfer f70 b70 ;return loops {1236 on yarn C3.3} on f70 to b70
xfer f74 b74 ;return loops {1214 on yarn C2.2} on f74 to b74
xfer f78 b78 ;return loops {1235 on yarn C3.3} on f78 to b78
xfer f82 b82 ;return loops {1213 on yarn C2.2} on f82 to b82
xfer f86 b86 ;return loops {1234 on yarn C3.3} on f86 to b86
xfer f90 b90 ;return loops {1212 on yarn C2.2} on f90 to b90
xfer f94 b94 ;return loops {1233 on yarn C3.3} on f94 to b94
xfer f98 b98 ;return loops {1211 on yarn C2.2} on f98 to b98
xfer f102 b102 ;return loops {1232 on yarn C3.3} on f102 to b102
xfer f106 b106 ;return loops {1210 on yarn C2.2} on f106 to b106
xfer f110 b110 ;return loops {1231 on yarn C3.3} on f110 to b110
xfer f114 b114 ;return loops {1209 on yarn C2.2} on f114 to b114
xfer f118 b118 ;return loops {1230 on yarn C3.3} on f118 to b118
knit - f116 1 ;knit loops: [1320 on yarn C1.1]. 
knit - b114 1 ;knit loops: [1321 on yarn C1.1]. 
knit - f112 1 ;knit loops: [1322 on yarn C1.1]. 
knit - f108 1 ;knit loops: [1323 on yarn C1.1]. 
knit - b106 1 ;knit loops: [1324 on yarn C1.1]. 
knit - f104 1 ;knit loops: [1325 on yarn C1.1]. 
knit - f100 1 ;knit loops: [1326 on yarn C1.1]. 
knit - b98 1 ;knit loops: [1327 on yarn C1.1]. 
knit - f96 1 ;knit loops: [1328 on yarn C1.1]. 
knit - f92 1 ;knit loops: [1329 on yarn C1.1]. 
knit - b90 1 ;knit loops: [1330 on yarn C1.1]. 
knit - f88 1 ;knit loops: [1331 on yarn C1.1]. 
knit - f84 1 ;knit loops: [1332 on yarn C1.1]. 
knit - b82 1 ;knit loops: [1333 on yarn C1.1]. 
knit - f80 1 ;knit loops: [1334 on yarn C1.1]. 
knit - f76 1 ;knit loops: [1335 on yarn C1.1]. 
knit - b74 1 ;knit loops: [1336 on yarn C1.1]. 
knit - f72 1 ;knit loops: [1337 on yarn C1.1]. 
knit - f68 1 ;knit loops: [1338 on yarn C1.1]. 
knit - b66 1 ;knit loops: [1339 on yarn C1.1]. 
knit - f64 1 ;knit loops: [1340 on yarn C1.1]. 
knit - f60 1 ;knit loops: [1341 on yarn C1.1]. 
knit - b58 1 ;knit loops: [1342 on yarn C1.1]. 
knit - f56 1 ;knit loops: [1343 on yarn C1.1]. 
knit - b50 1 ;knit loops: [1344 on yarn C1.1]. 
knit - b42 1 ;knit loops: [1345 on yarn C1.1]. 
knit - b34 1 ;knit loops: [1346 on yarn C1.1]. 
knit - f28 1 ;knit loops: [1347 on yarn C1.1]. 
knit - b26 1 ;knit loops: [1348 on yarn C1.1]. 
knit - f24 1 ;knit loops: [1349 on yarn C1.1]. 
knit - f20 1 ;knit loops: [1350 on yarn C1.1]. 
knit - b18 1 ;knit loops: [1351 on yarn C1.1]. 
knit - f16 1 ;knit loops: [1352 on yarn C1.1]. 
knit - f12 1 ;knit loops: [1353 on yarn C1.1]. 
knit - b10 1 ;knit loops: [1354 on yarn C1.1]. 
knit - f8 1 ;knit loops: [1355 on yarn C1.1]. 
knit - f4 1 ;knit loops: [1356 on yarn C1.1]. 
knit - b2 1 ;knit loops: [1357 on yarn C1.1]. 
knit - f0 1 ;knit loops: [1358 on yarn C1.1]. 
knit - b118 2 ;knit loops: [1359 on yarn C2.2]. 
knit - b110 2 ;knit loops: [1360 on yarn C2.2]. 
knit - b102 2 ;knit loops: [1361 on yarn C2.2]. 
knit - b94 2 ;knit loops: [1362 on yarn C2.2]. 
knit - b86 2 ;knit loops: [1363 on yarn C2.2]. 
knit - b78 2 ;knit loops: [1364 on yarn C2.2]. 
knit - b70 2 ;knit loops: [1365 on yarn C2.2]. 
knit - b62 2 ;knit loops: [1366 on yarn C2.2]. 
knit - b54 2 ;knit loops: [1367 on yarn C2.2]. 
knit - f52 2 ;knit loops: [1368 on yarn C2.2]. 
knit - f48 2 ;knit loops: [1369 on yarn C2.2]. 
knit - b46 2 ;knit loops: [1370 on yarn C2.2]. 
knit - f44 2 ;knit loops: [1371 on yarn C2.2]. 
knit - f40 2 ;knit loops: [1372 on yarn C2.2]. 
knit - b38 2 ;knit loops: [1373 on yarn C2.2]. 
knit - f36 2 ;knit loops: [1374 on yarn C2.2]. 
knit - f32 2 ;knit loops: [1375 on yarn C2.2]. 
knit - b30 2 ;knit loops: [1376 on yarn C2.2]. 
knit - b22 2 ;knit loops: [1377 on yarn C2.2]. 
knit - b14 2 ;knit loops: [1378 on yarn C2.2]. 
knit - b6 2 ;knit loops: [1379 on yarn C2.2]. 
knit - b114 3 ;knit loops: [1380 on yarn C3.3]. 
knit - b106 3 ;knit loops: [1381 on yarn C3.3]. 
knit - b98 3 ;knit loops: [1382 on yarn C3.3]. 
knit - b90 3 ;knit loops: [1383 on yarn C3.3]. 
knit - b82 3 ;knit loops: [1384 on yarn C3.3]. 
knit - b74 3 ;knit loops: [1385 on yarn C3.3]. 
knit - b66 3 ;knit loops: [1386 on yarn C3.3]. 
knit - b58 3 ;knit loops: [1387 on yarn C3.3]. 
knit - b50 3 ;knit loops: [1388 on yarn C3.3]. 
knit - b42 3 ;knit loops: [1389 on yarn C3.3]. 
knit - b34 3 ;knit loops: [1390 on yarn C3.3]. 
knit - b26 3 ;knit loops: [1391 on yarn C3.3]. 
knit - b18 3 ;knit loops: [1392 on yarn C3.3]. 
knit - b10 3 ;knit loops: [1393 on yarn C3.3]. 
knit - b2 3 ;knit loops: [1394 on yarn C3.3]. 
;KP Printout: 8: stripe 1: [b35, b39, b43, b47, b51, b55]
;Resetting to sheet s3:g4 of 4
; Peel sheet 0 relative to 3
; Peel sheet 1 relative to 3
; Peel sheet 2 relative to 3
xfer b2 f2 ;
xfer b6 f6 ;
xfer b10 f10 ;
xfer b14 f14 ;
xfer b18 f18 ;
xfer b22 f22 ;
xfer b26 f26 ;
xfer b30 f30 ;
xfer b34 f34 ;
xfer b38 f38 ;
xfer b42 f42 ;
xfer b46 f46 ;
xfer b50 f50 ;
xfer b54 f54 ;
xfer b58 f58 ;
xfer b62 f62 ;
xfer b66 f66 ;
xfer b70 f70 ;
xfer b74 f74 ;
xfer b78 f78 ;
xfer b82 f82 ;
xfer b86 f86 ;
xfer b90 f90 ;
xfer b94 f94 ;
xfer b98 f98 ;
xfer b102 f102 ;
xfer b106 f106 ;
xfer b110 f110 ;
xfer b114 f114 ;
xfer b118 f118 ;
; Peel sheet 3 relative to 3
xfer b1 f1 ;Return loops {1299 on yarn C3.3} on b1 to f1
xfer b5 f5 ;Return loops {1284 on yarn C2.2} on b5 to f5
xfer b9 f9 ;Return loops {1300 on yarn C3.3} on b9 to f9
xfer b13 f13 ;Return loops {1285 on yarn C2.2} on b13 to f13
xfer b17 f17 ;Return loops {1301 on yarn C3.3} on b17 to f17
xfer b21 f21 ;Return loops {1286 on yarn C2.2} on b21 to f21
xfer b25 f25 ;Return loops {1302 on yarn C3.3} on b25 to f25
xfer b29 f29 ;Return loops {1287 on yarn C2.2} on b29 to f29
xfer b33 f33 ;Return loops {1304 on yarn C3.3} on b33 to f33
xfer b37 f37 ;Return loops {1288 on yarn C2.2} on b37 to f37
xfer b41 f41 ;Return loops {1307 on yarn C3.3} on b41 to f41
xfer b45 f45 ;Return loops {1289 on yarn C2.2} on b45 to f45
xfer b49 f49 ;Return loops {1310 on yarn C3.3} on b49 to f49
xfer b53 f53 ;Return loops {1290 on yarn C2.2} on b53 to f53
xfer b57 f57 ;Return loops {1312 on yarn C3.3} on b57 to f57
xfer b61 f61 ;Return loops {1291 on yarn C2.2} on b61 to f61
xfer b65 f65 ;Return loops {1313 on yarn C3.3} on b65 to f65
xfer b69 f69 ;Return loops {1292 on yarn C2.2} on b69 to f69
xfer b73 f73 ;Return loops {1314 on yarn C3.3} on b73 to f73
xfer b77 f77 ;Return loops {1293 on yarn C2.2} on b77 to f77
xfer b81 f81 ;Return loops {1315 on yarn C3.3} on b81 to f81
xfer b85 f85 ;Return loops {1294 on yarn C2.2} on b85 to f85
xfer b89 f89 ;Return loops {1316 on yarn C3.3} on b89 to f89
xfer b93 f93 ;Return loops {1295 on yarn C2.2} on b93 to f93
xfer b97 f97 ;Return loops {1317 on yarn C3.3} on b97 to f97
xfer b101 f101 ;Return loops {1296 on yarn C2.2} on b101 to f101
xfer b105 f105 ;Return loops {1318 on yarn C3.3} on b105 to f105
xfer b109 f109 ;Return loops {1297 on yarn C2.2} on b109 to f109
xfer b113 f113 ;Return loops {1319 on yarn C3.3} on b113 to f113
xfer b117 f117 ;Return loops {1298 on yarn C2.2} on b117 to f117
knit + b3 1 ;knit loops: [1395 on yarn C1.1]. 
knit + f5 1 ;knit loops: [1396 on yarn C1.1]. 
knit + b7 1 ;knit loops: [1397 on yarn C1.1]. 
knit + b11 1 ;knit loops: [1398 on yarn C1.1]. 
knit + f13 1 ;knit loops: [1399 on yarn C1.1]. 
knit + b15 1 ;knit loops: [1400 on yarn C1.1]. 
knit + b19 1 ;knit loops: [1401 on yarn C1.1]. 
knit + f21 1 ;knit loops: [1402 on yarn C1.1]. 
knit + b23 1 ;knit loops: [1403 on yarn C1.1]. 
knit + b27 1 ;knit loops: [1404 on yarn C1.1]. 
knit + f29 1 ;knit loops: [1405 on yarn C1.1]. 
knit + b31 1 ;knit loops: [1406 on yarn C1.1]. 
knit + f37 1 ;knit loops: [1407 on yarn C1.1]. 
knit + f45 1 ;knit loops: [1408 on yarn C1.1]. 
knit + f53 1 ;knit loops: [1409 on yarn C1.1]. 
knit + b59 1 ;knit loops: [1410 on yarn C1.1]. 
knit + f61 1 ;knit loops: [1411 on yarn C1.1]. 
knit + b63 1 ;knit loops: [1412 on yarn C1.1]. 
knit + b67 1 ;knit loops: [1413 on yarn C1.1]. 
knit + f69 1 ;knit loops: [1414 on yarn C1.1]. 
knit + b71 1 ;knit loops: [1415 on yarn C1.1]. 
knit + b75 1 ;knit loops: [1416 on yarn C1.1]. 
knit + f77 1 ;knit loops: [1417 on yarn C1.1]. 
knit + b79 1 ;knit loops: [1418 on yarn C1.1]. 
knit + b83 1 ;knit loops: [1419 on yarn C1.1]. 
knit + f85 1 ;knit loops: [1420 on yarn C1.1]. 
knit + b87 1 ;knit loops: [1421 on yarn C1.1]. 
knit + b91 1 ;knit loops: [1422 on yarn C1.1]. 
knit + f93 1 ;knit loops: [1423 on yarn C1.1]. 
knit + b95 1 ;knit loops: [1424 on yarn C1.1]. 
knit + b99 1 ;knit loops: [1425 on yarn C1.1]. 
knit + f101 1 ;knit loops: [1426 on yarn C1.1]. 
knit + b103 1 ;knit loops: [1427 on yarn C1.1]. 
knit + b107 1 ;knit loops: [1428 on yarn C1.1]. 
knit + f109 1 ;knit loops: [1429 on yarn C1.1]. 
knit + b111 1 ;knit loops: [1430 on yarn C1.1]. 
knit + b115 1 ;knit loops: [1431 on yarn C1.1]. 
knit + f117 1 ;knit loops: [1432 on yarn C1.1]. 
knit + b119 1 ;knit loops: [1433 on yarn C1.1]. 
knit + f1 2 ;knit loops: [1434 on yarn C2.2]. 
knit + f9 2 ;knit loops: [1435 on yarn C2.2]. 
knit + f17 2 ;knit loops: [1436 on yarn C2.2]. 
knit + f25 2 ;knit loops: [1437 on yarn C2.2]. 
knit + f33 2 ;knit loops: [1438 on yarn C2.2]. 
knit + f41 2 ;knit loops: [1439 on yarn C2.2]. 
knit + f49 2 ;knit loops: [1440 on yarn C2.2]. 
knit + f57 2 ;knit loops: [1441 on yarn C2.2]. 
knit + f65 2 ;knit loops: [1442 on yarn C2.2]. 
knit + f73 2 ;knit loops: [1443 on yarn C2.2]. 
knit + f81 2 ;knit loops: [1444 on yarn C2.2]. 
knit + f89 2 ;knit loops: [1445 on yarn C2.2]. 
knit + f97 2 ;knit loops: [1446 on yarn C2.2]. 
knit + f105 2 ;knit loops: [1447 on yarn C2.2]. 
knit + f113 2 ;knit loops: [1448 on yarn C2.2]. 
knit + f5 3 ;knit loops: [1449 on yarn C3.3]. 
knit + f13 3 ;knit loops: [1450 on yarn C3.3]. 
knit + f21 3 ;knit loops: [1451 on yarn C3.3]. 
knit + f29 3 ;knit loops: [1452 on yarn C3.3]. 
knit + b35 3 ;knit loops: [1453 on yarn C3.3]. 
knit + f37 3 ;knit loops: [1454 on yarn C3.3]. 
knit + b39 3 ;knit loops: [1455 on yarn C3.3]. 
knit + b43 3 ;knit loops: [1456 on yarn C3.3]. 
knit + f45 3 ;knit loops: [1457 on yarn C3.3]. 
knit + b47 3 ;knit loops: [1458 on yarn C3.3]. 
knit + b51 3 ;knit loops: [1459 on yarn C3.3]. 
knit + f53 3 ;knit loops: [1460 on yarn C3.3]. 
knit + b55 3 ;knit loops: [1461 on yarn C3.3]. 
knit + f61 3 ;knit loops: [1462 on yarn C3.3]. 
knit + f69 3 ;knit loops: [1463 on yarn C3.3]. 
knit + f77 3 ;knit loops: [1464 on yarn C3.3]. 
knit + f85 3 ;knit loops: [1465 on yarn C3.3]. 
knit + f93 3 ;knit loops: [1466 on yarn C3.3]. 
knit + f101 3 ;knit loops: [1467 on yarn C3.3]. 
knit + f109 3 ;knit loops: [1468 on yarn C3.3]. 
knit + f117 3 ;knit loops: [1469 on yarn C3.3]. 
;KP Printout: 9: stripe 0: [f36, f40, f44, f48, f52, f56]
;Resetting to sheet s0:g4 of 4
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f5 b5 ;
xfer f9 b9 ;
xfer f13 b13 ;
xfer f17 b17 ;
xfer f21 b21 ;
xfer f25 b25 ;
xfer f29 b29 ;
xfer f33 b33 ;
xfer f37 b37 ;
xfer f41 b41 ;
xfer f45 b45 ;
xfer f49 b49 ;
xfer f53 b53 ;
xfer f57 b57 ;
xfer f61 b61 ;
xfer f65 b65 ;
xfer f69 b69 ;
xfer f73 b73 ;
xfer f77 b77 ;
xfer f81 b81 ;
xfer f85 b85 ;
xfer f89 b89 ;
xfer f93 b93 ;
xfer f97 b97 ;
xfer f101 b101 ;
xfer f105 b105 ;
xfer f109 b109 ;
xfer f113 b113 ;
xfer f117 b117 ;
; Peel sheet 2 relative to 0
; Peel sheet 3 relative to 0
xfer f2 b2 ;return loops {1394 on yarn C3.3} on f2 to b2
xfer f6 b6 ;return loops {1379 on yarn C2.2} on f6 to b6
xfer f10 b10 ;return loops {1393 on yarn C3.3} on f10 to b10
xfer f14 b14 ;return loops {1378 on yarn C2.2} on f14 to b14
xfer f18 b18 ;return loops {1392 on yarn C3.3} on f18 to b18
xfer f22 b22 ;return loops {1377 on yarn C2.2} on f22 to b22
xfer f26 b26 ;return loops {1391 on yarn C3.3} on f26 to b26
xfer f30 b30 ;return loops {1376 on yarn C2.2} on f30 to b30
xfer f34 b34 ;return loops {1390 on yarn C3.3} on f34 to b34
xfer f38 b38 ;return loops {1373 on yarn C2.2} on f38 to b38
xfer f42 b42 ;return loops {1389 on yarn C3.3} on f42 to b42
xfer f46 b46 ;return loops {1370 on yarn C2.2} on f46 to b46
xfer f50 b50 ;return loops {1388 on yarn C3.3} on f50 to b50
xfer f54 b54 ;return loops {1367 on yarn C2.2} on f54 to b54
xfer f58 b58 ;return loops {1387 on yarn C3.3} on f58 to b58
xfer f62 b62 ;return loops {1366 on yarn C2.2} on f62 to b62
xfer f66 b66 ;return loops {1386 on yarn C3.3} on f66 to b66
xfer f70 b70 ;return loops {1365 on yarn C2.2} on f70 to b70
xfer f74 b74 ;return loops {1385 on yarn C3.3} on f74 to b74
xfer f78 b78 ;return loops {1364 on yarn C2.2} on f78 to b78
xfer f82 b82 ;return loops {1384 on yarn C3.3} on f82 to b82
xfer f86 b86 ;return loops {1363 on yarn C2.2} on f86 to b86
xfer f90 b90 ;return loops {1383 on yarn C3.3} on f90 to b90
xfer f94 b94 ;return loops {1362 on yarn C2.2} on f94 to b94
xfer f98 b98 ;return loops {1382 on yarn C3.3} on f98 to b98
xfer f102 b102 ;return loops {1361 on yarn C2.2} on f102 to b102
xfer f106 b106 ;return loops {1381 on yarn C3.3} on f106 to b106
xfer f110 b110 ;return loops {1360 on yarn C2.2} on f110 to b110
xfer f114 b114 ;return loops {1380 on yarn C3.3} on f114 to b114
xfer f118 b118 ;return loops {1359 on yarn C2.2} on f118 to b118
knit - b118 1 ;knit loops: [1470 on yarn C1.1]. 
knit - f116 1 ;knit loops: [1471 on yarn C1.1]. 
knit - f112 1 ;knit loops: [1472 on yarn C1.1]. 
knit - b110 1 ;knit loops: [1473 on yarn C1.1]. 
knit - f108 1 ;knit loops: [1474 on yarn C1.1]. 
knit - f104 1 ;knit loops: [1475 on yarn C1.1]. 
knit - b102 1 ;knit loops: [1476 on yarn C1.1]. 
knit - f100 1 ;knit loops: [1477 on yarn C1.1]. 
knit - f96 1 ;knit loops: [1478 on yarn C1.1]. 
knit - b94 1 ;knit loops: [1479 on yarn C1.1]. 
knit - f92 1 ;knit loops: [1480 on yarn C1.1]. 
knit - f88 1 ;knit loops: [1481 on yarn C1.1]. 
knit - b86 1 ;knit loops: [1482 on yarn C1.1]. 
knit - f84 1 ;knit loops: [1483 on yarn C1.1]. 
knit - f80 1 ;knit loops: [1484 on yarn C1.1]. 
knit - b78 1 ;knit loops: [1485 on yarn C1.1]. 
knit - f76 1 ;knit loops: [1486 on yarn C1.1]. 
knit - f72 1 ;knit loops: [1487 on yarn C1.1]. 
knit - b70 1 ;knit loops: [1488 on yarn C1.1]. 
knit - f68 1 ;knit loops: [1489 on yarn C1.1]. 
knit - f64 1 ;knit loops: [1490 on yarn C1.1]. 
knit - b62 1 ;knit loops: [1491 on yarn C1.1]. 
knit - f60 1 ;knit loops: [1492 on yarn C1.1]. 
knit - b54 1 ;knit loops: [1493 on yarn C1.1]. 
knit - b46 1 ;knit loops: [1494 on yarn C1.1]. 
knit - b38 1 ;knit loops: [1495 on yarn C1.1]. 
knit - f32 1 ;knit loops: [1496 on yarn C1.1]. 
knit - b30 1 ;knit loops: [1497 on yarn C1.1]. 
knit - f28 1 ;knit loops: [1498 on yarn C1.1]. 
knit - f24 1 ;knit loops: [1499 on yarn C1.1]. 
knit - b22 1 ;knit loops: [1500 on yarn C1.1]. 
knit - f20 1 ;knit loops: [1501 on yarn C1.1]. 
knit - f16 1 ;knit loops: [1502 on yarn C1.1]. 
knit - b14 1 ;knit loops: [1503 on yarn C1.1]. 
knit - f12 1 ;knit loops: [1504 on yarn C1.1]. 
knit - f8 1 ;knit loops: [1505 on yarn C1.1]. 
knit - b6 1 ;knit loops: [1506 on yarn C1.1]. 
knit - f4 1 ;knit loops: [1507 on yarn C1.1]. 
knit - f0 1 ;knit loops: [1508 on yarn C1.1]. 
knit - b114 2 ;knit loops: [1509 on yarn C2.2]. 
knit - b106 2 ;knit loops: [1510 on yarn C2.2]. 
knit - b98 2 ;knit loops: [1511 on yarn C2.2]. 
knit - b90 2 ;knit loops: [1512 on yarn C2.2]. 
knit - b82 2 ;knit loops: [1513 on yarn C2.2]. 
knit - b74 2 ;knit loops: [1514 on yarn C2.2]. 
knit - b66 2 ;knit loops: [1515 on yarn C2.2]. 
knit - b58 2 ;knit loops: [1516 on yarn C2.2]. 
knit - f56 2 ;knit loops: [1517 on yarn C2.2]. 
knit - f52 2 ;knit loops: [1518 on yarn C2.2]. 
knit - b50 2 ;knit loops: [1519 on yarn C2.2]. 
knit - f48 2 ;knit loops: [1520 on yarn C2.2]. 
knit - f44 2 ;knit loops: [1521 on yarn C2.2]. 
knit - b42 2 ;knit loops: [1522 on yarn C2.2]. 
knit - f40 2 ;knit loops: [1523 on yarn C2.2]. 
knit - f36 2 ;knit loops: [1524 on yarn C2.2]. 
knit - b34 2 ;knit loops: [1525 on yarn C2.2]. 
knit - b26 2 ;knit loops: [1526 on yarn C2.2]. 
knit - b18 2 ;knit loops: [1527 on yarn C2.2]. 
knit - b10 2 ;knit loops: [1528 on yarn C2.2]. 
knit - b2 2 ;knit loops: [1529 on yarn C2.2]. 
knit - b118 3 ;knit loops: [1530 on yarn C3.3]. 
knit - b110 3 ;knit loops: [1531 on yarn C3.3]. 
knit - b102 3 ;knit loops: [1532 on yarn C3.3]. 
knit - b94 3 ;knit loops: [1533 on yarn C3.3]. 
knit - b86 3 ;knit loops: [1534 on yarn C3.3]. 
knit - b78 3 ;knit loops: [1535 on yarn C3.3]. 
knit - b70 3 ;knit loops: [1536 on yarn C3.3]. 
knit - b62 3 ;knit loops: [1537 on yarn C3.3]. 
knit - b54 3 ;knit loops: [1538 on yarn C3.3]. 
knit - b46 3 ;knit loops: [1539 on yarn C3.3]. 
knit - b38 3 ;knit loops: [1540 on yarn C3.3]. 
knit - b30 3 ;knit loops: [1541 on yarn C3.3]. 
knit - b22 3 ;knit loops: [1542 on yarn C3.3]. 
knit - b14 3 ;knit loops: [1543 on yarn C3.3]. 
knit - b6 3 ;knit loops: [1544 on yarn C3.3]. 
;KP Printout: 9: stripe 1: [b39, b43, b47, b51, b55, b59]
;Resetting to sheet s3:g4 of 4
; Peel sheet 0 relative to 3
; Peel sheet 1 relative to 3
; Peel sheet 2 relative to 3
xfer b2 f2 ;
xfer b6 f6 ;
xfer b10 f10 ;
xfer b14 f14 ;
xfer b18 f18 ;
xfer b22 f22 ;
xfer b26 f26 ;
xfer b30 f30 ;
xfer b34 f34 ;
xfer b38 f38 ;
xfer b42 f42 ;
xfer b46 f46 ;
xfer b50 f50 ;
xfer b54 f54 ;
xfer b58 f58 ;
xfer b62 f62 ;
xfer b66 f66 ;
xfer b70 f70 ;
xfer b74 f74 ;
xfer b78 f78 ;
xfer b82 f82 ;
xfer b86 f86 ;
xfer b90 f90 ;
xfer b94 f94 ;
xfer b98 f98 ;
xfer b102 f102 ;
xfer b106 f106 ;
xfer b110 f110 ;
xfer b114 f114 ;
xfer b118 f118 ;
; Peel sheet 3 relative to 3
xfer b1 f1 ;Return loops {1434 on yarn C2.2} on b1 to f1
xfer b5 f5 ;Return loops {1449 on yarn C3.3} on b5 to f5
xfer b9 f9 ;Return loops {1435 on yarn C2.2} on b9 to f9
xfer b13 f13 ;Return loops {1450 on yarn C3.3} on b13 to f13
xfer b17 f17 ;Return loops {1436 on yarn C2.2} on b17 to f17
xfer b21 f21 ;Return loops {1451 on yarn C3.3} on b21 to f21
xfer b25 f25 ;Return loops {1437 on yarn C2.2} on b25 to f25
xfer b29 f29 ;Return loops {1452 on yarn C3.3} on b29 to f29
xfer b33 f33 ;Return loops {1438 on yarn C2.2} on b33 to f33
xfer b37 f37 ;Return loops {1454 on yarn C3.3} on b37 to f37
xfer b41 f41 ;Return loops {1439 on yarn C2.2} on b41 to f41
xfer b45 f45 ;Return loops {1457 on yarn C3.3} on b45 to f45
xfer b49 f49 ;Return loops {1440 on yarn C2.2} on b49 to f49
xfer b53 f53 ;Return loops {1460 on yarn C3.3} on b53 to f53
xfer b57 f57 ;Return loops {1441 on yarn C2.2} on b57 to f57
xfer b61 f61 ;Return loops {1462 on yarn C3.3} on b61 to f61
xfer b65 f65 ;Return loops {1442 on yarn C2.2} on b65 to f65
xfer b69 f69 ;Return loops {1463 on yarn C3.3} on b69 to f69
xfer b73 f73 ;Return loops {1443 on yarn C2.2} on b73 to f73
xfer b77 f77 ;Return loops {1464 on yarn C3.3} on b77 to f77
xfer b81 f81 ;Return loops {1444 on yarn C2.2} on b81 to f81
xfer b85 f85 ;Return loops {1465 on yarn C3.3} on b85 to f85
xfer b89 f89 ;Return loops {1445 on yarn C2.2} on b89 to f89
xfer b93 f93 ;Return loops {1466 on yarn C3.3} on b93 to f93
xfer b97 f97 ;Return loops {1446 on yarn C2.2} on b97 to f97
xfer b101 f101 ;Return loops {1467 on yarn C3.3} on b101 to f101
xfer b105 f105 ;Return loops {1447 on yarn C2.2} on b105 to f105
xfer b109 f109 ;Return loops {1468 on yarn C3.3} on b109 to f109
xfer b113 f113 ;Return loops {1448 on yarn C2.2} on b113 to f113
xfer b117 f117 ;Return loops {1469 on yarn C3.3} on b117 to f117
knit + f1 1 ;knit loops: [1545 on yarn C1.1]. 
knit + b3 1 ;knit loops: [1546 on yarn C1.1]. 
knit + b7 1 ;knit loops: [1547 on yarn C1.1]. 
knit + f9 1 ;knit loops: [1548 on yarn C1.1]. 
knit + b11 1 ;knit loops: [1549 on yarn C1.1]. 
knit + b15 1 ;knit loops: [1550 on yarn C1.1]. 
knit + f17 1 ;knit loops: [1551 on yarn C1.1]. 
knit + b19 1 ;knit loops: [1552 on yarn C1.1]. 
knit + b23 1 ;knit loops: [1553 on yarn C1.1]. 
knit + f25 1 ;knit loops: [1554 on yarn C1.1]. 
knit + b27 1 ;knit loops: [1555 on yarn C1.1]. 
knit + b31 1 ;knit loops: [1556 on yarn C1.1]. 
knit + f33 1 ;knit loops: [1557 on yarn C1.1]. 
knit + b35 1 ;knit loops: [1558 on yarn C1.1]. 
knit + f41 1 ;knit loops: [1559 on yarn C1.1]. 
knit + f49 1 ;knit loops: [1560 on yarn C1.1]. 
knit + f57 1 ;knit loops: [1561 on yarn C1.1]. 
knit + b63 1 ;knit loops: [1562 on yarn C1.1]. 
knit + f65 1 ;knit loops: [1563 on yarn C1.1]. 
knit + b67 1 ;knit loops: [1564 on yarn C1.1]. 
knit + b71 1 ;knit loops: [1565 on yarn C1.1]. 
knit + f73 1 ;knit loops: [1566 on yarn C1.1]. 
knit + b75 1 ;knit loops: [1567 on yarn C1.1]. 
knit + b79 1 ;knit loops: [1568 on yarn C1.1]. 
knit + f81 1 ;knit loops: [1569 on yarn C1.1]. 
knit + b83 1 ;knit loops: [1570 on yarn C1.1]. 
knit + b87 1 ;knit loops: [1571 on yarn C1.1]. 
knit + f89 1 ;knit loops: [1572 on yarn C1.1]. 
knit + b91 1 ;knit loops: [1573 on yarn C1.1]. 
knit + b95 1 ;knit loops: [1574 on yarn C1.1]. 
knit + f97 1 ;knit loops: [1575 on yarn C1.1]. 
knit + b99 1 ;knit loops: [1576 on yarn C1.1]. 
knit + b103 1 ;knit loops: [1577 on yarn C1.1]. 
knit + f105 1 ;knit loops: [1578 on yarn C1.1]. 
knit + b107 1 ;knit loops: [1579 on yarn C1.1]. 
knit + b111 1 ;knit loops: [1580 on yarn C1.1]. 
knit + f113 1 ;knit loops: [1581 on yarn C1.1]. 
knit + b115 1 ;knit loops: [1582 on yarn C1.1]. 
knit + b119 1 ;knit loops: [1583 on yarn C1.1]. 
knit + f5 2 ;knit loops: [1584 on yarn C2.2]. 
knit + f13 2 ;knit loops: [1585 on yarn C2.2]. 
knit + f21 2 ;knit loops: [1586 on yarn C2.2]. 
knit + f29 2 ;knit loops: [1587 on yarn C2.2]. 
knit + f37 2 ;knit loops: [1588 on yarn C2.2]. 
knit + f45 2 ;knit loops: [1589 on yarn C2.2]. 
knit + f53 2 ;knit loops: [1590 on yarn C2.2]. 
knit + f61 2 ;knit loops: [1591 on yarn C2.2]. 
knit + f69 2 ;knit loops: [1592 on yarn C2.2]. 
knit + f77 2 ;knit loops: [1593 on yarn C2.2]. 
knit + f85 2 ;knit loops: [1594 on yarn C2.2]. 
knit + f93 2 ;knit loops: [1595 on yarn C2.2]. 
knit + f101 2 ;knit loops: [1596 on yarn C2.2]. 
knit + f109 2 ;knit loops: [1597 on yarn C2.2]. 
knit + f117 2 ;knit loops: [1598 on yarn C2.2]. 
knit + f1 3 ;knit loops: [1599 on yarn C3.3]. 
knit + f9 3 ;knit loops: [1600 on yarn C3.3]. 
knit + f17 3 ;knit loops: [1601 on yarn C3.3]. 
knit + f25 3 ;knit loops: [1602 on yarn C3.3]. 
knit + f33 3 ;knit loops: [1603 on yarn C3.3]. 
knit + b39 3 ;knit loops: [1604 on yarn C3.3]. 
knit + f41 3 ;knit loops: [1605 on yarn C3.3]. 
knit + b43 3 ;knit loops: [1606 on yarn C3.3]. 
knit + b47 3 ;knit loops: [1607 on yarn C3.3]. 
knit + f49 3 ;knit loops: [1608 on yarn C3.3]. 
knit + b51 3 ;knit loops: [1609 on yarn C3.3]. 
knit + b55 3 ;knit loops: [1610 on yarn C3.3]. 
knit + f57 3 ;knit loops: [1611 on yarn C3.3]. 
knit + b59 3 ;knit loops: [1612 on yarn C3.3]. 
knit + f65 3 ;knit loops: [1613 on yarn C3.3]. 
knit + f73 3 ;knit loops: [1614 on yarn C3.3]. 
knit + f81 3 ;knit loops: [1615 on yarn C3.3]. 
knit + f89 3 ;knit loops: [1616 on yarn C3.3]. 
knit + f97 3 ;knit loops: [1617 on yarn C3.3]. 
knit + f105 3 ;knit loops: [1618 on yarn C3.3]. 
knit + f113 3 ;knit loops: [1619 on yarn C3.3]. 
outhook 1; Cut yarn 1, disconnecting knitted piece
outhook 2; Cut yarn 2, disconnecting knitted piece
outhook 3; Cut yarn 3, disconnecting knitted piece
