;!knitout-2
;;Machine: SWG091N2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Gauge: 7
;;Width: 250
;;Position: Center
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
; Peel sheet 2 relative to 0
inhook  1 ;Activating carrier  1
;KP Printout: caston 24loops
tuck - f69 1 ; tuck loops: [0 on yarn C1.1]. 
tuck - f63 1 ; tuck loops: [1 on yarn C1.1]. 
tuck - f57 1 ; tuck loops: [2 on yarn C1.1]. 
tuck - f51 1 ; tuck loops: [3 on yarn C1.1]. 
tuck - f45 1 ; tuck loops: [4 on yarn C1.1]. 
tuck - f39 1 ; tuck loops: [5 on yarn C1.1]. 
tuck - f33 1 ; tuck loops: [6 on yarn C1.1]. 
tuck - f27 1 ; tuck loops: [7 on yarn C1.1]. 
tuck - f21 1 ; tuck loops: [8 on yarn C1.1]. 
tuck - f15 1 ; tuck loops: [9 on yarn C1.1]. 
tuck - f9 1 ; tuck loops: [10 on yarn C1.1]. 
tuck - f3 1 ; tuck loops: [11 on yarn C1.1]. 
releasehook  1 ;
tuck + f0 1 ; tuck loops: [12 on yarn C1.1]. 
tuck + f6 1 ; tuck loops: [13 on yarn C1.1]. 
tuck + f12 1 ; tuck loops: [14 on yarn C1.1]. 
tuck + f18 1 ; tuck loops: [15 on yarn C1.1]. 
tuck + f24 1 ; tuck loops: [16 on yarn C1.1]. 
tuck + f30 1 ; tuck loops: [17 on yarn C1.1]. 
tuck + f36 1 ; tuck loops: [18 on yarn C1.1]. 
tuck + f42 1 ; tuck loops: [19 on yarn C1.1]. 
tuck + f48 1 ; tuck loops: [20 on yarn C1.1]. 
tuck + f54 1 ; tuck loops: [21 on yarn C1.1]. 
tuck + f60 1 ; tuck loops: [22 on yarn C1.1]. 
tuck + f66 1 ; tuck loops: [23 on yarn C1.1]. 
knit - f69 1 ;knit loops: [24 on yarn C1.1]. 
knit - f66 1 ;knit loops: [25 on yarn C1.1]. 
knit - f63 1 ;knit loops: [26 on yarn C1.1]. 
knit - f60 1 ;knit loops: [27 on yarn C1.1]. 
knit - f57 1 ;knit loops: [28 on yarn C1.1]. 
knit - f54 1 ;knit loops: [29 on yarn C1.1]. 
knit - f51 1 ;knit loops: [30 on yarn C1.1]. 
knit - f48 1 ;knit loops: [31 on yarn C1.1]. 
knit - f45 1 ;knit loops: [32 on yarn C1.1]. 
knit - f42 1 ;knit loops: [33 on yarn C1.1]. 
knit - f39 1 ;knit loops: [34 on yarn C1.1]. 
knit - f36 1 ;knit loops: [35 on yarn C1.1]. 
knit - f33 1 ;knit loops: [36 on yarn C1.1]. 
knit - f30 1 ;knit loops: [37 on yarn C1.1]. 
knit - f27 1 ;knit loops: [38 on yarn C1.1]. 
knit - f24 1 ;knit loops: [39 on yarn C1.1]. 
knit - f21 1 ;knit loops: [40 on yarn C1.1]. 
knit - f18 1 ;knit loops: [41 on yarn C1.1]. 
knit - f15 1 ;knit loops: [42 on yarn C1.1]. 
knit - f12 1 ;knit loops: [43 on yarn C1.1]. 
knit - f9 1 ;knit loops: [44 on yarn C1.1]. 
knit - f6 1 ;knit loops: [45 on yarn C1.1]. 
knit - f3 1 ;knit loops: [46 on yarn C1.1]. 
knit - f0 1 ;knit loops: [47 on yarn C1.1]. 
knit + f0 1 ;knit loops: [48 on yarn C1.1]. 
knit + f3 1 ;knit loops: [49 on yarn C1.1]. 
knit + f6 1 ;knit loops: [50 on yarn C1.1]. 
knit + f9 1 ;knit loops: [51 on yarn C1.1]. 
knit + f12 1 ;knit loops: [52 on yarn C1.1]. 
knit + f15 1 ;knit loops: [53 on yarn C1.1]. 
knit + f18 1 ;knit loops: [54 on yarn C1.1]. 
knit + f21 1 ;knit loops: [55 on yarn C1.1]. 
knit + f24 1 ;knit loops: [56 on yarn C1.1]. 
knit + f27 1 ;knit loops: [57 on yarn C1.1]. 
knit + f30 1 ;knit loops: [58 on yarn C1.1]. 
knit + f33 1 ;knit loops: [59 on yarn C1.1]. 
knit + f36 1 ;knit loops: [60 on yarn C1.1]. 
knit + f39 1 ;knit loops: [61 on yarn C1.1]. 
knit + f42 1 ;knit loops: [62 on yarn C1.1]. 
knit + f45 1 ;knit loops: [63 on yarn C1.1]. 
knit + f48 1 ;knit loops: [64 on yarn C1.1]. 
knit + f51 1 ;knit loops: [65 on yarn C1.1]. 
knit + f54 1 ;knit loops: [66 on yarn C1.1]. 
knit + f57 1 ;knit loops: [67 on yarn C1.1]. 
knit + f60 1 ;knit loops: [68 on yarn C1.1]. 
knit + f63 1 ;knit loops: [69 on yarn C1.1]. 
knit + f66 1 ;knit loops: [70 on yarn C1.1]. 
knit + f69 1 ;knit loops: [71 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
inhook  2 ;Activating carrier  2
;KP Printout: caston 24loops
tuck - f70 2 ; tuck loops: [72 on yarn C2.2]. 
tuck - f64 2 ; tuck loops: [73 on yarn C2.2]. 
tuck - f58 2 ; tuck loops: [74 on yarn C2.2]. 
tuck - f52 2 ; tuck loops: [75 on yarn C2.2]. 
tuck - f46 2 ; tuck loops: [76 on yarn C2.2]. 
tuck - f40 2 ; tuck loops: [77 on yarn C2.2]. 
tuck - f34 2 ; tuck loops: [78 on yarn C2.2]. 
tuck - f28 2 ; tuck loops: [79 on yarn C2.2]. 
tuck - f22 2 ; tuck loops: [80 on yarn C2.2]. 
tuck - f16 2 ; tuck loops: [81 on yarn C2.2]. 
tuck - f10 2 ; tuck loops: [82 on yarn C2.2]. 
tuck - f4 2 ; tuck loops: [83 on yarn C2.2]. 
releasehook  2 ;
tuck + f1 2 ; tuck loops: [84 on yarn C2.2]. 
tuck + f7 2 ; tuck loops: [85 on yarn C2.2]. 
tuck + f13 2 ; tuck loops: [86 on yarn C2.2]. 
tuck + f19 2 ; tuck loops: [87 on yarn C2.2]. 
tuck + f25 2 ; tuck loops: [88 on yarn C2.2]. 
tuck + f31 2 ; tuck loops: [89 on yarn C2.2]. 
tuck + f37 2 ; tuck loops: [90 on yarn C2.2]. 
tuck + f43 2 ; tuck loops: [91 on yarn C2.2]. 
tuck + f49 2 ; tuck loops: [92 on yarn C2.2]. 
tuck + f55 2 ; tuck loops: [93 on yarn C2.2]. 
tuck + f61 2 ; tuck loops: [94 on yarn C2.2]. 
tuck + f67 2 ; tuck loops: [95 on yarn C2.2]. 
knit - f70 2 ;knit loops: [96 on yarn C2.2]. 
knit - f67 2 ;knit loops: [97 on yarn C2.2]. 
knit - f64 2 ;knit loops: [98 on yarn C2.2]. 
knit - f61 2 ;knit loops: [99 on yarn C2.2]. 
knit - f58 2 ;knit loops: [100 on yarn C2.2]. 
knit - f55 2 ;knit loops: [101 on yarn C2.2]. 
knit - f52 2 ;knit loops: [102 on yarn C2.2]. 
knit - f49 2 ;knit loops: [103 on yarn C2.2]. 
knit - f46 2 ;knit loops: [104 on yarn C2.2]. 
knit - f43 2 ;knit loops: [105 on yarn C2.2]. 
knit - f40 2 ;knit loops: [106 on yarn C2.2]. 
knit - f37 2 ;knit loops: [107 on yarn C2.2]. 
knit - f34 2 ;knit loops: [108 on yarn C2.2]. 
knit - f31 2 ;knit loops: [109 on yarn C2.2]. 
knit - f28 2 ;knit loops: [110 on yarn C2.2]. 
knit - f25 2 ;knit loops: [111 on yarn C2.2]. 
knit - f22 2 ;knit loops: [112 on yarn C2.2]. 
knit - f19 2 ;knit loops: [113 on yarn C2.2]. 
knit - f16 2 ;knit loops: [114 on yarn C2.2]. 
knit - f13 2 ;knit loops: [115 on yarn C2.2]. 
knit - f10 2 ;knit loops: [116 on yarn C2.2]. 
knit - f7 2 ;knit loops: [117 on yarn C2.2]. 
knit - f4 2 ;knit loops: [118 on yarn C2.2]. 
knit - f1 2 ;knit loops: [119 on yarn C2.2]. 
knit + f1 2 ;knit loops: [120 on yarn C2.2]. 
knit + f4 2 ;knit loops: [121 on yarn C2.2]. 
knit + f7 2 ;knit loops: [122 on yarn C2.2]. 
knit + f10 2 ;knit loops: [123 on yarn C2.2]. 
knit + f13 2 ;knit loops: [124 on yarn C2.2]. 
knit + f16 2 ;knit loops: [125 on yarn C2.2]. 
knit + f19 2 ;knit loops: [126 on yarn C2.2]. 
knit + f22 2 ;knit loops: [127 on yarn C2.2]. 
knit + f25 2 ;knit loops: [128 on yarn C2.2]. 
knit + f28 2 ;knit loops: [129 on yarn C2.2]. 
knit + f31 2 ;knit loops: [130 on yarn C2.2]. 
knit + f34 2 ;knit loops: [131 on yarn C2.2]. 
knit + f37 2 ;knit loops: [132 on yarn C2.2]. 
knit + f40 2 ;knit loops: [133 on yarn C2.2]. 
knit + f43 2 ;knit loops: [134 on yarn C2.2]. 
knit + f46 2 ;knit loops: [135 on yarn C2.2]. 
knit + f49 2 ;knit loops: [136 on yarn C2.2]. 
knit + f52 2 ;knit loops: [137 on yarn C2.2]. 
knit + f55 2 ;knit loops: [138 on yarn C2.2]. 
knit + f58 2 ;knit loops: [139 on yarn C2.2]. 
knit + f61 2 ;knit loops: [140 on yarn C2.2]. 
knit + f64 2 ;knit loops: [141 on yarn C2.2]. 
knit + f67 2 ;knit loops: [142 on yarn C2.2]. 
knit + f70 2 ;knit loops: [143 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
; Peel sheet 2 relative to 2
inhook  3 ;Activating carrier  3
;KP Printout: caston 24loops
tuck - f71 3 ; tuck loops: [144 on yarn C3.3]. 
tuck - f65 3 ; tuck loops: [145 on yarn C3.3]. 
tuck - f59 3 ; tuck loops: [146 on yarn C3.3]. 
tuck - f53 3 ; tuck loops: [147 on yarn C3.3]. 
tuck - f47 3 ; tuck loops: [148 on yarn C3.3]. 
tuck - f41 3 ; tuck loops: [149 on yarn C3.3]. 
tuck - f35 3 ; tuck loops: [150 on yarn C3.3]. 
tuck - f29 3 ; tuck loops: [151 on yarn C3.3]. 
tuck - f23 3 ; tuck loops: [152 on yarn C3.3]. 
tuck - f17 3 ; tuck loops: [153 on yarn C3.3]. 
tuck - f11 3 ; tuck loops: [154 on yarn C3.3]. 
tuck - f5 3 ; tuck loops: [155 on yarn C3.3]. 
releasehook  3 ;
tuck + f2 3 ; tuck loops: [156 on yarn C3.3]. 
tuck + f8 3 ; tuck loops: [157 on yarn C3.3]. 
tuck + f14 3 ; tuck loops: [158 on yarn C3.3]. 
tuck + f20 3 ; tuck loops: [159 on yarn C3.3]. 
tuck + f26 3 ; tuck loops: [160 on yarn C3.3]. 
tuck + f32 3 ; tuck loops: [161 on yarn C3.3]. 
tuck + f38 3 ; tuck loops: [162 on yarn C3.3]. 
tuck + f44 3 ; tuck loops: [163 on yarn C3.3]. 
tuck + f50 3 ; tuck loops: [164 on yarn C3.3]. 
tuck + f56 3 ; tuck loops: [165 on yarn C3.3]. 
tuck + f62 3 ; tuck loops: [166 on yarn C3.3]. 
tuck + f68 3 ; tuck loops: [167 on yarn C3.3]. 
knit - f71 3 ;knit loops: [168 on yarn C3.3]. 
knit - f68 3 ;knit loops: [169 on yarn C3.3]. 
knit - f65 3 ;knit loops: [170 on yarn C3.3]. 
knit - f62 3 ;knit loops: [171 on yarn C3.3]. 
knit - f59 3 ;knit loops: [172 on yarn C3.3]. 
knit - f56 3 ;knit loops: [173 on yarn C3.3]. 
knit - f53 3 ;knit loops: [174 on yarn C3.3]. 
knit - f50 3 ;knit loops: [175 on yarn C3.3]. 
knit - f47 3 ;knit loops: [176 on yarn C3.3]. 
knit - f44 3 ;knit loops: [177 on yarn C3.3]. 
knit - f41 3 ;knit loops: [178 on yarn C3.3]. 
knit - f38 3 ;knit loops: [179 on yarn C3.3]. 
knit - f35 3 ;knit loops: [180 on yarn C3.3]. 
knit - f32 3 ;knit loops: [181 on yarn C3.3]. 
knit - f29 3 ;knit loops: [182 on yarn C3.3]. 
knit - f26 3 ;knit loops: [183 on yarn C3.3]. 
knit - f23 3 ;knit loops: [184 on yarn C3.3]. 
knit - f20 3 ;knit loops: [185 on yarn C3.3]. 
knit - f17 3 ;knit loops: [186 on yarn C3.3]. 
knit - f14 3 ;knit loops: [187 on yarn C3.3]. 
knit - f11 3 ;knit loops: [188 on yarn C3.3]. 
knit - f8 3 ;knit loops: [189 on yarn C3.3]. 
knit - f5 3 ;knit loops: [190 on yarn C3.3]. 
knit - f2 3 ;knit loops: [191 on yarn C3.3]. 
knit + f2 3 ;knit loops: [192 on yarn C3.3]. 
knit + f5 3 ;knit loops: [193 on yarn C3.3]. 
knit + f8 3 ;knit loops: [194 on yarn C3.3]. 
knit + f11 3 ;knit loops: [195 on yarn C3.3]. 
knit + f14 3 ;knit loops: [196 on yarn C3.3]. 
knit + f17 3 ;knit loops: [197 on yarn C3.3]. 
knit + f20 3 ;knit loops: [198 on yarn C3.3]. 
knit + f23 3 ;knit loops: [199 on yarn C3.3]. 
knit + f26 3 ;knit loops: [200 on yarn C3.3]. 
knit + f29 3 ;knit loops: [201 on yarn C3.3]. 
knit + f32 3 ;knit loops: [202 on yarn C3.3]. 
knit + f35 3 ;knit loops: [203 on yarn C3.3]. 
knit + f38 3 ;knit loops: [204 on yarn C3.3]. 
knit + f41 3 ;knit loops: [205 on yarn C3.3]. 
knit + f44 3 ;knit loops: [206 on yarn C3.3]. 
knit + f47 3 ;knit loops: [207 on yarn C3.3]. 
knit + f50 3 ;knit loops: [208 on yarn C3.3]. 
knit + f53 3 ;knit loops: [209 on yarn C3.3]. 
knit + f56 3 ;knit loops: [210 on yarn C3.3]. 
knit + f59 3 ;knit loops: [211 on yarn C3.3]. 
knit + f62 3 ;knit loops: [212 on yarn C3.3]. 
knit + f65 3 ;knit loops: [213 on yarn C3.3]. 
knit + f68 3 ;knit loops: [214 on yarn C3.3]. 
knit + f71 3 ;knit loops: [215 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
xfer f49 b49 ;
xfer f52 b52 ;
xfer f55 b55 ;
xfer f58 b58 ;
xfer f61 b61 ;
xfer f64 b64 ;
xfer f67 b67 ;
xfer f70 b70 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer f26 b26 ;
xfer f29 b29 ;
xfer f32 b32 ;
xfer f35 b35 ;
xfer f38 b38 ;
xfer f41 b41 ;
xfer f44 b44 ;
xfer f47 b47 ;
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
; Peel sheet 2 relative to 0
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
; Peel sheet 2 relative to 0
xfer b25 f25 ;Return loops {128 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {129 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {130 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {131 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {132 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {133 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {134 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {135 on yarn C2.2} on b46 to f46
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer b49 f49 ;
xfer b52 f52 ;
xfer b55 f55 ;
xfer b58 f58 ;
xfer b61 f61 ;
xfer b64 f64 ;
xfer b67 f67 ;
xfer b70 f70 ;
; Peel sheet 2 relative to 0
xfer b50 f50 ;Return loops {208 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {209 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {210 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {211 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {212 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {213 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {214 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {215 on yarn C3.3} on b71 to f71
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {120 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {121 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {122 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {123 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {124 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {125 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {126 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {127 on yarn C2.2} on b22 to f22
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b26 f26 ;Return loops {200 on yarn C3.3} on b26 to f26
xfer b29 f29 ;Return loops {201 on yarn C3.3} on b29 to f29
xfer b32 f32 ;Return loops {202 on yarn C3.3} on b32 to f32
xfer b35 f35 ;Return loops {203 on yarn C3.3} on b35 to f35
xfer b38 f38 ;Return loops {204 on yarn C3.3} on b38 to f38
xfer b41 f41 ;Return loops {205 on yarn C3.3} on b41 to f41
xfer b44 f44 ;Return loops {206 on yarn C3.3} on b44 to f44
xfer b47 f47 ;Return loops {207 on yarn C3.3} on b47 to f47
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {192 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {193 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {194 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {195 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {196 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {197 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {198 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {199 on yarn C3.3} on b23 to f23
xfer b48 f48 ;Return loops {64 on yarn C1.1} on b48 to f48
xfer b50 f50 ;Return loops {208 on yarn C3.3} on b50 to f50
xfer b51 f51 ;Return loops {65 on yarn C1.1} on b51 to f51
xfer b53 f53 ;Return loops {209 on yarn C3.3} on b53 to f53
xfer b54 f54 ;Return loops {66 on yarn C1.1} on b54 to f54
xfer b56 f56 ;Return loops {210 on yarn C3.3} on b56 to f56
xfer b57 f57 ;Return loops {67 on yarn C1.1} on b57 to f57
xfer b59 f59 ;Return loops {211 on yarn C3.3} on b59 to f59
xfer b60 f60 ;Return loops {68 on yarn C1.1} on b60 to f60
xfer b62 f62 ;Return loops {212 on yarn C3.3} on b62 to f62
xfer b63 f63 ;Return loops {69 on yarn C1.1} on b63 to f63
xfer b65 f65 ;Return loops {213 on yarn C3.3} on b65 to f65
xfer b66 f66 ;Return loops {70 on yarn C1.1} on b66 to f66
xfer b68 f68 ;Return loops {214 on yarn C3.3} on b68 to f68
xfer b69 f69 ;Return loops {71 on yarn C1.1} on b69 to f69
xfer b71 f71 ;Return loops {215 on yarn C3.3} on b71 to f71
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
; Peel sheet 2 relative to 2
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
; Peel sheet 0 relative to 2
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 2
; Peel sheet 2 relative to 2
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {56 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {57 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {58 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {59 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {60 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {61 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {62 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {63 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {64 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {65 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {66 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {67 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {68 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {69 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {70 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {71 on yarn C1.1} on b69 to f69
knit - f69 1 ;knit loops: [216 on yarn C1.1]. 
knit - f66 1 ;knit loops: [217 on yarn C1.1]. 
knit - f63 1 ;knit loops: [218 on yarn C1.1]. 
knit - f60 1 ;knit loops: [219 on yarn C1.1]. 
knit - f57 1 ;knit loops: [220 on yarn C1.1]. 
knit - f54 1 ;knit loops: [221 on yarn C1.1]. 
knit - f51 1 ;knit loops: [222 on yarn C1.1]. 
knit - f48 1 ;knit loops: [223 on yarn C1.1]. 
knit - f45 1 ;knit loops: [224 on yarn C1.1]. 
knit - f42 1 ;knit loops: [225 on yarn C1.1]. 
knit - f39 1 ;knit loops: [226 on yarn C1.1]. 
knit - f36 1 ;knit loops: [227 on yarn C1.1]. 
knit - f33 1 ;knit loops: [228 on yarn C1.1]. 
knit - f30 1 ;knit loops: [229 on yarn C1.1]. 
knit - f27 1 ;knit loops: [230 on yarn C1.1]. 
knit - f24 1 ;knit loops: [231 on yarn C1.1]. 
knit - f21 1 ;knit loops: [232 on yarn C1.1]. 
knit - f18 1 ;knit loops: [233 on yarn C1.1]. 
knit - f15 1 ;knit loops: [234 on yarn C1.1]. 
knit - f12 1 ;knit loops: [235 on yarn C1.1]. 
knit - f9 1 ;knit loops: [236 on yarn C1.1]. 
knit - f6 1 ;knit loops: [237 on yarn C1.1]. 
knit - f3 1 ;knit loops: [238 on yarn C1.1]. 
knit - f0 1 ;knit loops: [239 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {120 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {121 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {122 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {123 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {124 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {125 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {126 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {127 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {128 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {129 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {130 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {131 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {132 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {133 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {134 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {135 on yarn C2.2} on b46 to f46
knit + f1 2 ;knit loops: [240 on yarn C2.2]. 
knit + f4 2 ;knit loops: [241 on yarn C2.2]. 
knit + f7 2 ;knit loops: [242 on yarn C2.2]. 
knit + f10 2 ;knit loops: [243 on yarn C2.2]. 
knit + f13 2 ;knit loops: [244 on yarn C2.2]. 
knit + f16 2 ;knit loops: [245 on yarn C2.2]. 
knit + f19 2 ;knit loops: [246 on yarn C2.2]. 
knit + f22 2 ;knit loops: [247 on yarn C2.2]. 
knit + f25 2 ;knit loops: [248 on yarn C2.2]. 
knit + f28 2 ;knit loops: [249 on yarn C2.2]. 
knit + f31 2 ;knit loops: [250 on yarn C2.2]. 
knit + f34 2 ;knit loops: [251 on yarn C2.2]. 
knit + f37 2 ;knit loops: [252 on yarn C2.2]. 
knit + f40 2 ;knit loops: [253 on yarn C2.2]. 
knit + f43 2 ;knit loops: [254 on yarn C2.2]. 
knit + f46 2 ;knit loops: [255 on yarn C2.2]. 
knit + f49 2 ;knit loops: [256 on yarn C2.2]. 
knit + f52 2 ;knit loops: [257 on yarn C2.2]. 
knit + f55 2 ;knit loops: [258 on yarn C2.2]. 
knit + f58 2 ;knit loops: [259 on yarn C2.2]. 
knit + f61 2 ;knit loops: [260 on yarn C2.2]. 
knit + f64 2 ;knit loops: [261 on yarn C2.2]. 
knit + f67 2 ;knit loops: [262 on yarn C2.2]. 
knit + f70 2 ;knit loops: [263 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {192 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {193 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {194 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {195 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {196 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {197 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {198 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {199 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {208 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {209 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {210 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {211 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {212 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {213 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {214 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {215 on yarn C3.3} on b71 to f71
knit - f71 3 ;knit loops: [264 on yarn C3.3]. 
knit - f68 3 ;knit loops: [265 on yarn C3.3]. 
knit - f65 3 ;knit loops: [266 on yarn C3.3]. 
knit - f62 3 ;knit loops: [267 on yarn C3.3]. 
knit - f59 3 ;knit loops: [268 on yarn C3.3]. 
knit - f56 3 ;knit loops: [269 on yarn C3.3]. 
knit - f53 3 ;knit loops: [270 on yarn C3.3]. 
knit - f50 3 ;knit loops: [271 on yarn C3.3]. 
knit - f47 3 ;knit loops: [272 on yarn C3.3]. 
knit - f44 3 ;knit loops: [273 on yarn C3.3]. 
knit - f41 3 ;knit loops: [274 on yarn C3.3]. 
knit - f38 3 ;knit loops: [275 on yarn C3.3]. 
knit - f35 3 ;knit loops: [276 on yarn C3.3]. 
knit - f32 3 ;knit loops: [277 on yarn C3.3]. 
knit - f29 3 ;knit loops: [278 on yarn C3.3]. 
knit - f26 3 ;knit loops: [279 on yarn C3.3]. 
knit - f23 3 ;knit loops: [280 on yarn C3.3]. 
knit - f20 3 ;knit loops: [281 on yarn C3.3]. 
knit - f17 3 ;knit loops: [282 on yarn C3.3]. 
knit - f14 3 ;knit loops: [283 on yarn C3.3]. 
knit - f11 3 ;knit loops: [284 on yarn C3.3]. 
knit - f8 3 ;knit loops: [285 on yarn C3.3]. 
knit - f5 3 ;knit loops: [286 on yarn C3.3]. 
knit - f2 3 ;knit loops: [287 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {231 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {230 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {229 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {228 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {227 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {226 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {225 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {224 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {223 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {222 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {221 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {220 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {219 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {218 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {217 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {216 on yarn C1.1} on b69 to f69
knit + f0 1 ;knit loops: [288 on yarn C1.1]. 
knit + f3 1 ;knit loops: [289 on yarn C1.1]. 
knit + f6 1 ;knit loops: [290 on yarn C1.1]. 
knit + f9 1 ;knit loops: [291 on yarn C1.1]. 
knit + f12 1 ;knit loops: [292 on yarn C1.1]. 
knit + f15 1 ;knit loops: [293 on yarn C1.1]. 
knit + f18 1 ;knit loops: [294 on yarn C1.1]. 
knit + f21 1 ;knit loops: [295 on yarn C1.1]. 
knit + f24 1 ;knit loops: [296 on yarn C1.1]. 
knit + f27 1 ;knit loops: [297 on yarn C1.1]. 
knit + f30 1 ;knit loops: [298 on yarn C1.1]. 
knit + f33 1 ;knit loops: [299 on yarn C1.1]. 
knit + f36 1 ;knit loops: [300 on yarn C1.1]. 
knit + f39 1 ;knit loops: [301 on yarn C1.1]. 
knit + f42 1 ;knit loops: [302 on yarn C1.1]. 
knit + f45 1 ;knit loops: [303 on yarn C1.1]. 
knit + f48 1 ;knit loops: [304 on yarn C1.1]. 
knit + f51 1 ;knit loops: [305 on yarn C1.1]. 
knit + f54 1 ;knit loops: [306 on yarn C1.1]. 
knit + f57 1 ;knit loops: [307 on yarn C1.1]. 
knit + f60 1 ;knit loops: [308 on yarn C1.1]. 
knit + f63 1 ;knit loops: [309 on yarn C1.1]. 
knit + f66 1 ;knit loops: [310 on yarn C1.1]. 
knit + f69 1 ;knit loops: [311 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {240 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {241 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {242 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {243 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {244 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {245 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {246 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {247 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {248 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {249 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {250 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {251 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {252 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {253 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {254 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {255 on yarn C2.2} on b46 to f46
knit - f70 2 ;knit loops: [312 on yarn C2.2]. 
knit - f67 2 ;knit loops: [313 on yarn C2.2]. 
knit - f64 2 ;knit loops: [314 on yarn C2.2]. 
knit - f61 2 ;knit loops: [315 on yarn C2.2]. 
knit - f58 2 ;knit loops: [316 on yarn C2.2]. 
knit - f55 2 ;knit loops: [317 on yarn C2.2]. 
knit - f52 2 ;knit loops: [318 on yarn C2.2]. 
knit - f49 2 ;knit loops: [319 on yarn C2.2]. 
knit - f46 2 ;knit loops: [320 on yarn C2.2]. 
knit - f43 2 ;knit loops: [321 on yarn C2.2]. 
knit - f40 2 ;knit loops: [322 on yarn C2.2]. 
knit - f37 2 ;knit loops: [323 on yarn C2.2]. 
knit - f34 2 ;knit loops: [324 on yarn C2.2]. 
knit - f31 2 ;knit loops: [325 on yarn C2.2]. 
knit - f28 2 ;knit loops: [326 on yarn C2.2]. 
knit - f25 2 ;knit loops: [327 on yarn C2.2]. 
knit - f22 2 ;knit loops: [328 on yarn C2.2]. 
knit - f19 2 ;knit loops: [329 on yarn C2.2]. 
knit - f16 2 ;knit loops: [330 on yarn C2.2]. 
knit - f13 2 ;knit loops: [331 on yarn C2.2]. 
knit - f10 2 ;knit loops: [332 on yarn C2.2]. 
knit - f7 2 ;knit loops: [333 on yarn C2.2]. 
knit - f4 2 ;knit loops: [334 on yarn C2.2]. 
knit - f1 2 ;knit loops: [335 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {287 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {286 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {285 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {284 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {283 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {282 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {281 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {280 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {271 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {270 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {269 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {268 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {267 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {266 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {265 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {264 on yarn C3.3} on b71 to f71
knit + f2 3 ;knit loops: [336 on yarn C3.3]. 
knit + f5 3 ;knit loops: [337 on yarn C3.3]. 
knit + f8 3 ;knit loops: [338 on yarn C3.3]. 
knit + f11 3 ;knit loops: [339 on yarn C3.3]. 
knit + f14 3 ;knit loops: [340 on yarn C3.3]. 
knit + f17 3 ;knit loops: [341 on yarn C3.3]. 
knit + f20 3 ;knit loops: [342 on yarn C3.3]. 
knit + f23 3 ;knit loops: [343 on yarn C3.3]. 
knit + f26 3 ;knit loops: [344 on yarn C3.3]. 
knit + f29 3 ;knit loops: [345 on yarn C3.3]. 
knit + f32 3 ;knit loops: [346 on yarn C3.3]. 
knit + f35 3 ;knit loops: [347 on yarn C3.3]. 
knit + f38 3 ;knit loops: [348 on yarn C3.3]. 
knit + f41 3 ;knit loops: [349 on yarn C3.3]. 
knit + f44 3 ;knit loops: [350 on yarn C3.3]. 
knit + f47 3 ;knit loops: [351 on yarn C3.3]. 
knit + f50 3 ;knit loops: [352 on yarn C3.3]. 
knit + f53 3 ;knit loops: [353 on yarn C3.3]. 
knit + f56 3 ;knit loops: [354 on yarn C3.3]. 
knit + f59 3 ;knit loops: [355 on yarn C3.3]. 
knit + f62 3 ;knit loops: [356 on yarn C3.3]. 
knit + f65 3 ;knit loops: [357 on yarn C3.3]. 
knit + f68 3 ;knit loops: [358 on yarn C3.3]. 
knit + f71 3 ;knit loops: [359 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {296 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {297 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {298 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {299 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {300 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {301 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {302 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {303 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {304 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {305 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {306 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {307 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {308 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {309 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {310 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {311 on yarn C1.1} on b69 to f69
knit - f69 1 ;knit loops: [360 on yarn C1.1]. 
knit - f66 1 ;knit loops: [361 on yarn C1.1]. 
knit - f63 1 ;knit loops: [362 on yarn C1.1]. 
knit - f60 1 ;knit loops: [363 on yarn C1.1]. 
knit - f57 1 ;knit loops: [364 on yarn C1.1]. 
knit - f54 1 ;knit loops: [365 on yarn C1.1]. 
knit - f51 1 ;knit loops: [366 on yarn C1.1]. 
knit - f48 1 ;knit loops: [367 on yarn C1.1]. 
knit - f45 1 ;knit loops: [368 on yarn C1.1]. 
knit - f42 1 ;knit loops: [369 on yarn C1.1]. 
knit - f39 1 ;knit loops: [370 on yarn C1.1]. 
knit - f36 1 ;knit loops: [371 on yarn C1.1]. 
knit - f33 1 ;knit loops: [372 on yarn C1.1]. 
knit - f30 1 ;knit loops: [373 on yarn C1.1]. 
knit - f27 1 ;knit loops: [374 on yarn C1.1]. 
knit - f24 1 ;knit loops: [375 on yarn C1.1]. 
knit - f21 1 ;knit loops: [376 on yarn C1.1]. 
knit - f18 1 ;knit loops: [377 on yarn C1.1]. 
knit - f15 1 ;knit loops: [378 on yarn C1.1]. 
knit - f12 1 ;knit loops: [379 on yarn C1.1]. 
knit - f9 1 ;knit loops: [380 on yarn C1.1]. 
knit - f6 1 ;knit loops: [381 on yarn C1.1]. 
knit - f3 1 ;knit loops: [382 on yarn C1.1]. 
knit - f0 1 ;knit loops: [383 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {335 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {334 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {333 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {332 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {331 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {330 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {329 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {328 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {327 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {326 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {325 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {324 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {323 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {322 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {321 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {320 on yarn C2.2} on b46 to f46
knit + f1 2 ;knit loops: [384 on yarn C2.2]. 
knit + f4 2 ;knit loops: [385 on yarn C2.2]. 
knit + f7 2 ;knit loops: [386 on yarn C2.2]. 
knit + f10 2 ;knit loops: [387 on yarn C2.2]. 
knit + f13 2 ;knit loops: [388 on yarn C2.2]. 
knit + f16 2 ;knit loops: [389 on yarn C2.2]. 
knit + f19 2 ;knit loops: [390 on yarn C2.2]. 
knit + f22 2 ;knit loops: [391 on yarn C2.2]. 
knit + f25 2 ;knit loops: [392 on yarn C2.2]. 
knit + f28 2 ;knit loops: [393 on yarn C2.2]. 
knit + f31 2 ;knit loops: [394 on yarn C2.2]. 
knit + f34 2 ;knit loops: [395 on yarn C2.2]. 
knit + f37 2 ;knit loops: [396 on yarn C2.2]. 
knit + f40 2 ;knit loops: [397 on yarn C2.2]. 
knit + f43 2 ;knit loops: [398 on yarn C2.2]. 
knit + f46 2 ;knit loops: [399 on yarn C2.2]. 
knit + f49 2 ;knit loops: [400 on yarn C2.2]. 
knit + f52 2 ;knit loops: [401 on yarn C2.2]. 
knit + f55 2 ;knit loops: [402 on yarn C2.2]. 
knit + f58 2 ;knit loops: [403 on yarn C2.2]. 
knit + f61 2 ;knit loops: [404 on yarn C2.2]. 
knit + f64 2 ;knit loops: [405 on yarn C2.2]. 
knit + f67 2 ;knit loops: [406 on yarn C2.2]. 
knit + f70 2 ;knit loops: [407 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {336 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {337 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {338 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {339 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {340 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {341 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {342 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {343 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {352 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {353 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {354 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {355 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {356 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {357 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {358 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {359 on yarn C3.3} on b71 to f71
knit - f71 3 ;knit loops: [408 on yarn C3.3]. 
knit - f68 3 ;knit loops: [409 on yarn C3.3]. 
knit - f65 3 ;knit loops: [410 on yarn C3.3]. 
knit - f62 3 ;knit loops: [411 on yarn C3.3]. 
knit - f59 3 ;knit loops: [412 on yarn C3.3]. 
knit - f56 3 ;knit loops: [413 on yarn C3.3]. 
knit - f53 3 ;knit loops: [414 on yarn C3.3]. 
knit - f50 3 ;knit loops: [415 on yarn C3.3]. 
knit - f47 3 ;knit loops: [416 on yarn C3.3]. 
knit - f44 3 ;knit loops: [417 on yarn C3.3]. 
knit - f41 3 ;knit loops: [418 on yarn C3.3]. 
knit - f38 3 ;knit loops: [419 on yarn C3.3]. 
knit - f35 3 ;knit loops: [420 on yarn C3.3]. 
knit - f32 3 ;knit loops: [421 on yarn C3.3]. 
knit - f29 3 ;knit loops: [422 on yarn C3.3]. 
knit - f26 3 ;knit loops: [423 on yarn C3.3]. 
knit - f23 3 ;knit loops: [424 on yarn C3.3]. 
knit - f20 3 ;knit loops: [425 on yarn C3.3]. 
knit - f17 3 ;knit loops: [426 on yarn C3.3]. 
knit - f14 3 ;knit loops: [427 on yarn C3.3]. 
knit - f11 3 ;knit loops: [428 on yarn C3.3]. 
knit - f8 3 ;knit loops: [429 on yarn C3.3]. 
knit - f5 3 ;knit loops: [430 on yarn C3.3]. 
knit - f2 3 ;knit loops: [431 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {375 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {374 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {373 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {372 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {371 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {370 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {369 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {368 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {367 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {366 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {365 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {364 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {363 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {362 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {361 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {360 on yarn C1.1} on b69 to f69
knit + f0 1 ;knit loops: [432 on yarn C1.1]. 
knit + f3 1 ;knit loops: [433 on yarn C1.1]. 
knit + f6 1 ;knit loops: [434 on yarn C1.1]. 
knit + f9 1 ;knit loops: [435 on yarn C1.1]. 
knit + f12 1 ;knit loops: [436 on yarn C1.1]. 
knit + f15 1 ;knit loops: [437 on yarn C1.1]. 
knit + f18 1 ;knit loops: [438 on yarn C1.1]. 
knit + f21 1 ;knit loops: [439 on yarn C1.1]. 
knit + f24 1 ;knit loops: [440 on yarn C1.1]. 
knit + f27 1 ;knit loops: [441 on yarn C1.1]. 
knit + f30 1 ;knit loops: [442 on yarn C1.1]. 
knit + f33 1 ;knit loops: [443 on yarn C1.1]. 
knit + f36 1 ;knit loops: [444 on yarn C1.1]. 
knit + f39 1 ;knit loops: [445 on yarn C1.1]. 
knit + f42 1 ;knit loops: [446 on yarn C1.1]. 
knit + f45 1 ;knit loops: [447 on yarn C1.1]. 
knit + f48 1 ;knit loops: [448 on yarn C1.1]. 
knit + f51 1 ;knit loops: [449 on yarn C1.1]. 
knit + f54 1 ;knit loops: [450 on yarn C1.1]. 
knit + f57 1 ;knit loops: [451 on yarn C1.1]. 
knit + f60 1 ;knit loops: [452 on yarn C1.1]. 
knit + f63 1 ;knit loops: [453 on yarn C1.1]. 
knit + f66 1 ;knit loops: [454 on yarn C1.1]. 
knit + f69 1 ;knit loops: [455 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {384 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {385 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {386 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {387 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {388 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {389 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {390 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {391 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {392 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {393 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {394 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {395 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {396 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {397 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {398 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {399 on yarn C2.2} on b46 to f46
knit - f70 2 ;knit loops: [456 on yarn C2.2]. 
knit - f67 2 ;knit loops: [457 on yarn C2.2]. 
knit - f64 2 ;knit loops: [458 on yarn C2.2]. 
knit - f61 2 ;knit loops: [459 on yarn C2.2]. 
knit - f58 2 ;knit loops: [460 on yarn C2.2]. 
knit - f55 2 ;knit loops: [461 on yarn C2.2]. 
knit - f52 2 ;knit loops: [462 on yarn C2.2]. 
knit - f49 2 ;knit loops: [463 on yarn C2.2]. 
knit - f46 2 ;knit loops: [464 on yarn C2.2]. 
knit - f43 2 ;knit loops: [465 on yarn C2.2]. 
knit - f40 2 ;knit loops: [466 on yarn C2.2]. 
knit - f37 2 ;knit loops: [467 on yarn C2.2]. 
knit - f34 2 ;knit loops: [468 on yarn C2.2]. 
knit - f31 2 ;knit loops: [469 on yarn C2.2]. 
knit - f28 2 ;knit loops: [470 on yarn C2.2]. 
knit - f25 2 ;knit loops: [471 on yarn C2.2]. 
knit - f22 2 ;knit loops: [472 on yarn C2.2]. 
knit - f19 2 ;knit loops: [473 on yarn C2.2]. 
knit - f16 2 ;knit loops: [474 on yarn C2.2]. 
knit - f13 2 ;knit loops: [475 on yarn C2.2]. 
knit - f10 2 ;knit loops: [476 on yarn C2.2]. 
knit - f7 2 ;knit loops: [477 on yarn C2.2]. 
knit - f4 2 ;knit loops: [478 on yarn C2.2]. 
knit - f1 2 ;knit loops: [479 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {431 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {430 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {429 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {428 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {427 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {426 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {425 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {424 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {415 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {414 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {413 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {412 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {411 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {410 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {409 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {408 on yarn C3.3} on b71 to f71
knit + f2 3 ;knit loops: [480 on yarn C3.3]. 
knit + f5 3 ;knit loops: [481 on yarn C3.3]. 
knit + f8 3 ;knit loops: [482 on yarn C3.3]. 
knit + f11 3 ;knit loops: [483 on yarn C3.3]. 
knit + f14 3 ;knit loops: [484 on yarn C3.3]. 
knit + f17 3 ;knit loops: [485 on yarn C3.3]. 
knit + f20 3 ;knit loops: [486 on yarn C3.3]. 
knit + f23 3 ;knit loops: [487 on yarn C3.3]. 
knit + f26 3 ;knit loops: [488 on yarn C3.3]. 
knit + f29 3 ;knit loops: [489 on yarn C3.3]. 
knit + f32 3 ;knit loops: [490 on yarn C3.3]. 
knit + f35 3 ;knit loops: [491 on yarn C3.3]. 
knit + f38 3 ;knit loops: [492 on yarn C3.3]. 
knit + f41 3 ;knit loops: [493 on yarn C3.3]. 
knit + f44 3 ;knit loops: [494 on yarn C3.3]. 
knit + f47 3 ;knit loops: [495 on yarn C3.3]. 
knit + f50 3 ;knit loops: [496 on yarn C3.3]. 
knit + f53 3 ;knit loops: [497 on yarn C3.3]. 
knit + f56 3 ;knit loops: [498 on yarn C3.3]. 
knit + f59 3 ;knit loops: [499 on yarn C3.3]. 
knit + f62 3 ;knit loops: [500 on yarn C3.3]. 
knit + f65 3 ;knit loops: [501 on yarn C3.3]. 
knit + f68 3 ;knit loops: [502 on yarn C3.3]. 
knit + f71 3 ;knit loops: [503 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {440 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {441 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {442 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {443 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {444 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {445 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {446 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {447 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {448 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {449 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {450 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {451 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {452 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {453 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {454 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {455 on yarn C1.1} on b69 to f69
knit - f69 1 ;knit loops: [504 on yarn C1.1]. 
knit - f66 1 ;knit loops: [505 on yarn C1.1]. 
knit - f63 1 ;knit loops: [506 on yarn C1.1]. 
knit - f60 1 ;knit loops: [507 on yarn C1.1]. 
knit - f57 1 ;knit loops: [508 on yarn C1.1]. 
knit - f54 1 ;knit loops: [509 on yarn C1.1]. 
knit - f51 1 ;knit loops: [510 on yarn C1.1]. 
knit - f48 1 ;knit loops: [511 on yarn C1.1]. 
knit - f45 1 ;knit loops: [512 on yarn C1.1]. 
knit - f42 1 ;knit loops: [513 on yarn C1.1]. 
knit - f39 1 ;knit loops: [514 on yarn C1.1]. 
knit - f36 1 ;knit loops: [515 on yarn C1.1]. 
knit - f33 1 ;knit loops: [516 on yarn C1.1]. 
knit - f30 1 ;knit loops: [517 on yarn C1.1]. 
knit - f27 1 ;knit loops: [518 on yarn C1.1]. 
knit - f24 1 ;knit loops: [519 on yarn C1.1]. 
knit - f21 1 ;knit loops: [520 on yarn C1.1]. 
knit - f18 1 ;knit loops: [521 on yarn C1.1]. 
knit - f15 1 ;knit loops: [522 on yarn C1.1]. 
knit - f12 1 ;knit loops: [523 on yarn C1.1]. 
knit - f9 1 ;knit loops: [524 on yarn C1.1]. 
knit - f6 1 ;knit loops: [525 on yarn C1.1]. 
knit - f3 1 ;knit loops: [526 on yarn C1.1]. 
knit - f0 1 ;knit loops: [527 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {479 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {478 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {477 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {476 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {475 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {474 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {473 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {472 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {471 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {470 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {469 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {468 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {467 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {466 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {465 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {464 on yarn C2.2} on b46 to f46
knit + f1 2 ;knit loops: [528 on yarn C2.2]. 
knit + f4 2 ;knit loops: [529 on yarn C2.2]. 
knit + f7 2 ;knit loops: [530 on yarn C2.2]. 
knit + f10 2 ;knit loops: [531 on yarn C2.2]. 
knit + f13 2 ;knit loops: [532 on yarn C2.2]. 
knit + f16 2 ;knit loops: [533 on yarn C2.2]. 
knit + f19 2 ;knit loops: [534 on yarn C2.2]. 
knit + f22 2 ;knit loops: [535 on yarn C2.2]. 
knit + f25 2 ;knit loops: [536 on yarn C2.2]. 
knit + f28 2 ;knit loops: [537 on yarn C2.2]. 
knit + f31 2 ;knit loops: [538 on yarn C2.2]. 
knit + f34 2 ;knit loops: [539 on yarn C2.2]. 
knit + f37 2 ;knit loops: [540 on yarn C2.2]. 
knit + f40 2 ;knit loops: [541 on yarn C2.2]. 
knit + f43 2 ;knit loops: [542 on yarn C2.2]. 
knit + f46 2 ;knit loops: [543 on yarn C2.2]. 
knit + f49 2 ;knit loops: [544 on yarn C2.2]. 
knit + f52 2 ;knit loops: [545 on yarn C2.2]. 
knit + f55 2 ;knit loops: [546 on yarn C2.2]. 
knit + f58 2 ;knit loops: [547 on yarn C2.2]. 
knit + f61 2 ;knit loops: [548 on yarn C2.2]. 
knit + f64 2 ;knit loops: [549 on yarn C2.2]. 
knit + f67 2 ;knit loops: [550 on yarn C2.2]. 
knit + f70 2 ;knit loops: [551 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {480 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {481 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {482 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {483 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {484 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {485 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {486 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {487 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {496 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {497 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {498 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {499 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {500 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {501 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {502 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {503 on yarn C3.3} on b71 to f71
knit - f71 3 ;knit loops: [552 on yarn C3.3]. 
knit - f68 3 ;knit loops: [553 on yarn C3.3]. 
knit - f65 3 ;knit loops: [554 on yarn C3.3]. 
knit - f62 3 ;knit loops: [555 on yarn C3.3]. 
knit - f59 3 ;knit loops: [556 on yarn C3.3]. 
knit - f56 3 ;knit loops: [557 on yarn C3.3]. 
knit - f53 3 ;knit loops: [558 on yarn C3.3]. 
knit - f50 3 ;knit loops: [559 on yarn C3.3]. 
knit - f47 3 ;knit loops: [560 on yarn C3.3]. 
knit - f44 3 ;knit loops: [561 on yarn C3.3]. 
knit - f41 3 ;knit loops: [562 on yarn C3.3]. 
knit - f38 3 ;knit loops: [563 on yarn C3.3]. 
knit - f35 3 ;knit loops: [564 on yarn C3.3]. 
knit - f32 3 ;knit loops: [565 on yarn C3.3]. 
knit - f29 3 ;knit loops: [566 on yarn C3.3]. 
knit - f26 3 ;knit loops: [567 on yarn C3.3]. 
knit - f23 3 ;knit loops: [568 on yarn C3.3]. 
knit - f20 3 ;knit loops: [569 on yarn C3.3]. 
knit - f17 3 ;knit loops: [570 on yarn C3.3]. 
knit - f14 3 ;knit loops: [571 on yarn C3.3]. 
knit - f11 3 ;knit loops: [572 on yarn C3.3]. 
knit - f8 3 ;knit loops: [573 on yarn C3.3]. 
knit - f5 3 ;knit loops: [574 on yarn C3.3]. 
knit - f2 3 ;knit loops: [575 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {519 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {518 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {517 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {516 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {515 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {514 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {513 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {512 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {511 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {510 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {509 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {508 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {507 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {506 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {505 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {504 on yarn C1.1} on b69 to f69
knit + f0 1 ;knit loops: [576 on yarn C1.1]. 
knit + f3 1 ;knit loops: [577 on yarn C1.1]. 
knit + f6 1 ;knit loops: [578 on yarn C1.1]. 
knit + f9 1 ;knit loops: [579 on yarn C1.1]. 
knit + f12 1 ;knit loops: [580 on yarn C1.1]. 
knit + f15 1 ;knit loops: [581 on yarn C1.1]. 
knit + f18 1 ;knit loops: [582 on yarn C1.1]. 
knit + f21 1 ;knit loops: [583 on yarn C1.1]. 
knit + f24 1 ;knit loops: [584 on yarn C1.1]. 
knit + f27 1 ;knit loops: [585 on yarn C1.1]. 
knit + f30 1 ;knit loops: [586 on yarn C1.1]. 
knit + f33 1 ;knit loops: [587 on yarn C1.1]. 
knit + f36 1 ;knit loops: [588 on yarn C1.1]. 
knit + f39 1 ;knit loops: [589 on yarn C1.1]. 
knit + f42 1 ;knit loops: [590 on yarn C1.1]. 
knit + f45 1 ;knit loops: [591 on yarn C1.1]. 
knit + f48 1 ;knit loops: [592 on yarn C1.1]. 
knit + f51 1 ;knit loops: [593 on yarn C1.1]. 
knit + f54 1 ;knit loops: [594 on yarn C1.1]. 
knit + f57 1 ;knit loops: [595 on yarn C1.1]. 
knit + f60 1 ;knit loops: [596 on yarn C1.1]. 
knit + f63 1 ;knit loops: [597 on yarn C1.1]. 
knit + f66 1 ;knit loops: [598 on yarn C1.1]. 
knit + f69 1 ;knit loops: [599 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {528 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {529 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {530 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {531 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {532 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {533 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {534 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {535 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {536 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {537 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {538 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {539 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {540 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {541 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {542 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {543 on yarn C2.2} on b46 to f46
knit - f70 2 ;knit loops: [600 on yarn C2.2]. 
knit - f67 2 ;knit loops: [601 on yarn C2.2]. 
knit - f64 2 ;knit loops: [602 on yarn C2.2]. 
knit - f61 2 ;knit loops: [603 on yarn C2.2]. 
knit - f58 2 ;knit loops: [604 on yarn C2.2]. 
knit - f55 2 ;knit loops: [605 on yarn C2.2]. 
knit - f52 2 ;knit loops: [606 on yarn C2.2]. 
knit - f49 2 ;knit loops: [607 on yarn C2.2]. 
knit - f46 2 ;knit loops: [608 on yarn C2.2]. 
knit - f43 2 ;knit loops: [609 on yarn C2.2]. 
knit - f40 2 ;knit loops: [610 on yarn C2.2]. 
knit - f37 2 ;knit loops: [611 on yarn C2.2]. 
knit - f34 2 ;knit loops: [612 on yarn C2.2]. 
knit - f31 2 ;knit loops: [613 on yarn C2.2]. 
knit - f28 2 ;knit loops: [614 on yarn C2.2]. 
knit - f25 2 ;knit loops: [615 on yarn C2.2]. 
knit - f22 2 ;knit loops: [616 on yarn C2.2]. 
knit - f19 2 ;knit loops: [617 on yarn C2.2]. 
knit - f16 2 ;knit loops: [618 on yarn C2.2]. 
knit - f13 2 ;knit loops: [619 on yarn C2.2]. 
knit - f10 2 ;knit loops: [620 on yarn C2.2]. 
knit - f7 2 ;knit loops: [621 on yarn C2.2]. 
knit - f4 2 ;knit loops: [622 on yarn C2.2]. 
knit - f1 2 ;knit loops: [623 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {575 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {574 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {573 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {572 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {571 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {570 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {569 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {568 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {559 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {558 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {557 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {556 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {555 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {554 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {553 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {552 on yarn C3.3} on b71 to f71
knit + f2 3 ;knit loops: [624 on yarn C3.3]. 
knit + f5 3 ;knit loops: [625 on yarn C3.3]. 
knit + f8 3 ;knit loops: [626 on yarn C3.3]. 
knit + f11 3 ;knit loops: [627 on yarn C3.3]. 
knit + f14 3 ;knit loops: [628 on yarn C3.3]. 
knit + f17 3 ;knit loops: [629 on yarn C3.3]. 
knit + f20 3 ;knit loops: [630 on yarn C3.3]. 
knit + f23 3 ;knit loops: [631 on yarn C3.3]. 
knit + f26 3 ;knit loops: [632 on yarn C3.3]. 
knit + f29 3 ;knit loops: [633 on yarn C3.3]. 
knit + f32 3 ;knit loops: [634 on yarn C3.3]. 
knit + f35 3 ;knit loops: [635 on yarn C3.3]. 
knit + f38 3 ;knit loops: [636 on yarn C3.3]. 
knit + f41 3 ;knit loops: [637 on yarn C3.3]. 
knit + f44 3 ;knit loops: [638 on yarn C3.3]. 
knit + f47 3 ;knit loops: [639 on yarn C3.3]. 
knit + f50 3 ;knit loops: [640 on yarn C3.3]. 
knit + f53 3 ;knit loops: [641 on yarn C3.3]. 
knit + f56 3 ;knit loops: [642 on yarn C3.3]. 
knit + f59 3 ;knit loops: [643 on yarn C3.3]. 
knit + f62 3 ;knit loops: [644 on yarn C3.3]. 
knit + f65 3 ;knit loops: [645 on yarn C3.3]. 
knit + f68 3 ;knit loops: [646 on yarn C3.3]. 
knit + f71 3 ;knit loops: [647 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {584 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {585 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {586 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {587 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {588 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {589 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {590 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {591 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {592 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {593 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {594 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {595 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {596 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {597 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {598 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {599 on yarn C1.1} on b69 to f69
knit - f69 1 ;knit loops: [648 on yarn C1.1]. 
knit - f66 1 ;knit loops: [649 on yarn C1.1]. 
knit - f63 1 ;knit loops: [650 on yarn C1.1]. 
knit - f60 1 ;knit loops: [651 on yarn C1.1]. 
knit - f57 1 ;knit loops: [652 on yarn C1.1]. 
knit - f54 1 ;knit loops: [653 on yarn C1.1]. 
knit - f51 1 ;knit loops: [654 on yarn C1.1]. 
knit - f48 1 ;knit loops: [655 on yarn C1.1]. 
knit - f45 1 ;knit loops: [656 on yarn C1.1]. 
knit - f42 1 ;knit loops: [657 on yarn C1.1]. 
knit - f39 1 ;knit loops: [658 on yarn C1.1]. 
knit - f36 1 ;knit loops: [659 on yarn C1.1]. 
knit - f33 1 ;knit loops: [660 on yarn C1.1]. 
knit - f30 1 ;knit loops: [661 on yarn C1.1]. 
knit - f27 1 ;knit loops: [662 on yarn C1.1]. 
knit - f24 1 ;knit loops: [663 on yarn C1.1]. 
knit - f21 1 ;knit loops: [664 on yarn C1.1]. 
knit - f18 1 ;knit loops: [665 on yarn C1.1]. 
knit - f15 1 ;knit loops: [666 on yarn C1.1]. 
knit - f12 1 ;knit loops: [667 on yarn C1.1]. 
knit - f9 1 ;knit loops: [668 on yarn C1.1]. 
knit - f6 1 ;knit loops: [669 on yarn C1.1]. 
knit - f3 1 ;knit loops: [670 on yarn C1.1]. 
knit - f0 1 ;knit loops: [671 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {623 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {622 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {621 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {620 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {619 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {618 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {617 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {616 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {615 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {614 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {613 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {612 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {611 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {610 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {609 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {608 on yarn C2.2} on b46 to f46
knit + f1 2 ;knit loops: [672 on yarn C2.2]. 
knit + f4 2 ;knit loops: [673 on yarn C2.2]. 
knit + f7 2 ;knit loops: [674 on yarn C2.2]. 
knit + f10 2 ;knit loops: [675 on yarn C2.2]. 
knit + f13 2 ;knit loops: [676 on yarn C2.2]. 
knit + f16 2 ;knit loops: [677 on yarn C2.2]. 
knit + f19 2 ;knit loops: [678 on yarn C2.2]. 
knit + f22 2 ;knit loops: [679 on yarn C2.2]. 
knit + f25 2 ;knit loops: [680 on yarn C2.2]. 
knit + f28 2 ;knit loops: [681 on yarn C2.2]. 
knit + f31 2 ;knit loops: [682 on yarn C2.2]. 
knit + f34 2 ;knit loops: [683 on yarn C2.2]. 
knit + f37 2 ;knit loops: [684 on yarn C2.2]. 
knit + f40 2 ;knit loops: [685 on yarn C2.2]. 
knit + f43 2 ;knit loops: [686 on yarn C2.2]. 
knit + f46 2 ;knit loops: [687 on yarn C2.2]. 
knit + f49 2 ;knit loops: [688 on yarn C2.2]. 
knit + f52 2 ;knit loops: [689 on yarn C2.2]. 
knit + f55 2 ;knit loops: [690 on yarn C2.2]. 
knit + f58 2 ;knit loops: [691 on yarn C2.2]. 
knit + f61 2 ;knit loops: [692 on yarn C2.2]. 
knit + f64 2 ;knit loops: [693 on yarn C2.2]. 
knit + f67 2 ;knit loops: [694 on yarn C2.2]. 
knit + f70 2 ;knit loops: [695 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {624 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {625 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {626 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {627 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {628 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {629 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {630 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {631 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {640 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {641 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {642 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {643 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {644 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {645 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {646 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {647 on yarn C3.3} on b71 to f71
knit - f71 3 ;knit loops: [696 on yarn C3.3]. 
knit - f68 3 ;knit loops: [697 on yarn C3.3]. 
knit - f65 3 ;knit loops: [698 on yarn C3.3]. 
knit - f62 3 ;knit loops: [699 on yarn C3.3]. 
knit - f59 3 ;knit loops: [700 on yarn C3.3]. 
knit - f56 3 ;knit loops: [701 on yarn C3.3]. 
knit - f53 3 ;knit loops: [702 on yarn C3.3]. 
knit - f50 3 ;knit loops: [703 on yarn C3.3]. 
knit - f47 3 ;knit loops: [704 on yarn C3.3]. 
knit - f44 3 ;knit loops: [705 on yarn C3.3]. 
knit - f41 3 ;knit loops: [706 on yarn C3.3]. 
knit - f38 3 ;knit loops: [707 on yarn C3.3]. 
knit - f35 3 ;knit loops: [708 on yarn C3.3]. 
knit - f32 3 ;knit loops: [709 on yarn C3.3]. 
knit - f29 3 ;knit loops: [710 on yarn C3.3]. 
knit - f26 3 ;knit loops: [711 on yarn C3.3]. 
knit - f23 3 ;knit loops: [712 on yarn C3.3]. 
knit - f20 3 ;knit loops: [713 on yarn C3.3]. 
knit - f17 3 ;knit loops: [714 on yarn C3.3]. 
knit - f14 3 ;knit loops: [715 on yarn C3.3]. 
knit - f11 3 ;knit loops: [716 on yarn C3.3]. 
knit - f8 3 ;knit loops: [717 on yarn C3.3]. 
knit - f5 3 ;knit loops: [718 on yarn C3.3]. 
knit - f2 3 ;knit loops: [719 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {663 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {662 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {661 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {660 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {659 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {658 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {657 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {656 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {655 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {654 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {653 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {652 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {651 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {650 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {649 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {648 on yarn C1.1} on b69 to f69
knit + f0 1 ;knit loops: [720 on yarn C1.1]. 
knit + f3 1 ;knit loops: [721 on yarn C1.1]. 
knit + f6 1 ;knit loops: [722 on yarn C1.1]. 
knit + f9 1 ;knit loops: [723 on yarn C1.1]. 
knit + f12 1 ;knit loops: [724 on yarn C1.1]. 
knit + f15 1 ;knit loops: [725 on yarn C1.1]. 
knit + f18 1 ;knit loops: [726 on yarn C1.1]. 
knit + f21 1 ;knit loops: [727 on yarn C1.1]. 
knit + f24 1 ;knit loops: [728 on yarn C1.1]. 
knit + f27 1 ;knit loops: [729 on yarn C1.1]. 
knit + f30 1 ;knit loops: [730 on yarn C1.1]. 
knit + f33 1 ;knit loops: [731 on yarn C1.1]. 
knit + f36 1 ;knit loops: [732 on yarn C1.1]. 
knit + f39 1 ;knit loops: [733 on yarn C1.1]. 
knit + f42 1 ;knit loops: [734 on yarn C1.1]. 
knit + f45 1 ;knit loops: [735 on yarn C1.1]. 
knit + f48 1 ;knit loops: [736 on yarn C1.1]. 
knit + f51 1 ;knit loops: [737 on yarn C1.1]. 
knit + f54 1 ;knit loops: [738 on yarn C1.1]. 
knit + f57 1 ;knit loops: [739 on yarn C1.1]. 
knit + f60 1 ;knit loops: [740 on yarn C1.1]. 
knit + f63 1 ;knit loops: [741 on yarn C1.1]. 
knit + f66 1 ;knit loops: [742 on yarn C1.1]. 
knit + f69 1 ;knit loops: [743 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {672 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {673 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {674 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {675 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {676 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {677 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {678 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {679 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {680 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {681 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {682 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {683 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {684 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {685 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {686 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {687 on yarn C2.2} on b46 to f46
knit - f70 2 ;knit loops: [744 on yarn C2.2]. 
knit - f67 2 ;knit loops: [745 on yarn C2.2]. 
knit - f64 2 ;knit loops: [746 on yarn C2.2]. 
knit - f61 2 ;knit loops: [747 on yarn C2.2]. 
knit - f58 2 ;knit loops: [748 on yarn C2.2]. 
knit - f55 2 ;knit loops: [749 on yarn C2.2]. 
knit - f52 2 ;knit loops: [750 on yarn C2.2]. 
knit - f49 2 ;knit loops: [751 on yarn C2.2]. 
knit - f46 2 ;knit loops: [752 on yarn C2.2]. 
knit - f43 2 ;knit loops: [753 on yarn C2.2]. 
knit - f40 2 ;knit loops: [754 on yarn C2.2]. 
knit - f37 2 ;knit loops: [755 on yarn C2.2]. 
knit - f34 2 ;knit loops: [756 on yarn C2.2]. 
knit - f31 2 ;knit loops: [757 on yarn C2.2]. 
knit - f28 2 ;knit loops: [758 on yarn C2.2]. 
knit - f25 2 ;knit loops: [759 on yarn C2.2]. 
knit - f22 2 ;knit loops: [760 on yarn C2.2]. 
knit - f19 2 ;knit loops: [761 on yarn C2.2]. 
knit - f16 2 ;knit loops: [762 on yarn C2.2]. 
knit - f13 2 ;knit loops: [763 on yarn C2.2]. 
knit - f10 2 ;knit loops: [764 on yarn C2.2]. 
knit - f7 2 ;knit loops: [765 on yarn C2.2]. 
knit - f4 2 ;knit loops: [766 on yarn C2.2]. 
knit - f1 2 ;knit loops: [767 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {719 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {718 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {717 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {716 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {715 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {714 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {713 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {712 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {703 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {702 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {701 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {700 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {699 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {698 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {697 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {696 on yarn C3.3} on b71 to f71
knit + f2 3 ;knit loops: [768 on yarn C3.3]. 
knit + f5 3 ;knit loops: [769 on yarn C3.3]. 
knit + f8 3 ;knit loops: [770 on yarn C3.3]. 
knit + f11 3 ;knit loops: [771 on yarn C3.3]. 
knit + f14 3 ;knit loops: [772 on yarn C3.3]. 
knit + f17 3 ;knit loops: [773 on yarn C3.3]. 
knit + f20 3 ;knit loops: [774 on yarn C3.3]. 
knit + f23 3 ;knit loops: [775 on yarn C3.3]. 
knit + f26 3 ;knit loops: [776 on yarn C3.3]. 
knit + f29 3 ;knit loops: [777 on yarn C3.3]. 
knit + f32 3 ;knit loops: [778 on yarn C3.3]. 
knit + f35 3 ;knit loops: [779 on yarn C3.3]. 
knit + f38 3 ;knit loops: [780 on yarn C3.3]. 
knit + f41 3 ;knit loops: [781 on yarn C3.3]. 
knit + f44 3 ;knit loops: [782 on yarn C3.3]. 
knit + f47 3 ;knit loops: [783 on yarn C3.3]. 
knit + f50 3 ;knit loops: [784 on yarn C3.3]. 
knit + f53 3 ;knit loops: [785 on yarn C3.3]. 
knit + f56 3 ;knit loops: [786 on yarn C3.3]. 
knit + f59 3 ;knit loops: [787 on yarn C3.3]. 
knit + f62 3 ;knit loops: [788 on yarn C3.3]. 
knit + f65 3 ;knit loops: [789 on yarn C3.3]. 
knit + f68 3 ;knit loops: [790 on yarn C3.3]. 
knit + f71 3 ;knit loops: [791 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {728 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {729 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {730 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {731 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {732 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {733 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {734 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {735 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {736 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {737 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {738 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {739 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {740 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {741 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {742 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {743 on yarn C1.1} on b69 to f69
knit - f69 1 ;knit loops: [792 on yarn C1.1]. 
knit - f66 1 ;knit loops: [793 on yarn C1.1]. 
knit - f63 1 ;knit loops: [794 on yarn C1.1]. 
knit - f60 1 ;knit loops: [795 on yarn C1.1]. 
knit - f57 1 ;knit loops: [796 on yarn C1.1]. 
knit - f54 1 ;knit loops: [797 on yarn C1.1]. 
knit - f51 1 ;knit loops: [798 on yarn C1.1]. 
knit - f48 1 ;knit loops: [799 on yarn C1.1]. 
knit - f45 1 ;knit loops: [800 on yarn C1.1]. 
knit - f42 1 ;knit loops: [801 on yarn C1.1]. 
knit - f39 1 ;knit loops: [802 on yarn C1.1]. 
knit - f36 1 ;knit loops: [803 on yarn C1.1]. 
knit - f33 1 ;knit loops: [804 on yarn C1.1]. 
knit - f30 1 ;knit loops: [805 on yarn C1.1]. 
knit - f27 1 ;knit loops: [806 on yarn C1.1]. 
knit - f24 1 ;knit loops: [807 on yarn C1.1]. 
knit - f21 1 ;knit loops: [808 on yarn C1.1]. 
knit - f18 1 ;knit loops: [809 on yarn C1.1]. 
knit - f15 1 ;knit loops: [810 on yarn C1.1]. 
knit - f12 1 ;knit loops: [811 on yarn C1.1]. 
knit - f9 1 ;knit loops: [812 on yarn C1.1]. 
knit - f6 1 ;knit loops: [813 on yarn C1.1]. 
knit - f3 1 ;knit loops: [814 on yarn C1.1]. 
knit - f0 1 ;knit loops: [815 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {767 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {766 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {765 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {764 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {763 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {762 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {761 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {760 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {759 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {758 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {757 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {756 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {755 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {754 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {753 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {752 on yarn C2.2} on b46 to f46
knit + f1 2 ;knit loops: [816 on yarn C2.2]. 
knit + f4 2 ;knit loops: [817 on yarn C2.2]. 
knit + f7 2 ;knit loops: [818 on yarn C2.2]. 
knit + f10 2 ;knit loops: [819 on yarn C2.2]. 
knit + f13 2 ;knit loops: [820 on yarn C2.2]. 
knit + f16 2 ;knit loops: [821 on yarn C2.2]. 
knit + f19 2 ;knit loops: [822 on yarn C2.2]. 
knit + f22 2 ;knit loops: [823 on yarn C2.2]. 
knit + f25 2 ;knit loops: [824 on yarn C2.2]. 
knit + f28 2 ;knit loops: [825 on yarn C2.2]. 
knit + f31 2 ;knit loops: [826 on yarn C2.2]. 
knit + f34 2 ;knit loops: [827 on yarn C2.2]. 
knit + f37 2 ;knit loops: [828 on yarn C2.2]. 
knit + f40 2 ;knit loops: [829 on yarn C2.2]. 
knit + f43 2 ;knit loops: [830 on yarn C2.2]. 
knit + f46 2 ;knit loops: [831 on yarn C2.2]. 
knit + f49 2 ;knit loops: [832 on yarn C2.2]. 
knit + f52 2 ;knit loops: [833 on yarn C2.2]. 
knit + f55 2 ;knit loops: [834 on yarn C2.2]. 
knit + f58 2 ;knit loops: [835 on yarn C2.2]. 
knit + f61 2 ;knit loops: [836 on yarn C2.2]. 
knit + f64 2 ;knit loops: [837 on yarn C2.2]. 
knit + f67 2 ;knit loops: [838 on yarn C2.2]. 
knit + f70 2 ;knit loops: [839 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {768 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {769 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {770 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {771 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {772 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {773 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {774 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {775 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {784 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {785 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {786 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {787 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {788 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {789 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {790 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {791 on yarn C3.3} on b71 to f71
knit - f71 3 ;knit loops: [840 on yarn C3.3]. 
knit - f68 3 ;knit loops: [841 on yarn C3.3]. 
knit - f65 3 ;knit loops: [842 on yarn C3.3]. 
knit - f62 3 ;knit loops: [843 on yarn C3.3]. 
knit - f59 3 ;knit loops: [844 on yarn C3.3]. 
knit - f56 3 ;knit loops: [845 on yarn C3.3]. 
knit - f53 3 ;knit loops: [846 on yarn C3.3]. 
knit - f50 3 ;knit loops: [847 on yarn C3.3]. 
knit - f47 3 ;knit loops: [848 on yarn C3.3]. 
knit - f44 3 ;knit loops: [849 on yarn C3.3]. 
knit - f41 3 ;knit loops: [850 on yarn C3.3]. 
knit - f38 3 ;knit loops: [851 on yarn C3.3]. 
knit - f35 3 ;knit loops: [852 on yarn C3.3]. 
knit - f32 3 ;knit loops: [853 on yarn C3.3]. 
knit - f29 3 ;knit loops: [854 on yarn C3.3]. 
knit - f26 3 ;knit loops: [855 on yarn C3.3]. 
knit - f23 3 ;knit loops: [856 on yarn C3.3]. 
knit - f20 3 ;knit loops: [857 on yarn C3.3]. 
knit - f17 3 ;knit loops: [858 on yarn C3.3]. 
knit - f14 3 ;knit loops: [859 on yarn C3.3]. 
knit - f11 3 ;knit loops: [860 on yarn C3.3]. 
knit - f8 3 ;knit loops: [861 on yarn C3.3]. 
knit - f5 3 ;knit loops: [862 on yarn C3.3]. 
knit - f2 3 ;knit loops: [863 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {807 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {806 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {805 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {804 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {803 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {802 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {801 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {800 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {799 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {798 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {797 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {796 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {795 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {794 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {793 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {792 on yarn C1.1} on b69 to f69
knit + f0 1 ;knit loops: [864 on yarn C1.1]. 
knit + f3 1 ;knit loops: [865 on yarn C1.1]. 
knit + f6 1 ;knit loops: [866 on yarn C1.1]. 
knit + f9 1 ;knit loops: [867 on yarn C1.1]. 
knit + f12 1 ;knit loops: [868 on yarn C1.1]. 
knit + f15 1 ;knit loops: [869 on yarn C1.1]. 
knit + f18 1 ;knit loops: [870 on yarn C1.1]. 
knit + f21 1 ;knit loops: [871 on yarn C1.1]. 
knit + f24 1 ;knit loops: [872 on yarn C1.1]. 
knit + f27 1 ;knit loops: [873 on yarn C1.1]. 
knit + f30 1 ;knit loops: [874 on yarn C1.1]. 
knit + f33 1 ;knit loops: [875 on yarn C1.1]. 
knit + f36 1 ;knit loops: [876 on yarn C1.1]. 
knit + f39 1 ;knit loops: [877 on yarn C1.1]. 
knit + f42 1 ;knit loops: [878 on yarn C1.1]. 
knit + f45 1 ;knit loops: [879 on yarn C1.1]. 
knit + f48 1 ;knit loops: [880 on yarn C1.1]. 
knit + f51 1 ;knit loops: [881 on yarn C1.1]. 
knit + f54 1 ;knit loops: [882 on yarn C1.1]. 
knit + f57 1 ;knit loops: [883 on yarn C1.1]. 
knit + f60 1 ;knit loops: [884 on yarn C1.1]. 
knit + f63 1 ;knit loops: [885 on yarn C1.1]. 
knit + f66 1 ;knit loops: [886 on yarn C1.1]. 
knit + f69 1 ;knit loops: [887 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {816 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {817 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {818 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {819 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {820 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {821 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {822 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {823 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {824 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {825 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {826 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {827 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {828 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {829 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {830 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {831 on yarn C2.2} on b46 to f46
knit - f70 2 ;knit loops: [888 on yarn C2.2]. 
knit - f67 2 ;knit loops: [889 on yarn C2.2]. 
knit - f64 2 ;knit loops: [890 on yarn C2.2]. 
knit - f61 2 ;knit loops: [891 on yarn C2.2]. 
knit - f58 2 ;knit loops: [892 on yarn C2.2]. 
knit - f55 2 ;knit loops: [893 on yarn C2.2]. 
knit - f52 2 ;knit loops: [894 on yarn C2.2]. 
knit - f49 2 ;knit loops: [895 on yarn C2.2]. 
knit - f46 2 ;knit loops: [896 on yarn C2.2]. 
knit - f43 2 ;knit loops: [897 on yarn C2.2]. 
knit - f40 2 ;knit loops: [898 on yarn C2.2]. 
knit - f37 2 ;knit loops: [899 on yarn C2.2]. 
knit - f34 2 ;knit loops: [900 on yarn C2.2]. 
knit - f31 2 ;knit loops: [901 on yarn C2.2]. 
knit - f28 2 ;knit loops: [902 on yarn C2.2]. 
knit - f25 2 ;knit loops: [903 on yarn C2.2]. 
knit - f22 2 ;knit loops: [904 on yarn C2.2]. 
knit - f19 2 ;knit loops: [905 on yarn C2.2]. 
knit - f16 2 ;knit loops: [906 on yarn C2.2]. 
knit - f13 2 ;knit loops: [907 on yarn C2.2]. 
knit - f10 2 ;knit loops: [908 on yarn C2.2]. 
knit - f7 2 ;knit loops: [909 on yarn C2.2]. 
knit - f4 2 ;knit loops: [910 on yarn C2.2]. 
knit - f1 2 ;knit loops: [911 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {863 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {862 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {861 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {860 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {859 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {858 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {857 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {856 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {847 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {846 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {845 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {844 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {843 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {842 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {841 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {840 on yarn C3.3} on b71 to f71
knit + f2 3 ;knit loops: [912 on yarn C3.3]. 
knit + f5 3 ;knit loops: [913 on yarn C3.3]. 
knit + f8 3 ;knit loops: [914 on yarn C3.3]. 
knit + f11 3 ;knit loops: [915 on yarn C3.3]. 
knit + f14 3 ;knit loops: [916 on yarn C3.3]. 
knit + f17 3 ;knit loops: [917 on yarn C3.3]. 
knit + f20 3 ;knit loops: [918 on yarn C3.3]. 
knit + f23 3 ;knit loops: [919 on yarn C3.3]. 
knit + f26 3 ;knit loops: [920 on yarn C3.3]. 
knit + f29 3 ;knit loops: [921 on yarn C3.3]. 
knit + f32 3 ;knit loops: [922 on yarn C3.3]. 
knit + f35 3 ;knit loops: [923 on yarn C3.3]. 
knit + f38 3 ;knit loops: [924 on yarn C3.3]. 
knit + f41 3 ;knit loops: [925 on yarn C3.3]. 
knit + f44 3 ;knit loops: [926 on yarn C3.3]. 
knit + f47 3 ;knit loops: [927 on yarn C3.3]. 
knit + f50 3 ;knit loops: [928 on yarn C3.3]. 
knit + f53 3 ;knit loops: [929 on yarn C3.3]. 
knit + f56 3 ;knit loops: [930 on yarn C3.3]. 
knit + f59 3 ;knit loops: [931 on yarn C3.3]. 
knit + f62 3 ;knit loops: [932 on yarn C3.3]. 
knit + f65 3 ;knit loops: [933 on yarn C3.3]. 
knit + f68 3 ;knit loops: [934 on yarn C3.3]. 
knit + f71 3 ;knit loops: [935 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {872 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {873 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {874 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {875 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {876 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {877 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {878 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {879 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {880 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {881 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {882 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {883 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {884 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {885 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {886 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {887 on yarn C1.1} on b69 to f69
knit - f69 1 ;knit loops: [936 on yarn C1.1]. 
knit - f66 1 ;knit loops: [937 on yarn C1.1]. 
knit - f63 1 ;knit loops: [938 on yarn C1.1]. 
knit - f60 1 ;knit loops: [939 on yarn C1.1]. 
knit - f57 1 ;knit loops: [940 on yarn C1.1]. 
knit - f54 1 ;knit loops: [941 on yarn C1.1]. 
knit - f51 1 ;knit loops: [942 on yarn C1.1]. 
knit - f48 1 ;knit loops: [943 on yarn C1.1]. 
knit - f45 1 ;knit loops: [944 on yarn C1.1]. 
knit - f42 1 ;knit loops: [945 on yarn C1.1]. 
knit - f39 1 ;knit loops: [946 on yarn C1.1]. 
knit - f36 1 ;knit loops: [947 on yarn C1.1]. 
knit - f33 1 ;knit loops: [948 on yarn C1.1]. 
knit - f30 1 ;knit loops: [949 on yarn C1.1]. 
knit - f27 1 ;knit loops: [950 on yarn C1.1]. 
knit - f24 1 ;knit loops: [951 on yarn C1.1]. 
knit - f21 1 ;knit loops: [952 on yarn C1.1]. 
knit - f18 1 ;knit loops: [953 on yarn C1.1]. 
knit - f15 1 ;knit loops: [954 on yarn C1.1]. 
knit - f12 1 ;knit loops: [955 on yarn C1.1]. 
knit - f9 1 ;knit loops: [956 on yarn C1.1]. 
knit - f6 1 ;knit loops: [957 on yarn C1.1]. 
knit - f3 1 ;knit loops: [958 on yarn C1.1]. 
knit - f0 1 ;knit loops: [959 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {911 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {910 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {909 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {908 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {907 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {906 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {905 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {904 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {903 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {902 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {901 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {900 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {899 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {898 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {897 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {896 on yarn C2.2} on b46 to f46
knit + f1 2 ;knit loops: [960 on yarn C2.2]. 
knit + f4 2 ;knit loops: [961 on yarn C2.2]. 
knit + f7 2 ;knit loops: [962 on yarn C2.2]. 
knit + f10 2 ;knit loops: [963 on yarn C2.2]. 
knit + f13 2 ;knit loops: [964 on yarn C2.2]. 
knit + f16 2 ;knit loops: [965 on yarn C2.2]. 
knit + f19 2 ;knit loops: [966 on yarn C2.2]. 
knit + f22 2 ;knit loops: [967 on yarn C2.2]. 
knit + f25 2 ;knit loops: [968 on yarn C2.2]. 
knit + f28 2 ;knit loops: [969 on yarn C2.2]. 
knit + f31 2 ;knit loops: [970 on yarn C2.2]. 
knit + f34 2 ;knit loops: [971 on yarn C2.2]. 
knit + f37 2 ;knit loops: [972 on yarn C2.2]. 
knit + f40 2 ;knit loops: [973 on yarn C2.2]. 
knit + f43 2 ;knit loops: [974 on yarn C2.2]. 
knit + f46 2 ;knit loops: [975 on yarn C2.2]. 
knit + f49 2 ;knit loops: [976 on yarn C2.2]. 
knit + f52 2 ;knit loops: [977 on yarn C2.2]. 
knit + f55 2 ;knit loops: [978 on yarn C2.2]. 
knit + f58 2 ;knit loops: [979 on yarn C2.2]. 
knit + f61 2 ;knit loops: [980 on yarn C2.2]. 
knit + f64 2 ;knit loops: [981 on yarn C2.2]. 
knit + f67 2 ;knit loops: [982 on yarn C2.2]. 
knit + f70 2 ;knit loops: [983 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {912 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {913 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {914 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {915 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {916 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {917 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {918 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {919 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {928 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {929 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {930 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {931 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {932 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {933 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {934 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {935 on yarn C3.3} on b71 to f71
knit - f71 3 ;knit loops: [984 on yarn C3.3]. 
knit - f68 3 ;knit loops: [985 on yarn C3.3]. 
knit - f65 3 ;knit loops: [986 on yarn C3.3]. 
knit - f62 3 ;knit loops: [987 on yarn C3.3]. 
knit - f59 3 ;knit loops: [988 on yarn C3.3]. 
knit - f56 3 ;knit loops: [989 on yarn C3.3]. 
knit - f53 3 ;knit loops: [990 on yarn C3.3]. 
knit - f50 3 ;knit loops: [991 on yarn C3.3]. 
knit - f47 3 ;knit loops: [992 on yarn C3.3]. 
knit - f44 3 ;knit loops: [993 on yarn C3.3]. 
knit - f41 3 ;knit loops: [994 on yarn C3.3]. 
knit - f38 3 ;knit loops: [995 on yarn C3.3]. 
knit - f35 3 ;knit loops: [996 on yarn C3.3]. 
knit - f32 3 ;knit loops: [997 on yarn C3.3]. 
knit - f29 3 ;knit loops: [998 on yarn C3.3]. 
knit - f26 3 ;knit loops: [999 on yarn C3.3]. 
knit - f23 3 ;knit loops: [1000 on yarn C3.3]. 
knit - f20 3 ;knit loops: [1001 on yarn C3.3]. 
knit - f17 3 ;knit loops: [1002 on yarn C3.3]. 
knit - f14 3 ;knit loops: [1003 on yarn C3.3]. 
knit - f11 3 ;knit loops: [1004 on yarn C3.3]. 
knit - f8 3 ;knit loops: [1005 on yarn C3.3]. 
knit - f5 3 ;knit loops: [1006 on yarn C3.3]. 
knit - f2 3 ;knit loops: [1007 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {951 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {950 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {949 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {948 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {947 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {946 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {945 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {944 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {943 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {942 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {941 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {940 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {939 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {938 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {937 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {936 on yarn C1.1} on b69 to f69
knit + f0 1 ;knit loops: [1008 on yarn C1.1]. 
knit + f3 1 ;knit loops: [1009 on yarn C1.1]. 
knit + f6 1 ;knit loops: [1010 on yarn C1.1]. 
knit + f9 1 ;knit loops: [1011 on yarn C1.1]. 
knit + f12 1 ;knit loops: [1012 on yarn C1.1]. 
knit + f15 1 ;knit loops: [1013 on yarn C1.1]. 
knit + f18 1 ;knit loops: [1014 on yarn C1.1]. 
knit + f21 1 ;knit loops: [1015 on yarn C1.1]. 
knit + f24 1 ;knit loops: [1016 on yarn C1.1]. 
knit + f27 1 ;knit loops: [1017 on yarn C1.1]. 
knit + f30 1 ;knit loops: [1018 on yarn C1.1]. 
knit + f33 1 ;knit loops: [1019 on yarn C1.1]. 
knit + f36 1 ;knit loops: [1020 on yarn C1.1]. 
knit + f39 1 ;knit loops: [1021 on yarn C1.1]. 
knit + f42 1 ;knit loops: [1022 on yarn C1.1]. 
knit + f45 1 ;knit loops: [1023 on yarn C1.1]. 
knit + f48 1 ;knit loops: [1024 on yarn C1.1]. 
knit + f51 1 ;knit loops: [1025 on yarn C1.1]. 
knit + f54 1 ;knit loops: [1026 on yarn C1.1]. 
knit + f57 1 ;knit loops: [1027 on yarn C1.1]. 
knit + f60 1 ;knit loops: [1028 on yarn C1.1]. 
knit + f63 1 ;knit loops: [1029 on yarn C1.1]. 
knit + f66 1 ;knit loops: [1030 on yarn C1.1]. 
knit + f69 1 ;knit loops: [1031 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {960 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {961 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {962 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {963 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {964 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {965 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {966 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {967 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {968 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {969 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {970 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {971 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {972 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {973 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {974 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {975 on yarn C2.2} on b46 to f46
knit - f70 2 ;knit loops: [1032 on yarn C2.2]. 
knit - f67 2 ;knit loops: [1033 on yarn C2.2]. 
knit - f64 2 ;knit loops: [1034 on yarn C2.2]. 
knit - f61 2 ;knit loops: [1035 on yarn C2.2]. 
knit - f58 2 ;knit loops: [1036 on yarn C2.2]. 
knit - f55 2 ;knit loops: [1037 on yarn C2.2]. 
knit - f52 2 ;knit loops: [1038 on yarn C2.2]. 
knit - f49 2 ;knit loops: [1039 on yarn C2.2]. 
knit - f46 2 ;knit loops: [1040 on yarn C2.2]. 
knit - f43 2 ;knit loops: [1041 on yarn C2.2]. 
knit - f40 2 ;knit loops: [1042 on yarn C2.2]. 
knit - f37 2 ;knit loops: [1043 on yarn C2.2]. 
knit - f34 2 ;knit loops: [1044 on yarn C2.2]. 
knit - f31 2 ;knit loops: [1045 on yarn C2.2]. 
knit - f28 2 ;knit loops: [1046 on yarn C2.2]. 
knit - f25 2 ;knit loops: [1047 on yarn C2.2]. 
knit - f22 2 ;knit loops: [1048 on yarn C2.2]. 
knit - f19 2 ;knit loops: [1049 on yarn C2.2]. 
knit - f16 2 ;knit loops: [1050 on yarn C2.2]. 
knit - f13 2 ;knit loops: [1051 on yarn C2.2]. 
knit - f10 2 ;knit loops: [1052 on yarn C2.2]. 
knit - f7 2 ;knit loops: [1053 on yarn C2.2]. 
knit - f4 2 ;knit loops: [1054 on yarn C2.2]. 
knit - f1 2 ;knit loops: [1055 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {1007 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {1006 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {1005 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {1004 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {1003 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {1002 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {1001 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {1000 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {991 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {990 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {989 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {988 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {987 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {986 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {985 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {984 on yarn C3.3} on b71 to f71
knit + f2 3 ;knit loops: [1056 on yarn C3.3]. 
knit + f5 3 ;knit loops: [1057 on yarn C3.3]. 
knit + f8 3 ;knit loops: [1058 on yarn C3.3]. 
knit + f11 3 ;knit loops: [1059 on yarn C3.3]. 
knit + f14 3 ;knit loops: [1060 on yarn C3.3]. 
knit + f17 3 ;knit loops: [1061 on yarn C3.3]. 
knit + f20 3 ;knit loops: [1062 on yarn C3.3]. 
knit + f23 3 ;knit loops: [1063 on yarn C3.3]. 
knit + f26 3 ;knit loops: [1064 on yarn C3.3]. 
knit + f29 3 ;knit loops: [1065 on yarn C3.3]. 
knit + f32 3 ;knit loops: [1066 on yarn C3.3]. 
knit + f35 3 ;knit loops: [1067 on yarn C3.3]. 
knit + f38 3 ;knit loops: [1068 on yarn C3.3]. 
knit + f41 3 ;knit loops: [1069 on yarn C3.3]. 
knit + f44 3 ;knit loops: [1070 on yarn C3.3]. 
knit + f47 3 ;knit loops: [1071 on yarn C3.3]. 
knit + f50 3 ;knit loops: [1072 on yarn C3.3]. 
knit + f53 3 ;knit loops: [1073 on yarn C3.3]. 
knit + f56 3 ;knit loops: [1074 on yarn C3.3]. 
knit + f59 3 ;knit loops: [1075 on yarn C3.3]. 
knit + f62 3 ;knit loops: [1076 on yarn C3.3]. 
knit + f65 3 ;knit loops: [1077 on yarn C3.3]. 
knit + f68 3 ;knit loops: [1078 on yarn C3.3]. 
knit + f71 3 ;knit loops: [1079 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {1016 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {1017 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {1018 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {1019 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {1020 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {1021 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {1022 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {1023 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {1024 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {1025 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {1026 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {1027 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {1028 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {1029 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {1030 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {1031 on yarn C1.1} on b69 to f69
knit - f69 1 ;knit loops: [1080 on yarn C1.1]. 
knit - f66 1 ;knit loops: [1081 on yarn C1.1]. 
knit - f63 1 ;knit loops: [1082 on yarn C1.1]. 
knit - f60 1 ;knit loops: [1083 on yarn C1.1]. 
knit - f57 1 ;knit loops: [1084 on yarn C1.1]. 
knit - f54 1 ;knit loops: [1085 on yarn C1.1]. 
knit - f51 1 ;knit loops: [1086 on yarn C1.1]. 
knit - f48 1 ;knit loops: [1087 on yarn C1.1]. 
knit - f45 1 ;knit loops: [1088 on yarn C1.1]. 
knit - f42 1 ;knit loops: [1089 on yarn C1.1]. 
knit - f39 1 ;knit loops: [1090 on yarn C1.1]. 
knit - f36 1 ;knit loops: [1091 on yarn C1.1]. 
knit - f33 1 ;knit loops: [1092 on yarn C1.1]. 
knit - f30 1 ;knit loops: [1093 on yarn C1.1]. 
knit - f27 1 ;knit loops: [1094 on yarn C1.1]. 
knit - f24 1 ;knit loops: [1095 on yarn C1.1]. 
knit - f21 1 ;knit loops: [1096 on yarn C1.1]. 
knit - f18 1 ;knit loops: [1097 on yarn C1.1]. 
knit - f15 1 ;knit loops: [1098 on yarn C1.1]. 
knit - f12 1 ;knit loops: [1099 on yarn C1.1]. 
knit - f9 1 ;knit loops: [1100 on yarn C1.1]. 
knit - f6 1 ;knit loops: [1101 on yarn C1.1]. 
knit - f3 1 ;knit loops: [1102 on yarn C1.1]. 
knit - f0 1 ;knit loops: [1103 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {1055 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {1054 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {1053 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {1052 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {1051 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {1050 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {1049 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {1048 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {1047 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {1046 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {1045 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {1044 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {1043 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {1042 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {1041 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {1040 on yarn C2.2} on b46 to f46
knit + f1 2 ;knit loops: [1104 on yarn C2.2]. 
knit + f4 2 ;knit loops: [1105 on yarn C2.2]. 
knit + f7 2 ;knit loops: [1106 on yarn C2.2]. 
knit + f10 2 ;knit loops: [1107 on yarn C2.2]. 
knit + f13 2 ;knit loops: [1108 on yarn C2.2]. 
knit + f16 2 ;knit loops: [1109 on yarn C2.2]. 
knit + f19 2 ;knit loops: [1110 on yarn C2.2]. 
knit + f22 2 ;knit loops: [1111 on yarn C2.2]. 
knit + f25 2 ;knit loops: [1112 on yarn C2.2]. 
knit + f28 2 ;knit loops: [1113 on yarn C2.2]. 
knit + f31 2 ;knit loops: [1114 on yarn C2.2]. 
knit + f34 2 ;knit loops: [1115 on yarn C2.2]. 
knit + f37 2 ;knit loops: [1116 on yarn C2.2]. 
knit + f40 2 ;knit loops: [1117 on yarn C2.2]. 
knit + f43 2 ;knit loops: [1118 on yarn C2.2]. 
knit + f46 2 ;knit loops: [1119 on yarn C2.2]. 
knit + f49 2 ;knit loops: [1120 on yarn C2.2]. 
knit + f52 2 ;knit loops: [1121 on yarn C2.2]. 
knit + f55 2 ;knit loops: [1122 on yarn C2.2]. 
knit + f58 2 ;knit loops: [1123 on yarn C2.2]. 
knit + f61 2 ;knit loops: [1124 on yarn C2.2]. 
knit + f64 2 ;knit loops: [1125 on yarn C2.2]. 
knit + f67 2 ;knit loops: [1126 on yarn C2.2]. 
knit + f70 2 ;knit loops: [1127 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {1056 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {1057 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {1058 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {1059 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {1060 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {1061 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {1062 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {1063 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {1072 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {1073 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {1074 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {1075 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {1076 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {1077 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {1078 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {1079 on yarn C3.3} on b71 to f71
knit - f71 3 ;knit loops: [1128 on yarn C3.3]. 
knit - f68 3 ;knit loops: [1129 on yarn C3.3]. 
knit - f65 3 ;knit loops: [1130 on yarn C3.3]. 
knit - f62 3 ;knit loops: [1131 on yarn C3.3]. 
knit - f59 3 ;knit loops: [1132 on yarn C3.3]. 
knit - f56 3 ;knit loops: [1133 on yarn C3.3]. 
knit - f53 3 ;knit loops: [1134 on yarn C3.3]. 
knit - f50 3 ;knit loops: [1135 on yarn C3.3]. 
knit - f47 3 ;knit loops: [1136 on yarn C3.3]. 
knit - f44 3 ;knit loops: [1137 on yarn C3.3]. 
knit - f41 3 ;knit loops: [1138 on yarn C3.3]. 
knit - f38 3 ;knit loops: [1139 on yarn C3.3]. 
knit - f35 3 ;knit loops: [1140 on yarn C3.3]. 
knit - f32 3 ;knit loops: [1141 on yarn C3.3]. 
knit - f29 3 ;knit loops: [1142 on yarn C3.3]. 
knit - f26 3 ;knit loops: [1143 on yarn C3.3]. 
knit - f23 3 ;knit loops: [1144 on yarn C3.3]. 
knit - f20 3 ;knit loops: [1145 on yarn C3.3]. 
knit - f17 3 ;knit loops: [1146 on yarn C3.3]. 
knit - f14 3 ;knit loops: [1147 on yarn C3.3]. 
knit - f11 3 ;knit loops: [1148 on yarn C3.3]. 
knit - f8 3 ;knit loops: [1149 on yarn C3.3]. 
knit - f5 3 ;knit loops: [1150 on yarn C3.3]. 
knit - f2 3 ;knit loops: [1151 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {1095 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {1094 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {1093 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {1092 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {1091 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {1090 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {1089 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {1088 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {1087 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {1086 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {1085 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {1084 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {1083 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {1082 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {1081 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {1080 on yarn C1.1} on b69 to f69
knit + f0 1 ;knit loops: [1152 on yarn C1.1]. 
knit + f3 1 ;knit loops: [1153 on yarn C1.1]. 
knit + f6 1 ;knit loops: [1154 on yarn C1.1]. 
knit + f9 1 ;knit loops: [1155 on yarn C1.1]. 
knit + f12 1 ;knit loops: [1156 on yarn C1.1]. 
knit + f15 1 ;knit loops: [1157 on yarn C1.1]. 
knit + f18 1 ;knit loops: [1158 on yarn C1.1]. 
knit + f21 1 ;knit loops: [1159 on yarn C1.1]. 
knit + f24 1 ;knit loops: [1160 on yarn C1.1]. 
knit + f27 1 ;knit loops: [1161 on yarn C1.1]. 
knit + f30 1 ;knit loops: [1162 on yarn C1.1]. 
knit + f33 1 ;knit loops: [1163 on yarn C1.1]. 
knit + f36 1 ;knit loops: [1164 on yarn C1.1]. 
knit + f39 1 ;knit loops: [1165 on yarn C1.1]. 
knit + f42 1 ;knit loops: [1166 on yarn C1.1]. 
knit + f45 1 ;knit loops: [1167 on yarn C1.1]. 
knit + f48 1 ;knit loops: [1168 on yarn C1.1]. 
knit + f51 1 ;knit loops: [1169 on yarn C1.1]. 
knit + f54 1 ;knit loops: [1170 on yarn C1.1]. 
knit + f57 1 ;knit loops: [1171 on yarn C1.1]. 
knit + f60 1 ;knit loops: [1172 on yarn C1.1]. 
knit + f63 1 ;knit loops: [1173 on yarn C1.1]. 
knit + f66 1 ;knit loops: [1174 on yarn C1.1]. 
knit + f69 1 ;knit loops: [1175 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {1104 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {1105 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {1106 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {1107 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {1108 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {1109 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {1110 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {1111 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {1112 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {1113 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {1114 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {1115 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {1116 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {1117 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {1118 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {1119 on yarn C2.2} on b46 to f46
knit - f70 2 ;knit loops: [1176 on yarn C2.2]. 
knit - f67 2 ;knit loops: [1177 on yarn C2.2]. 
knit - f64 2 ;knit loops: [1178 on yarn C2.2]. 
knit - f61 2 ;knit loops: [1179 on yarn C2.2]. 
knit - f58 2 ;knit loops: [1180 on yarn C2.2]. 
knit - f55 2 ;knit loops: [1181 on yarn C2.2]. 
knit - f52 2 ;knit loops: [1182 on yarn C2.2]. 
knit - f49 2 ;knit loops: [1183 on yarn C2.2]. 
knit - f46 2 ;knit loops: [1184 on yarn C2.2]. 
knit - f43 2 ;knit loops: [1185 on yarn C2.2]. 
knit - f40 2 ;knit loops: [1186 on yarn C2.2]. 
knit - f37 2 ;knit loops: [1187 on yarn C2.2]. 
knit - f34 2 ;knit loops: [1188 on yarn C2.2]. 
knit - f31 2 ;knit loops: [1189 on yarn C2.2]. 
knit - f28 2 ;knit loops: [1190 on yarn C2.2]. 
knit - f25 2 ;knit loops: [1191 on yarn C2.2]. 
knit - f22 2 ;knit loops: [1192 on yarn C2.2]. 
knit - f19 2 ;knit loops: [1193 on yarn C2.2]. 
knit - f16 2 ;knit loops: [1194 on yarn C2.2]. 
knit - f13 2 ;knit loops: [1195 on yarn C2.2]. 
knit - f10 2 ;knit loops: [1196 on yarn C2.2]. 
knit - f7 2 ;knit loops: [1197 on yarn C2.2]. 
knit - f4 2 ;knit loops: [1198 on yarn C2.2]. 
knit - f1 2 ;knit loops: [1199 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {1151 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {1150 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {1149 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {1148 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {1147 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {1146 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {1145 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {1144 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {1135 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {1134 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {1133 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {1132 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {1131 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {1130 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {1129 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {1128 on yarn C3.3} on b71 to f71
knit + f2 3 ;knit loops: [1200 on yarn C3.3]. 
knit + f5 3 ;knit loops: [1201 on yarn C3.3]. 
knit + f8 3 ;knit loops: [1202 on yarn C3.3]. 
knit + f11 3 ;knit loops: [1203 on yarn C3.3]. 
knit + f14 3 ;knit loops: [1204 on yarn C3.3]. 
knit + f17 3 ;knit loops: [1205 on yarn C3.3]. 
knit + f20 3 ;knit loops: [1206 on yarn C3.3]. 
knit + f23 3 ;knit loops: [1207 on yarn C3.3]. 
knit + f26 3 ;knit loops: [1208 on yarn C3.3]. 
knit + f29 3 ;knit loops: [1209 on yarn C3.3]. 
knit + f32 3 ;knit loops: [1210 on yarn C3.3]. 
knit + f35 3 ;knit loops: [1211 on yarn C3.3]. 
knit + f38 3 ;knit loops: [1212 on yarn C3.3]. 
knit + f41 3 ;knit loops: [1213 on yarn C3.3]. 
knit + f44 3 ;knit loops: [1214 on yarn C3.3]. 
knit + f47 3 ;knit loops: [1215 on yarn C3.3]. 
knit + f50 3 ;knit loops: [1216 on yarn C3.3]. 
knit + f53 3 ;knit loops: [1217 on yarn C3.3]. 
knit + f56 3 ;knit loops: [1218 on yarn C3.3]. 
knit + f59 3 ;knit loops: [1219 on yarn C3.3]. 
knit + f62 3 ;knit loops: [1220 on yarn C3.3]. 
knit + f65 3 ;knit loops: [1221 on yarn C3.3]. 
knit + f68 3 ;knit loops: [1222 on yarn C3.3]. 
knit + f71 3 ;knit loops: [1223 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {1160 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {1161 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {1162 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {1163 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {1164 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {1165 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {1166 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {1167 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {1168 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {1169 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {1170 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {1171 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {1172 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {1173 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {1174 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {1175 on yarn C1.1} on b69 to f69
knit - f69 1 ;knit loops: [1224 on yarn C1.1]. 
knit - f66 1 ;knit loops: [1225 on yarn C1.1]. 
knit - f63 1 ;knit loops: [1226 on yarn C1.1]. 
knit - f60 1 ;knit loops: [1227 on yarn C1.1]. 
knit - f57 1 ;knit loops: [1228 on yarn C1.1]. 
knit - f54 1 ;knit loops: [1229 on yarn C1.1]. 
knit - f51 1 ;knit loops: [1230 on yarn C1.1]. 
knit - f48 1 ;knit loops: [1231 on yarn C1.1]. 
knit - f45 1 ;knit loops: [1232 on yarn C1.1]. 
knit - f42 1 ;knit loops: [1233 on yarn C1.1]. 
knit - f39 1 ;knit loops: [1234 on yarn C1.1]. 
knit - f36 1 ;knit loops: [1235 on yarn C1.1]. 
knit - f33 1 ;knit loops: [1236 on yarn C1.1]. 
knit - f30 1 ;knit loops: [1237 on yarn C1.1]. 
knit - f27 1 ;knit loops: [1238 on yarn C1.1]. 
knit - f24 1 ;knit loops: [1239 on yarn C1.1]. 
knit - f21 1 ;knit loops: [1240 on yarn C1.1]. 
knit - f18 1 ;knit loops: [1241 on yarn C1.1]. 
knit - f15 1 ;knit loops: [1242 on yarn C1.1]. 
knit - f12 1 ;knit loops: [1243 on yarn C1.1]. 
knit - f9 1 ;knit loops: [1244 on yarn C1.1]. 
knit - f6 1 ;knit loops: [1245 on yarn C1.1]. 
knit - f3 1 ;knit loops: [1246 on yarn C1.1]. 
knit - f0 1 ;knit loops: [1247 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {1199 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {1198 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {1197 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {1196 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {1195 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {1194 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {1193 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {1192 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {1191 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {1190 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {1189 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {1188 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {1187 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {1186 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {1185 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {1184 on yarn C2.2} on b46 to f46
knit + f1 2 ;knit loops: [1248 on yarn C2.2]. 
knit + f4 2 ;knit loops: [1249 on yarn C2.2]. 
knit + f7 2 ;knit loops: [1250 on yarn C2.2]. 
knit + f10 2 ;knit loops: [1251 on yarn C2.2]. 
knit + f13 2 ;knit loops: [1252 on yarn C2.2]. 
knit + f16 2 ;knit loops: [1253 on yarn C2.2]. 
knit + f19 2 ;knit loops: [1254 on yarn C2.2]. 
knit + f22 2 ;knit loops: [1255 on yarn C2.2]. 
knit + f25 2 ;knit loops: [1256 on yarn C2.2]. 
knit + f28 2 ;knit loops: [1257 on yarn C2.2]. 
knit + f31 2 ;knit loops: [1258 on yarn C2.2]. 
knit + f34 2 ;knit loops: [1259 on yarn C2.2]. 
knit + f37 2 ;knit loops: [1260 on yarn C2.2]. 
knit + f40 2 ;knit loops: [1261 on yarn C2.2]. 
knit + f43 2 ;knit loops: [1262 on yarn C2.2]. 
knit + f46 2 ;knit loops: [1263 on yarn C2.2]. 
knit + f49 2 ;knit loops: [1264 on yarn C2.2]. 
knit + f52 2 ;knit loops: [1265 on yarn C2.2]. 
knit + f55 2 ;knit loops: [1266 on yarn C2.2]. 
knit + f58 2 ;knit loops: [1267 on yarn C2.2]. 
knit + f61 2 ;knit loops: [1268 on yarn C2.2]. 
knit + f64 2 ;knit loops: [1269 on yarn C2.2]. 
knit + f67 2 ;knit loops: [1270 on yarn C2.2]. 
knit + f70 2 ;knit loops: [1271 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {1200 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {1201 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {1202 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {1203 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {1204 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {1205 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {1206 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {1207 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {1216 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {1217 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {1218 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {1219 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {1220 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {1221 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {1222 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {1223 on yarn C3.3} on b71 to f71
knit - f71 3 ;knit loops: [1272 on yarn C3.3]. 
knit - f68 3 ;knit loops: [1273 on yarn C3.3]. 
knit - f65 3 ;knit loops: [1274 on yarn C3.3]. 
knit - f62 3 ;knit loops: [1275 on yarn C3.3]. 
knit - f59 3 ;knit loops: [1276 on yarn C3.3]. 
knit - f56 3 ;knit loops: [1277 on yarn C3.3]. 
knit - f53 3 ;knit loops: [1278 on yarn C3.3]. 
knit - f50 3 ;knit loops: [1279 on yarn C3.3]. 
knit - f47 3 ;knit loops: [1280 on yarn C3.3]. 
knit - f44 3 ;knit loops: [1281 on yarn C3.3]. 
knit - f41 3 ;knit loops: [1282 on yarn C3.3]. 
knit - f38 3 ;knit loops: [1283 on yarn C3.3]. 
knit - f35 3 ;knit loops: [1284 on yarn C3.3]. 
knit - f32 3 ;knit loops: [1285 on yarn C3.3]. 
knit - f29 3 ;knit loops: [1286 on yarn C3.3]. 
knit - f26 3 ;knit loops: [1287 on yarn C3.3]. 
knit - f23 3 ;knit loops: [1288 on yarn C3.3]. 
knit - f20 3 ;knit loops: [1289 on yarn C3.3]. 
knit - f17 3 ;knit loops: [1290 on yarn C3.3]. 
knit - f14 3 ;knit loops: [1291 on yarn C3.3]. 
knit - f11 3 ;knit loops: [1292 on yarn C3.3]. 
knit - f8 3 ;knit loops: [1293 on yarn C3.3]. 
knit - f5 3 ;knit loops: [1294 on yarn C3.3]. 
knit - f2 3 ;knit loops: [1295 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {1239 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {1238 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {1237 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {1236 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {1235 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {1234 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {1233 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {1232 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {1231 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {1230 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {1229 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {1228 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {1227 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {1226 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {1225 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {1224 on yarn C1.1} on b69 to f69
knit + f0 1 ;knit loops: [1296 on yarn C1.1]. 
knit + f3 1 ;knit loops: [1297 on yarn C1.1]. 
knit + f6 1 ;knit loops: [1298 on yarn C1.1]. 
knit + f9 1 ;knit loops: [1299 on yarn C1.1]. 
knit + f12 1 ;knit loops: [1300 on yarn C1.1]. 
knit + f15 1 ;knit loops: [1301 on yarn C1.1]. 
knit + f18 1 ;knit loops: [1302 on yarn C1.1]. 
knit + f21 1 ;knit loops: [1303 on yarn C1.1]. 
knit + f24 1 ;knit loops: [1304 on yarn C1.1]. 
knit + f27 1 ;knit loops: [1305 on yarn C1.1]. 
knit + f30 1 ;knit loops: [1306 on yarn C1.1]. 
knit + f33 1 ;knit loops: [1307 on yarn C1.1]. 
knit + f36 1 ;knit loops: [1308 on yarn C1.1]. 
knit + f39 1 ;knit loops: [1309 on yarn C1.1]. 
knit + f42 1 ;knit loops: [1310 on yarn C1.1]. 
knit + f45 1 ;knit loops: [1311 on yarn C1.1]. 
knit + f48 1 ;knit loops: [1312 on yarn C1.1]. 
knit + f51 1 ;knit loops: [1313 on yarn C1.1]. 
knit + f54 1 ;knit loops: [1314 on yarn C1.1]. 
knit + f57 1 ;knit loops: [1315 on yarn C1.1]. 
knit + f60 1 ;knit loops: [1316 on yarn C1.1]. 
knit + f63 1 ;knit loops: [1317 on yarn C1.1]. 
knit + f66 1 ;knit loops: [1318 on yarn C1.1]. 
knit + f69 1 ;knit loops: [1319 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {1248 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {1249 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {1250 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {1251 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {1252 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {1253 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {1254 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {1255 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {1256 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {1257 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {1258 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {1259 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {1260 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {1261 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {1262 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {1263 on yarn C2.2} on b46 to f46
knit - f70 2 ;knit loops: [1320 on yarn C2.2]. 
knit - f67 2 ;knit loops: [1321 on yarn C2.2]. 
knit - f64 2 ;knit loops: [1322 on yarn C2.2]. 
knit - f61 2 ;knit loops: [1323 on yarn C2.2]. 
knit - f58 2 ;knit loops: [1324 on yarn C2.2]. 
knit - f55 2 ;knit loops: [1325 on yarn C2.2]. 
knit - f52 2 ;knit loops: [1326 on yarn C2.2]. 
knit - f49 2 ;knit loops: [1327 on yarn C2.2]. 
knit - f46 2 ;knit loops: [1328 on yarn C2.2]. 
knit - f43 2 ;knit loops: [1329 on yarn C2.2]. 
knit - f40 2 ;knit loops: [1330 on yarn C2.2]. 
knit - f37 2 ;knit loops: [1331 on yarn C2.2]. 
knit - f34 2 ;knit loops: [1332 on yarn C2.2]. 
knit - f31 2 ;knit loops: [1333 on yarn C2.2]. 
knit - f28 2 ;knit loops: [1334 on yarn C2.2]. 
knit - f25 2 ;knit loops: [1335 on yarn C2.2]. 
knit - f22 2 ;knit loops: [1336 on yarn C2.2]. 
knit - f19 2 ;knit loops: [1337 on yarn C2.2]. 
knit - f16 2 ;knit loops: [1338 on yarn C2.2]. 
knit - f13 2 ;knit loops: [1339 on yarn C2.2]. 
knit - f10 2 ;knit loops: [1340 on yarn C2.2]. 
knit - f7 2 ;knit loops: [1341 on yarn C2.2]. 
knit - f4 2 ;knit loops: [1342 on yarn C2.2]. 
knit - f1 2 ;knit loops: [1343 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {1295 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {1294 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {1293 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {1292 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {1291 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {1290 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {1289 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {1288 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {1279 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {1278 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {1277 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {1276 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {1275 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {1274 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {1273 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {1272 on yarn C3.3} on b71 to f71
knit + f2 3 ;knit loops: [1344 on yarn C3.3]. 
knit + f5 3 ;knit loops: [1345 on yarn C3.3]. 
knit + f8 3 ;knit loops: [1346 on yarn C3.3]. 
knit + f11 3 ;knit loops: [1347 on yarn C3.3]. 
knit + f14 3 ;knit loops: [1348 on yarn C3.3]. 
knit + f17 3 ;knit loops: [1349 on yarn C3.3]. 
knit + f20 3 ;knit loops: [1350 on yarn C3.3]. 
knit + f23 3 ;knit loops: [1351 on yarn C3.3]. 
knit + f26 3 ;knit loops: [1352 on yarn C3.3]. 
knit + f29 3 ;knit loops: [1353 on yarn C3.3]. 
knit + f32 3 ;knit loops: [1354 on yarn C3.3]. 
knit + f35 3 ;knit loops: [1355 on yarn C3.3]. 
knit + f38 3 ;knit loops: [1356 on yarn C3.3]. 
knit + f41 3 ;knit loops: [1357 on yarn C3.3]. 
knit + f44 3 ;knit loops: [1358 on yarn C3.3]. 
knit + f47 3 ;knit loops: [1359 on yarn C3.3]. 
knit + f50 3 ;knit loops: [1360 on yarn C3.3]. 
knit + f53 3 ;knit loops: [1361 on yarn C3.3]. 
knit + f56 3 ;knit loops: [1362 on yarn C3.3]. 
knit + f59 3 ;knit loops: [1363 on yarn C3.3]. 
knit + f62 3 ;knit loops: [1364 on yarn C3.3]. 
knit + f65 3 ;knit loops: [1365 on yarn C3.3]. 
knit + f68 3 ;knit loops: [1366 on yarn C3.3]. 
knit + f71 3 ;knit loops: [1367 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {1304 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {1305 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {1306 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {1307 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {1308 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {1309 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {1310 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {1311 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {1312 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {1313 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {1314 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {1315 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {1316 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {1317 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {1318 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {1319 on yarn C1.1} on b69 to f69
knit - f69 1 ;knit loops: [1368 on yarn C1.1]. 
knit - f66 1 ;knit loops: [1369 on yarn C1.1]. 
knit - f63 1 ;knit loops: [1370 on yarn C1.1]. 
knit - f60 1 ;knit loops: [1371 on yarn C1.1]. 
knit - f57 1 ;knit loops: [1372 on yarn C1.1]. 
knit - f54 1 ;knit loops: [1373 on yarn C1.1]. 
knit - f51 1 ;knit loops: [1374 on yarn C1.1]. 
knit - f48 1 ;knit loops: [1375 on yarn C1.1]. 
knit - f45 1 ;knit loops: [1376 on yarn C1.1]. 
knit - f42 1 ;knit loops: [1377 on yarn C1.1]. 
knit - f39 1 ;knit loops: [1378 on yarn C1.1]. 
knit - f36 1 ;knit loops: [1379 on yarn C1.1]. 
knit - f33 1 ;knit loops: [1380 on yarn C1.1]. 
knit - f30 1 ;knit loops: [1381 on yarn C1.1]. 
knit - f27 1 ;knit loops: [1382 on yarn C1.1]. 
knit - f24 1 ;knit loops: [1383 on yarn C1.1]. 
knit - f21 1 ;knit loops: [1384 on yarn C1.1]. 
knit - f18 1 ;knit loops: [1385 on yarn C1.1]. 
knit - f15 1 ;knit loops: [1386 on yarn C1.1]. 
knit - f12 1 ;knit loops: [1387 on yarn C1.1]. 
knit - f9 1 ;knit loops: [1388 on yarn C1.1]. 
knit - f6 1 ;knit loops: [1389 on yarn C1.1]. 
knit - f3 1 ;knit loops: [1390 on yarn C1.1]. 
knit - f0 1 ;knit loops: [1391 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {1343 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {1342 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {1341 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {1340 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {1339 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {1338 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {1337 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {1336 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {1335 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {1334 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {1333 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {1332 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {1331 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {1330 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {1329 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {1328 on yarn C2.2} on b46 to f46
knit + f1 2 ;knit loops: [1392 on yarn C2.2]. 
knit + f4 2 ;knit loops: [1393 on yarn C2.2]. 
knit + f7 2 ;knit loops: [1394 on yarn C2.2]. 
knit + f10 2 ;knit loops: [1395 on yarn C2.2]. 
knit + f13 2 ;knit loops: [1396 on yarn C2.2]. 
knit + f16 2 ;knit loops: [1397 on yarn C2.2]. 
knit + f19 2 ;knit loops: [1398 on yarn C2.2]. 
knit + f22 2 ;knit loops: [1399 on yarn C2.2]. 
knit + f25 2 ;knit loops: [1400 on yarn C2.2]. 
knit + f28 2 ;knit loops: [1401 on yarn C2.2]. 
knit + f31 2 ;knit loops: [1402 on yarn C2.2]. 
knit + f34 2 ;knit loops: [1403 on yarn C2.2]. 
knit + f37 2 ;knit loops: [1404 on yarn C2.2]. 
knit + f40 2 ;knit loops: [1405 on yarn C2.2]. 
knit + f43 2 ;knit loops: [1406 on yarn C2.2]. 
knit + f46 2 ;knit loops: [1407 on yarn C2.2]. 
knit + f49 2 ;knit loops: [1408 on yarn C2.2]. 
knit + f52 2 ;knit loops: [1409 on yarn C2.2]. 
knit + f55 2 ;knit loops: [1410 on yarn C2.2]. 
knit + f58 2 ;knit loops: [1411 on yarn C2.2]. 
knit + f61 2 ;knit loops: [1412 on yarn C2.2]. 
knit + f64 2 ;knit loops: [1413 on yarn C2.2]. 
knit + f67 2 ;knit loops: [1414 on yarn C2.2]. 
knit + f70 2 ;knit loops: [1415 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {1344 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {1345 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {1346 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {1347 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {1348 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {1349 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {1350 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {1351 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {1360 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {1361 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {1362 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {1363 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {1364 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {1365 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {1366 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {1367 on yarn C3.3} on b71 to f71
knit - f71 3 ;knit loops: [1416 on yarn C3.3]. 
knit - f68 3 ;knit loops: [1417 on yarn C3.3]. 
knit - f65 3 ;knit loops: [1418 on yarn C3.3]. 
knit - f62 3 ;knit loops: [1419 on yarn C3.3]. 
knit - f59 3 ;knit loops: [1420 on yarn C3.3]. 
knit - f56 3 ;knit loops: [1421 on yarn C3.3]. 
knit - f53 3 ;knit loops: [1422 on yarn C3.3]. 
knit - f50 3 ;knit loops: [1423 on yarn C3.3]. 
knit - f47 3 ;knit loops: [1424 on yarn C3.3]. 
knit - f44 3 ;knit loops: [1425 on yarn C3.3]. 
knit - f41 3 ;knit loops: [1426 on yarn C3.3]. 
knit - f38 3 ;knit loops: [1427 on yarn C3.3]. 
knit - f35 3 ;knit loops: [1428 on yarn C3.3]. 
knit - f32 3 ;knit loops: [1429 on yarn C3.3]. 
knit - f29 3 ;knit loops: [1430 on yarn C3.3]. 
knit - f26 3 ;knit loops: [1431 on yarn C3.3]. 
knit - f23 3 ;knit loops: [1432 on yarn C3.3]. 
knit - f20 3 ;knit loops: [1433 on yarn C3.3]. 
knit - f17 3 ;knit loops: [1434 on yarn C3.3]. 
knit - f14 3 ;knit loops: [1435 on yarn C3.3]. 
knit - f11 3 ;knit loops: [1436 on yarn C3.3]. 
knit - f8 3 ;knit loops: [1437 on yarn C3.3]. 
knit - f5 3 ;knit loops: [1438 on yarn C3.3]. 
knit - f2 3 ;knit loops: [1439 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {1383 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {1382 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {1381 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {1380 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {1379 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {1378 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {1377 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {1376 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {1375 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {1374 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {1373 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {1372 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {1371 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {1370 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {1369 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {1368 on yarn C1.1} on b69 to f69
knit + f0 1 ;knit loops: [1440 on yarn C1.1]. 
knit + f3 1 ;knit loops: [1441 on yarn C1.1]. 
knit + f6 1 ;knit loops: [1442 on yarn C1.1]. 
knit + f9 1 ;knit loops: [1443 on yarn C1.1]. 
knit + f12 1 ;knit loops: [1444 on yarn C1.1]. 
knit + f15 1 ;knit loops: [1445 on yarn C1.1]. 
knit + f18 1 ;knit loops: [1446 on yarn C1.1]. 
knit + f21 1 ;knit loops: [1447 on yarn C1.1]. 
knit + f24 1 ;knit loops: [1448 on yarn C1.1]. 
knit + f27 1 ;knit loops: [1449 on yarn C1.1]. 
knit + f30 1 ;knit loops: [1450 on yarn C1.1]. 
knit + f33 1 ;knit loops: [1451 on yarn C1.1]. 
knit + f36 1 ;knit loops: [1452 on yarn C1.1]. 
knit + f39 1 ;knit loops: [1453 on yarn C1.1]. 
knit + f42 1 ;knit loops: [1454 on yarn C1.1]. 
knit + f45 1 ;knit loops: [1455 on yarn C1.1]. 
knit + f48 1 ;knit loops: [1456 on yarn C1.1]. 
knit + f51 1 ;knit loops: [1457 on yarn C1.1]. 
knit + f54 1 ;knit loops: [1458 on yarn C1.1]. 
knit + f57 1 ;knit loops: [1459 on yarn C1.1]. 
knit + f60 1 ;knit loops: [1460 on yarn C1.1]. 
knit + f63 1 ;knit loops: [1461 on yarn C1.1]. 
knit + f66 1 ;knit loops: [1462 on yarn C1.1]. 
knit + f69 1 ;knit loops: [1463 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {1392 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {1393 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {1394 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {1395 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {1396 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {1397 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {1398 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {1399 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {1400 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {1401 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {1402 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {1403 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {1404 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {1405 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {1406 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {1407 on yarn C2.2} on b46 to f46
knit - f70 2 ;knit loops: [1464 on yarn C2.2]. 
knit - f67 2 ;knit loops: [1465 on yarn C2.2]. 
knit - f64 2 ;knit loops: [1466 on yarn C2.2]. 
knit - f61 2 ;knit loops: [1467 on yarn C2.2]. 
knit - f58 2 ;knit loops: [1468 on yarn C2.2]. 
knit - f55 2 ;knit loops: [1469 on yarn C2.2]. 
knit - f52 2 ;knit loops: [1470 on yarn C2.2]. 
knit - f49 2 ;knit loops: [1471 on yarn C2.2]. 
knit - f46 2 ;knit loops: [1472 on yarn C2.2]. 
knit - f43 2 ;knit loops: [1473 on yarn C2.2]. 
knit - f40 2 ;knit loops: [1474 on yarn C2.2]. 
knit - f37 2 ;knit loops: [1475 on yarn C2.2]. 
knit - f34 2 ;knit loops: [1476 on yarn C2.2]. 
knit - f31 2 ;knit loops: [1477 on yarn C2.2]. 
knit - f28 2 ;knit loops: [1478 on yarn C2.2]. 
knit - f25 2 ;knit loops: [1479 on yarn C2.2]. 
knit - f22 2 ;knit loops: [1480 on yarn C2.2]. 
knit - f19 2 ;knit loops: [1481 on yarn C2.2]. 
knit - f16 2 ;knit loops: [1482 on yarn C2.2]. 
knit - f13 2 ;knit loops: [1483 on yarn C2.2]. 
knit - f10 2 ;knit loops: [1484 on yarn C2.2]. 
knit - f7 2 ;knit loops: [1485 on yarn C2.2]. 
knit - f4 2 ;knit loops: [1486 on yarn C2.2]. 
knit - f1 2 ;knit loops: [1487 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {1439 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {1438 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {1437 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {1436 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {1435 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {1434 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {1433 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {1432 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {1423 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {1422 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {1421 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {1420 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {1419 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {1418 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {1417 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {1416 on yarn C3.3} on b71 to f71
knit + f2 3 ;knit loops: [1488 on yarn C3.3]. 
knit + f5 3 ;knit loops: [1489 on yarn C3.3]. 
knit + f8 3 ;knit loops: [1490 on yarn C3.3]. 
knit + f11 3 ;knit loops: [1491 on yarn C3.3]. 
knit + f14 3 ;knit loops: [1492 on yarn C3.3]. 
knit + f17 3 ;knit loops: [1493 on yarn C3.3]. 
knit + f20 3 ;knit loops: [1494 on yarn C3.3]. 
knit + f23 3 ;knit loops: [1495 on yarn C3.3]. 
knit + f26 3 ;knit loops: [1496 on yarn C3.3]. 
knit + f29 3 ;knit loops: [1497 on yarn C3.3]. 
knit + f32 3 ;knit loops: [1498 on yarn C3.3]. 
knit + f35 3 ;knit loops: [1499 on yarn C3.3]. 
knit + f38 3 ;knit loops: [1500 on yarn C3.3]. 
knit + f41 3 ;knit loops: [1501 on yarn C3.3]. 
knit + f44 3 ;knit loops: [1502 on yarn C3.3]. 
knit + f47 3 ;knit loops: [1503 on yarn C3.3]. 
knit + f50 3 ;knit loops: [1504 on yarn C3.3]. 
knit + f53 3 ;knit loops: [1505 on yarn C3.3]. 
knit + f56 3 ;knit loops: [1506 on yarn C3.3]. 
knit + f59 3 ;knit loops: [1507 on yarn C3.3]. 
knit + f62 3 ;knit loops: [1508 on yarn C3.3]. 
knit + f65 3 ;knit loops: [1509 on yarn C3.3]. 
knit + f68 3 ;knit loops: [1510 on yarn C3.3]. 
knit + f71 3 ;knit loops: [1511 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {1448 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {1449 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {1450 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {1451 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {1452 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {1453 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {1454 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {1455 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {1456 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {1457 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {1458 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {1459 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {1460 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {1461 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {1462 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {1463 on yarn C1.1} on b69 to f69
knit - f69 1 ;knit loops: [1512 on yarn C1.1]. 
knit - f66 1 ;knit loops: [1513 on yarn C1.1]. 
knit - f63 1 ;knit loops: [1514 on yarn C1.1]. 
knit - f60 1 ;knit loops: [1515 on yarn C1.1]. 
knit - f57 1 ;knit loops: [1516 on yarn C1.1]. 
knit - f54 1 ;knit loops: [1517 on yarn C1.1]. 
knit - f51 1 ;knit loops: [1518 on yarn C1.1]. 
knit - f48 1 ;knit loops: [1519 on yarn C1.1]. 
knit - f45 1 ;knit loops: [1520 on yarn C1.1]. 
knit - f42 1 ;knit loops: [1521 on yarn C1.1]. 
knit - f39 1 ;knit loops: [1522 on yarn C1.1]. 
knit - f36 1 ;knit loops: [1523 on yarn C1.1]. 
knit - f33 1 ;knit loops: [1524 on yarn C1.1]. 
knit - f30 1 ;knit loops: [1525 on yarn C1.1]. 
knit - f27 1 ;knit loops: [1526 on yarn C1.1]. 
knit - f24 1 ;knit loops: [1527 on yarn C1.1]. 
knit - f21 1 ;knit loops: [1528 on yarn C1.1]. 
knit - f18 1 ;knit loops: [1529 on yarn C1.1]. 
knit - f15 1 ;knit loops: [1530 on yarn C1.1]. 
knit - f12 1 ;knit loops: [1531 on yarn C1.1]. 
knit - f9 1 ;knit loops: [1532 on yarn C1.1]. 
knit - f6 1 ;knit loops: [1533 on yarn C1.1]. 
knit - f3 1 ;knit loops: [1534 on yarn C1.1]. 
knit - f0 1 ;knit loops: [1535 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {1487 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {1486 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {1485 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {1484 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {1483 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {1482 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {1481 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {1480 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {1479 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {1478 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {1477 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {1476 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {1475 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {1474 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {1473 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {1472 on yarn C2.2} on b46 to f46
knit + f1 2 ;knit loops: [1536 on yarn C2.2]. 
knit + f4 2 ;knit loops: [1537 on yarn C2.2]. 
knit + f7 2 ;knit loops: [1538 on yarn C2.2]. 
knit + f10 2 ;knit loops: [1539 on yarn C2.2]. 
knit + f13 2 ;knit loops: [1540 on yarn C2.2]. 
knit + f16 2 ;knit loops: [1541 on yarn C2.2]. 
knit + f19 2 ;knit loops: [1542 on yarn C2.2]. 
knit + f22 2 ;knit loops: [1543 on yarn C2.2]. 
knit + f25 2 ;knit loops: [1544 on yarn C2.2]. 
knit + f28 2 ;knit loops: [1545 on yarn C2.2]. 
knit + f31 2 ;knit loops: [1546 on yarn C2.2]. 
knit + f34 2 ;knit loops: [1547 on yarn C2.2]. 
knit + f37 2 ;knit loops: [1548 on yarn C2.2]. 
knit + f40 2 ;knit loops: [1549 on yarn C2.2]. 
knit + f43 2 ;knit loops: [1550 on yarn C2.2]. 
knit + f46 2 ;knit loops: [1551 on yarn C2.2]. 
knit + f49 2 ;knit loops: [1552 on yarn C2.2]. 
knit + f52 2 ;knit loops: [1553 on yarn C2.2]. 
knit + f55 2 ;knit loops: [1554 on yarn C2.2]. 
knit + f58 2 ;knit loops: [1555 on yarn C2.2]. 
knit + f61 2 ;knit loops: [1556 on yarn C2.2]. 
knit + f64 2 ;knit loops: [1557 on yarn C2.2]. 
knit + f67 2 ;knit loops: [1558 on yarn C2.2]. 
knit + f70 2 ;knit loops: [1559 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {1488 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {1489 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {1490 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {1491 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {1492 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {1493 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {1494 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {1495 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {1504 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {1505 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {1506 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {1507 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {1508 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {1509 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {1510 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {1511 on yarn C3.3} on b71 to f71
knit - f71 3 ;knit loops: [1560 on yarn C3.3]. 
knit - f68 3 ;knit loops: [1561 on yarn C3.3]. 
knit - f65 3 ;knit loops: [1562 on yarn C3.3]. 
knit - f62 3 ;knit loops: [1563 on yarn C3.3]. 
knit - f59 3 ;knit loops: [1564 on yarn C3.3]. 
knit - f56 3 ;knit loops: [1565 on yarn C3.3]. 
knit - f53 3 ;knit loops: [1566 on yarn C3.3]. 
knit - f50 3 ;knit loops: [1567 on yarn C3.3]. 
knit - f47 3 ;knit loops: [1568 on yarn C3.3]. 
knit - f44 3 ;knit loops: [1569 on yarn C3.3]. 
knit - f41 3 ;knit loops: [1570 on yarn C3.3]. 
knit - f38 3 ;knit loops: [1571 on yarn C3.3]. 
knit - f35 3 ;knit loops: [1572 on yarn C3.3]. 
knit - f32 3 ;knit loops: [1573 on yarn C3.3]. 
knit - f29 3 ;knit loops: [1574 on yarn C3.3]. 
knit - f26 3 ;knit loops: [1575 on yarn C3.3]. 
knit - f23 3 ;knit loops: [1576 on yarn C3.3]. 
knit - f20 3 ;knit loops: [1577 on yarn C3.3]. 
knit - f17 3 ;knit loops: [1578 on yarn C3.3]. 
knit - f14 3 ;knit loops: [1579 on yarn C3.3]. 
knit - f11 3 ;knit loops: [1580 on yarn C3.3]. 
knit - f8 3 ;knit loops: [1581 on yarn C3.3]. 
knit - f5 3 ;knit loops: [1582 on yarn C3.3]. 
knit - f2 3 ;knit loops: [1583 on yarn C3.3]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f1 b1 ;
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
; Peel sheet 2 relative to 0
xfer f2 b2 ;
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer b24 f24 ;Return loops {1527 on yarn C1.1} on b24 to f24
xfer b27 f27 ;Return loops {1526 on yarn C1.1} on b27 to f27
xfer b30 f30 ;Return loops {1525 on yarn C1.1} on b30 to f30
xfer b33 f33 ;Return loops {1524 on yarn C1.1} on b33 to f33
xfer b36 f36 ;Return loops {1523 on yarn C1.1} on b36 to f36
xfer b39 f39 ;Return loops {1522 on yarn C1.1} on b39 to f39
xfer b42 f42 ;Return loops {1521 on yarn C1.1} on b42 to f42
xfer b45 f45 ;Return loops {1520 on yarn C1.1} on b45 to f45
xfer b48 f48 ;Return loops {1519 on yarn C1.1} on b48 to f48
xfer b51 f51 ;Return loops {1518 on yarn C1.1} on b51 to f51
xfer b54 f54 ;Return loops {1517 on yarn C1.1} on b54 to f54
xfer b57 f57 ;Return loops {1516 on yarn C1.1} on b57 to f57
xfer b60 f60 ;Return loops {1515 on yarn C1.1} on b60 to f60
xfer b63 f63 ;Return loops {1514 on yarn C1.1} on b63 to f63
xfer b66 f66 ;Return loops {1513 on yarn C1.1} on b66 to f66
xfer b69 f69 ;Return loops {1512 on yarn C1.1} on b69 to f69
knit + f0 1 ;knit loops: [1584 on yarn C1.1]. 
knit + f3 1 ;knit loops: [1585 on yarn C1.1]. 
knit + f6 1 ;knit loops: [1586 on yarn C1.1]. 
knit + f9 1 ;knit loops: [1587 on yarn C1.1]. 
knit + f12 1 ;knit loops: [1588 on yarn C1.1]. 
knit + f15 1 ;knit loops: [1589 on yarn C1.1]. 
knit + f18 1 ;knit loops: [1590 on yarn C1.1]. 
knit + f21 1 ;knit loops: [1591 on yarn C1.1]. 
knit + f24 1 ;knit loops: [1592 on yarn C1.1]. 
knit + f27 1 ;knit loops: [1593 on yarn C1.1]. 
knit + f30 1 ;knit loops: [1594 on yarn C1.1]. 
knit + f33 1 ;knit loops: [1595 on yarn C1.1]. 
knit + f36 1 ;knit loops: [1596 on yarn C1.1]. 
knit + f39 1 ;knit loops: [1597 on yarn C1.1]. 
knit + f42 1 ;knit loops: [1598 on yarn C1.1]. 
knit + f45 1 ;knit loops: [1599 on yarn C1.1]. 
knit + f48 1 ;knit loops: [1600 on yarn C1.1]. 
knit + f51 1 ;knit loops: [1601 on yarn C1.1]. 
knit + f54 1 ;knit loops: [1602 on yarn C1.1]. 
knit + f57 1 ;knit loops: [1603 on yarn C1.1]. 
knit + f60 1 ;knit loops: [1604 on yarn C1.1]. 
knit + f63 1 ;knit loops: [1605 on yarn C1.1]. 
knit + f66 1 ;knit loops: [1606 on yarn C1.1]. 
knit + f69 1 ;knit loops: [1607 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
xfer f48 b48 ;
xfer f51 b51 ;
xfer f54 b54 ;
xfer f57 b57 ;
xfer f60 b60 ;
xfer f63 b63 ;
xfer f66 b66 ;
xfer f69 b69 ;
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f50 b50 ;
xfer f53 b53 ;
xfer f56 b56 ;
xfer f59 b59 ;
xfer f62 b62 ;
xfer f65 b65 ;
xfer f68 b68 ;
xfer f71 b71 ;
xfer b1 f1 ;Return loops {1536 on yarn C2.2} on b1 to f1
xfer b4 f4 ;Return loops {1537 on yarn C2.2} on b4 to f4
xfer b7 f7 ;Return loops {1538 on yarn C2.2} on b7 to f7
xfer b10 f10 ;Return loops {1539 on yarn C2.2} on b10 to f10
xfer b13 f13 ;Return loops {1540 on yarn C2.2} on b13 to f13
xfer b16 f16 ;Return loops {1541 on yarn C2.2} on b16 to f16
xfer b19 f19 ;Return loops {1542 on yarn C2.2} on b19 to f19
xfer b22 f22 ;Return loops {1543 on yarn C2.2} on b22 to f22
xfer b25 f25 ;Return loops {1544 on yarn C2.2} on b25 to f25
xfer b28 f28 ;Return loops {1545 on yarn C2.2} on b28 to f28
xfer b31 f31 ;Return loops {1546 on yarn C2.2} on b31 to f31
xfer b34 f34 ;Return loops {1547 on yarn C2.2} on b34 to f34
xfer b37 f37 ;Return loops {1548 on yarn C2.2} on b37 to f37
xfer b40 f40 ;Return loops {1549 on yarn C2.2} on b40 to f40
xfer b43 f43 ;Return loops {1550 on yarn C2.2} on b43 to f43
xfer b46 f46 ;Return loops {1551 on yarn C2.2} on b46 to f46
knit - f70 2 ;knit loops: [1608 on yarn C2.2]. 
knit - f67 2 ;knit loops: [1609 on yarn C2.2]. 
knit - f64 2 ;knit loops: [1610 on yarn C2.2]. 
knit - f61 2 ;knit loops: [1611 on yarn C2.2]. 
knit - f58 2 ;knit loops: [1612 on yarn C2.2]. 
knit - f55 2 ;knit loops: [1613 on yarn C2.2]. 
knit - f52 2 ;knit loops: [1614 on yarn C2.2]. 
knit - f49 2 ;knit loops: [1615 on yarn C2.2]. 
knit - f46 2 ;knit loops: [1616 on yarn C2.2]. 
knit - f43 2 ;knit loops: [1617 on yarn C2.2]. 
knit - f40 2 ;knit loops: [1618 on yarn C2.2]. 
knit - f37 2 ;knit loops: [1619 on yarn C2.2]. 
knit - f34 2 ;knit loops: [1620 on yarn C2.2]. 
knit - f31 2 ;knit loops: [1621 on yarn C2.2]. 
knit - f28 2 ;knit loops: [1622 on yarn C2.2]. 
knit - f25 2 ;knit loops: [1623 on yarn C2.2]. 
knit - f22 2 ;knit loops: [1624 on yarn C2.2]. 
knit - f19 2 ;knit loops: [1625 on yarn C2.2]. 
knit - f16 2 ;knit loops: [1626 on yarn C2.2]. 
knit - f13 2 ;knit loops: [1627 on yarn C2.2]. 
knit - f10 2 ;knit loops: [1628 on yarn C2.2]. 
knit - f7 2 ;knit loops: [1629 on yarn C2.2]. 
knit - f4 2 ;knit loops: [1630 on yarn C2.2]. 
knit - f1 2 ;knit loops: [1631 on yarn C2.2]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
xfer f24 b24 ;
xfer f27 b27 ;
xfer f30 b30 ;
xfer f33 b33 ;
xfer f36 b36 ;
xfer f39 b39 ;
xfer f42 b42 ;
xfer f45 b45 ;
; Peel sheet 1 relative to 2
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
xfer f34 b34 ;
xfer f37 b37 ;
xfer f40 b40 ;
xfer f43 b43 ;
xfer f46 b46 ;
; Peel sheet 2 relative to 2
xfer b2 f2 ;Return loops {1583 on yarn C3.3} on b2 to f2
xfer b5 f5 ;Return loops {1582 on yarn C3.3} on b5 to f5
xfer b8 f8 ;Return loops {1581 on yarn C3.3} on b8 to f8
xfer b11 f11 ;Return loops {1580 on yarn C3.3} on b11 to f11
xfer b14 f14 ;Return loops {1579 on yarn C3.3} on b14 to f14
xfer b17 f17 ;Return loops {1578 on yarn C3.3} on b17 to f17
xfer b20 f20 ;Return loops {1577 on yarn C3.3} on b20 to f20
xfer b23 f23 ;Return loops {1576 on yarn C3.3} on b23 to f23
xfer b50 f50 ;Return loops {1567 on yarn C3.3} on b50 to f50
xfer b53 f53 ;Return loops {1566 on yarn C3.3} on b53 to f53
xfer b56 f56 ;Return loops {1565 on yarn C3.3} on b56 to f56
xfer b59 f59 ;Return loops {1564 on yarn C3.3} on b59 to f59
xfer b62 f62 ;Return loops {1563 on yarn C3.3} on b62 to f62
xfer b65 f65 ;Return loops {1562 on yarn C3.3} on b65 to f65
xfer b68 f68 ;Return loops {1561 on yarn C3.3} on b68 to f68
xfer b71 f71 ;Return loops {1560 on yarn C3.3} on b71 to f71
knit + f2 3 ;knit loops: [1632 on yarn C3.3]. 
knit + f5 3 ;knit loops: [1633 on yarn C3.3]. 
knit + f8 3 ;knit loops: [1634 on yarn C3.3]. 
knit + f11 3 ;knit loops: [1635 on yarn C3.3]. 
knit + f14 3 ;knit loops: [1636 on yarn C3.3]. 
knit + f17 3 ;knit loops: [1637 on yarn C3.3]. 
knit + f20 3 ;knit loops: [1638 on yarn C3.3]. 
knit + f23 3 ;knit loops: [1639 on yarn C3.3]. 
knit + f26 3 ;knit loops: [1640 on yarn C3.3]. 
knit + f29 3 ;knit loops: [1641 on yarn C3.3]. 
knit + f32 3 ;knit loops: [1642 on yarn C3.3]. 
knit + f35 3 ;knit loops: [1643 on yarn C3.3]. 
knit + f38 3 ;knit loops: [1644 on yarn C3.3]. 
knit + f41 3 ;knit loops: [1645 on yarn C3.3]. 
knit + f44 3 ;knit loops: [1646 on yarn C3.3]. 
knit + f47 3 ;knit loops: [1647 on yarn C3.3]. 
knit + f50 3 ;knit loops: [1648 on yarn C3.3]. 
knit + f53 3 ;knit loops: [1649 on yarn C3.3]. 
knit + f56 3 ;knit loops: [1650 on yarn C3.3]. 
knit + f59 3 ;knit loops: [1651 on yarn C3.3]. 
knit + f62 3 ;knit loops: [1652 on yarn C3.3]. 
knit + f65 3 ;knit loops: [1653 on yarn C3.3]. 
knit + f68 3 ;knit loops: [1654 on yarn C3.3]. 
knit + f71 3 ;knit loops: [1655 on yarn C3.3]. 
outhook 1; Cut yarn 1, disconnecting knitted piece
outhook 2; Cut yarn 2, disconnecting knitted piece
outhook 3; Cut yarn 3, disconnecting knitted piece
