;!knitout-2
;;Machine: SWG091N2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Gauge: 5
;;Width: 250
;;Position: Center
inhook  1 ;Activating carrier  1
;KP Printout: Left tuck at 0
rack 0.25; All Needle racking 0 to right
tuck - b3 1 ; 
tuck - f3 1 ; 
tuck - b2 1 ; 
tuck - f2 1 ; 
tuck - b1 1 ; 
tuck - f1 1 ; 
tuck - b0 1 ; 
tuck - f0 1 ; 
rack 0; Single-Needle racking
;KP Printout: Right knit at 0
rack 0.25; All Needle racking 0 to right
knit + f0 1 ; 
knit + b0 1 ; 
knit + f1 1 ; 
knit + b1 1 ; 
knit + f2 1 ; 
knit + b2 1 ; 
knit + f3 1 ; 
knit + b3 1 ; 
rack 0; Single-Needle racking
;KP Printout: Left knit  at 0
rack 0.25; All Needle racking 0 to right
releasehook  1 ;
knit - b3 1 ; 
knit - f3 1 ; 
knit - b2 1 ; 
knit - f2 1 ; 
knit - b1 1 ; 
knit - f1 1 ; 
knit - b0 1 ; 
knit - f0 1 ; 
rack 0; Single-Needle racking
;KP Printout: Right tuck  at 0
rack 0.25; All Needle racking 0 to right
tuck + f0 1 ; 
tuck + b0 1 ; 
tuck + f1 1 ; 
tuck + b1 1 ; 
tuck + f2 1 ; 
tuck + b2 1 ; 
tuck + f3 1 ; 
tuck + b3 1 ; 
rack 0; Single-Needle racking
outhook 1; Cut yarn 1, disconnecting knitted piece
