;!knitout-2
;;Machine: SWG091N2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Gauge: 7
;;Width: 250
;;Position: Center
inhook  1 ;Activating carrier  1
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
; Peel sheet 2 relative to 0
;KP Printout: caston 10loops
tuck - f30 1 ; tuck loops: [0 on yarn C1.1]. 
tuck - f24 1 ; tuck loops: [1 on yarn C1.1]. 
tuck - f18 1 ; tuck loops: [2 on yarn C1.1]. 
tuck - f12 1 ; tuck loops: [3 on yarn C1.1]. 
tuck - f6 1 ; tuck loops: [4 on yarn C1.1]. 
tuck + f3 1 ; tuck loops: [5 on yarn C1.1]. 
tuck + f9 1 ; tuck loops: [6 on yarn C1.1]. 
tuck + f15 1 ; tuck loops: [7 on yarn C1.1]. 
tuck + f21 1 ; tuck loops: [8 on yarn C1.1]. 
tuck + f27 1 ; tuck loops: [9 on yarn C1.1]. 
releasehook  1 ;
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
;KP Printout: caston 10loops
tuck - f31 1 ; tuck loops: [10 on yarn C1.1]. 
tuck - f25 1 ; tuck loops: [11 on yarn C1.1]. 
tuck - f19 1 ; tuck loops: [12 on yarn C1.1]. 
tuck - f13 1 ; tuck loops: [13 on yarn C1.1]. 
tuck - f7 1 ; tuck loops: [14 on yarn C1.1]. 
tuck + f4 1 ; tuck loops: [15 on yarn C1.1]. 
tuck + f10 1 ; tuck loops: [16 on yarn C1.1]. 
tuck + f16 1 ; tuck loops: [17 on yarn C1.1]. 
tuck + f22 1 ; tuck loops: [18 on yarn C1.1]. 
tuck + f28 1 ; tuck loops: [19 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
; Peel sheet 2 relative to 2
;KP Printout: caston 10loops
tuck - f32 1 ; tuck loops: [20 on yarn C1.1]. 
tuck - f26 1 ; tuck loops: [21 on yarn C1.1]. 
tuck - f20 1 ; tuck loops: [22 on yarn C1.1]. 
tuck - f14 1 ; tuck loops: [23 on yarn C1.1]. 
tuck - f8 1 ; tuck loops: [24 on yarn C1.1]. 
tuck + f5 1 ; tuck loops: [25 on yarn C1.1]. 
tuck + f11 1 ; tuck loops: [26 on yarn C1.1]. 
tuck + f17 1 ; tuck loops: [27 on yarn C1.1]. 
tuck + f23 1 ; tuck loops: [28 on yarn C1.1]. 
tuck + f29 1 ; tuck loops: [29 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer f5 b5 ;
xfer f8 b8 ;
xfer f11 b11 ;
xfer f14 b14 ;
xfer f17 b17 ;
xfer f20 b20 ;
xfer f23 b23 ;
xfer f26 b26 ;
xfer f29 b29 ;
xfer f32 b32 ;
;KP Printout: xfer for ribbing
xfer f28 b28 ;
xfer f22 b22 ;
xfer f16 b16 ;
xfer f10 b10 ;
xfer f4 b4 ;
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
xfer b5 f5 ;Return loops {25 on yarn C1.1} on b5 to f5
xfer b8 f8 ;Return loops {24 on yarn C1.1} on b8 to f8
xfer b11 f11 ;Return loops {26 on yarn C1.1} on b11 to f11
xfer b14 f14 ;Return loops {23 on yarn C1.1} on b14 to f14
xfer b17 f17 ;Return loops {27 on yarn C1.1} on b17 to f17
xfer b20 f20 ;Return loops {22 on yarn C1.1} on b20 to f20
xfer b23 f23 ;Return loops {28 on yarn C1.1} on b23 to f23
xfer b26 f26 ;Return loops {21 on yarn C1.1} on b26 to f26
xfer b29 f29 ;Return loops {29 on yarn C1.1} on b29 to f29
xfer b32 f32 ;Return loops {20 on yarn C1.1} on b32 to f32
xfer f32 b32 ;
xfer f29 b29 ;
xfer f26 b26 ;
xfer f23 b23 ;
xfer f20 b20 ;
xfer f17 b17 ;
xfer f14 b14 ;
xfer f11 b11 ;
xfer f8 b8 ;
xfer f5 b5 ;
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit - f30 1 ;knit loops: [30 on yarn C1.1]. 
knit - f27 1 ;knit loops: [31 on yarn C1.1]. 
knit - f24 1 ;knit loops: [32 on yarn C1.1]. 
knit - f21 1 ;knit loops: [33 on yarn C1.1]. 
knit - f18 1 ;knit loops: [34 on yarn C1.1]. 
knit - f15 1 ;knit loops: [35 on yarn C1.1]. 
knit - f12 1 ;knit loops: [36 on yarn C1.1]. 
knit - f9 1 ;knit loops: [37 on yarn C1.1]. 
knit - f6 1 ;knit loops: [38 on yarn C1.1]. 
knit - f3 1 ;knit loops: [39 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {14 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {13 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {12 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {11 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {10 on yarn C1.1} on b31 to f31
knit + b4 1 ;knit loops: [40 on yarn C1.1]. 
knit + f7 1 ;knit loops: [41 on yarn C1.1]. 
knit + b10 1 ;knit loops: [42 on yarn C1.1]. 
knit + f13 1 ;knit loops: [43 on yarn C1.1]. 
knit + b16 1 ;knit loops: [44 on yarn C1.1]. 
knit + f19 1 ;knit loops: [45 on yarn C1.1]. 
knit + b22 1 ;knit loops: [46 on yarn C1.1]. 
knit + f25 1 ;knit loops: [47 on yarn C1.1]. 
knit + b28 1 ;knit loops: [48 on yarn C1.1]. 
knit + f31 1 ;knit loops: [49 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit - b32 1 ;knit loops: [50 on yarn C1.1]. 
knit - b29 1 ;knit loops: [51 on yarn C1.1]. 
knit - b26 1 ;knit loops: [52 on yarn C1.1]. 
knit - b23 1 ;knit loops: [53 on yarn C1.1]. 
knit - b20 1 ;knit loops: [54 on yarn C1.1]. 
knit - b17 1 ;knit loops: [55 on yarn C1.1]. 
knit - b14 1 ;knit loops: [56 on yarn C1.1]. 
knit - b11 1 ;knit loops: [57 on yarn C1.1]. 
knit - b8 1 ;knit loops: [58 on yarn C1.1]. 
knit - b5 1 ;knit loops: [59 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit + f3 1 ;knit loops: [60 on yarn C1.1]. 
knit + f6 1 ;knit loops: [61 on yarn C1.1]. 
knit + f9 1 ;knit loops: [62 on yarn C1.1]. 
knit + f12 1 ;knit loops: [63 on yarn C1.1]. 
knit + f15 1 ;knit loops: [64 on yarn C1.1]. 
knit + f18 1 ;knit loops: [65 on yarn C1.1]. 
knit + f21 1 ;knit loops: [66 on yarn C1.1]. 
knit + f24 1 ;knit loops: [67 on yarn C1.1]. 
knit + f27 1 ;knit loops: [68 on yarn C1.1]. 
knit + f30 1 ;knit loops: [69 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {41 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {43 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {45 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {47 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {49 on yarn C1.1} on b31 to f31
knit - f31 1 ;knit loops: [70 on yarn C1.1]. 
knit - b28 1 ;knit loops: [71 on yarn C1.1]. 
knit - f25 1 ;knit loops: [72 on yarn C1.1]. 
knit - b22 1 ;knit loops: [73 on yarn C1.1]. 
knit - f19 1 ;knit loops: [74 on yarn C1.1]. 
knit - b16 1 ;knit loops: [75 on yarn C1.1]. 
knit - f13 1 ;knit loops: [76 on yarn C1.1]. 
knit - b10 1 ;knit loops: [77 on yarn C1.1]. 
knit - f7 1 ;knit loops: [78 on yarn C1.1]. 
knit - b4 1 ;knit loops: [79 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit + b5 1 ;knit loops: [80 on yarn C1.1]. 
knit + b8 1 ;knit loops: [81 on yarn C1.1]. 
knit + b11 1 ;knit loops: [82 on yarn C1.1]. 
knit + b14 1 ;knit loops: [83 on yarn C1.1]. 
knit + b17 1 ;knit loops: [84 on yarn C1.1]. 
knit + b20 1 ;knit loops: [85 on yarn C1.1]. 
knit + b23 1 ;knit loops: [86 on yarn C1.1]. 
knit + b26 1 ;knit loops: [87 on yarn C1.1]. 
knit + b29 1 ;knit loops: [88 on yarn C1.1]. 
knit + b32 1 ;knit loops: [89 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit - f30 1 ;knit loops: [90 on yarn C1.1]. 
knit - f27 1 ;knit loops: [91 on yarn C1.1]. 
knit - f24 1 ;knit loops: [92 on yarn C1.1]. 
knit - f21 1 ;knit loops: [93 on yarn C1.1]. 
knit - f18 1 ;knit loops: [94 on yarn C1.1]. 
knit - f15 1 ;knit loops: [95 on yarn C1.1]. 
knit - f12 1 ;knit loops: [96 on yarn C1.1]. 
knit - f9 1 ;knit loops: [97 on yarn C1.1]. 
knit - f6 1 ;knit loops: [98 on yarn C1.1]. 
knit - f3 1 ;knit loops: [99 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {78 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {76 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {74 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {72 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {70 on yarn C1.1} on b31 to f31
knit + b4 1 ;knit loops: [100 on yarn C1.1]. 
knit + f7 1 ;knit loops: [101 on yarn C1.1]. 
knit + b10 1 ;knit loops: [102 on yarn C1.1]. 
knit + f13 1 ;knit loops: [103 on yarn C1.1]. 
knit + b16 1 ;knit loops: [104 on yarn C1.1]. 
knit + f19 1 ;knit loops: [105 on yarn C1.1]. 
knit + b22 1 ;knit loops: [106 on yarn C1.1]. 
knit + f25 1 ;knit loops: [107 on yarn C1.1]. 
knit + b28 1 ;knit loops: [108 on yarn C1.1]. 
knit + f31 1 ;knit loops: [109 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit - b32 1 ;knit loops: [110 on yarn C1.1]. 
knit - b29 1 ;knit loops: [111 on yarn C1.1]. 
knit - b26 1 ;knit loops: [112 on yarn C1.1]. 
knit - b23 1 ;knit loops: [113 on yarn C1.1]. 
knit - b20 1 ;knit loops: [114 on yarn C1.1]. 
knit - b17 1 ;knit loops: [115 on yarn C1.1]. 
knit - b14 1 ;knit loops: [116 on yarn C1.1]. 
knit - b11 1 ;knit loops: [117 on yarn C1.1]. 
knit - b8 1 ;knit loops: [118 on yarn C1.1]. 
knit - b5 1 ;knit loops: [119 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit + f3 1 ;knit loops: [120 on yarn C1.1]. 
knit + f6 1 ;knit loops: [121 on yarn C1.1]. 
knit + f9 1 ;knit loops: [122 on yarn C1.1]. 
knit + f12 1 ;knit loops: [123 on yarn C1.1]. 
knit + f15 1 ;knit loops: [124 on yarn C1.1]. 
knit + f18 1 ;knit loops: [125 on yarn C1.1]. 
knit + f21 1 ;knit loops: [126 on yarn C1.1]. 
knit + f24 1 ;knit loops: [127 on yarn C1.1]. 
knit + f27 1 ;knit loops: [128 on yarn C1.1]. 
knit + f30 1 ;knit loops: [129 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {101 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {103 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {105 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {107 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {109 on yarn C1.1} on b31 to f31
knit - f31 1 ;knit loops: [130 on yarn C1.1]. 
knit - b28 1 ;knit loops: [131 on yarn C1.1]. 
knit - f25 1 ;knit loops: [132 on yarn C1.1]. 
knit - b22 1 ;knit loops: [133 on yarn C1.1]. 
knit - f19 1 ;knit loops: [134 on yarn C1.1]. 
knit - b16 1 ;knit loops: [135 on yarn C1.1]. 
knit - f13 1 ;knit loops: [136 on yarn C1.1]. 
knit - b10 1 ;knit loops: [137 on yarn C1.1]. 
knit - f7 1 ;knit loops: [138 on yarn C1.1]. 
knit - b4 1 ;knit loops: [139 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit + b5 1 ;knit loops: [140 on yarn C1.1]. 
knit + b8 1 ;knit loops: [141 on yarn C1.1]. 
knit + b11 1 ;knit loops: [142 on yarn C1.1]. 
knit + b14 1 ;knit loops: [143 on yarn C1.1]. 
knit + b17 1 ;knit loops: [144 on yarn C1.1]. 
knit + b20 1 ;knit loops: [145 on yarn C1.1]. 
knit + b23 1 ;knit loops: [146 on yarn C1.1]. 
knit + b26 1 ;knit loops: [147 on yarn C1.1]. 
knit + b29 1 ;knit loops: [148 on yarn C1.1]. 
knit + b32 1 ;knit loops: [149 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit - f30 1 ;knit loops: [150 on yarn C1.1]. 
knit - f27 1 ;knit loops: [151 on yarn C1.1]. 
knit - f24 1 ;knit loops: [152 on yarn C1.1]. 
knit - f21 1 ;knit loops: [153 on yarn C1.1]. 
knit - f18 1 ;knit loops: [154 on yarn C1.1]. 
knit - f15 1 ;knit loops: [155 on yarn C1.1]. 
knit - f12 1 ;knit loops: [156 on yarn C1.1]. 
knit - f9 1 ;knit loops: [157 on yarn C1.1]. 
knit - f6 1 ;knit loops: [158 on yarn C1.1]. 
knit - f3 1 ;knit loops: [159 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {138 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {136 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {134 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {132 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {130 on yarn C1.1} on b31 to f31
knit + b4 1 ;knit loops: [160 on yarn C1.1]. 
knit + f7 1 ;knit loops: [161 on yarn C1.1]. 
knit + b10 1 ;knit loops: [162 on yarn C1.1]. 
knit + f13 1 ;knit loops: [163 on yarn C1.1]. 
knit + b16 1 ;knit loops: [164 on yarn C1.1]. 
knit + f19 1 ;knit loops: [165 on yarn C1.1]. 
knit + b22 1 ;knit loops: [166 on yarn C1.1]. 
knit + f25 1 ;knit loops: [167 on yarn C1.1]. 
knit + b28 1 ;knit loops: [168 on yarn C1.1]. 
knit + f31 1 ;knit loops: [169 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit - b32 1 ;knit loops: [170 on yarn C1.1]. 
knit - b29 1 ;knit loops: [171 on yarn C1.1]. 
knit - b26 1 ;knit loops: [172 on yarn C1.1]. 
knit - b23 1 ;knit loops: [173 on yarn C1.1]. 
knit - b20 1 ;knit loops: [174 on yarn C1.1]. 
knit - b17 1 ;knit loops: [175 on yarn C1.1]. 
knit - b14 1 ;knit loops: [176 on yarn C1.1]. 
knit - b11 1 ;knit loops: [177 on yarn C1.1]. 
knit - b8 1 ;knit loops: [178 on yarn C1.1]. 
knit - b5 1 ;knit loops: [179 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit + f3 1 ;knit loops: [180 on yarn C1.1]. 
knit + f6 1 ;knit loops: [181 on yarn C1.1]. 
knit + f9 1 ;knit loops: [182 on yarn C1.1]. 
knit + f12 1 ;knit loops: [183 on yarn C1.1]. 
knit + f15 1 ;knit loops: [184 on yarn C1.1]. 
knit + f18 1 ;knit loops: [185 on yarn C1.1]. 
knit + f21 1 ;knit loops: [186 on yarn C1.1]. 
knit + f24 1 ;knit loops: [187 on yarn C1.1]. 
knit + f27 1 ;knit loops: [188 on yarn C1.1]. 
knit + f30 1 ;knit loops: [189 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {161 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {163 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {165 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {167 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {169 on yarn C1.1} on b31 to f31
knit - f31 1 ;knit loops: [190 on yarn C1.1]. 
knit - b28 1 ;knit loops: [191 on yarn C1.1]. 
knit - f25 1 ;knit loops: [192 on yarn C1.1]. 
knit - b22 1 ;knit loops: [193 on yarn C1.1]. 
knit - f19 1 ;knit loops: [194 on yarn C1.1]. 
knit - b16 1 ;knit loops: [195 on yarn C1.1]. 
knit - f13 1 ;knit loops: [196 on yarn C1.1]. 
knit - b10 1 ;knit loops: [197 on yarn C1.1]. 
knit - f7 1 ;knit loops: [198 on yarn C1.1]. 
knit - b4 1 ;knit loops: [199 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit + b5 1 ;knit loops: [200 on yarn C1.1]. 
knit + b8 1 ;knit loops: [201 on yarn C1.1]. 
knit + b11 1 ;knit loops: [202 on yarn C1.1]. 
knit + b14 1 ;knit loops: [203 on yarn C1.1]. 
knit + b17 1 ;knit loops: [204 on yarn C1.1]. 
knit + b20 1 ;knit loops: [205 on yarn C1.1]. 
knit + b23 1 ;knit loops: [206 on yarn C1.1]. 
knit + b26 1 ;knit loops: [207 on yarn C1.1]. 
knit + b29 1 ;knit loops: [208 on yarn C1.1]. 
knit + b32 1 ;knit loops: [209 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit - f30 1 ;knit loops: [210 on yarn C1.1]. 
knit - f27 1 ;knit loops: [211 on yarn C1.1]. 
knit - f24 1 ;knit loops: [212 on yarn C1.1]. 
knit - f21 1 ;knit loops: [213 on yarn C1.1]. 
knit - f18 1 ;knit loops: [214 on yarn C1.1]. 
knit - f15 1 ;knit loops: [215 on yarn C1.1]. 
knit - f12 1 ;knit loops: [216 on yarn C1.1]. 
knit - f9 1 ;knit loops: [217 on yarn C1.1]. 
knit - f6 1 ;knit loops: [218 on yarn C1.1]. 
knit - f3 1 ;knit loops: [219 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {198 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {196 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {194 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {192 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {190 on yarn C1.1} on b31 to f31
knit + b4 1 ;knit loops: [220 on yarn C1.1]. 
knit + f7 1 ;knit loops: [221 on yarn C1.1]. 
knit + b10 1 ;knit loops: [222 on yarn C1.1]. 
knit + f13 1 ;knit loops: [223 on yarn C1.1]. 
knit + b16 1 ;knit loops: [224 on yarn C1.1]. 
knit + f19 1 ;knit loops: [225 on yarn C1.1]. 
knit + b22 1 ;knit loops: [226 on yarn C1.1]. 
knit + f25 1 ;knit loops: [227 on yarn C1.1]. 
knit + b28 1 ;knit loops: [228 on yarn C1.1]. 
knit + f31 1 ;knit loops: [229 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit - b32 1 ;knit loops: [230 on yarn C1.1]. 
knit - b29 1 ;knit loops: [231 on yarn C1.1]. 
knit - b26 1 ;knit loops: [232 on yarn C1.1]. 
knit - b23 1 ;knit loops: [233 on yarn C1.1]. 
knit - b20 1 ;knit loops: [234 on yarn C1.1]. 
knit - b17 1 ;knit loops: [235 on yarn C1.1]. 
knit - b14 1 ;knit loops: [236 on yarn C1.1]. 
knit - b11 1 ;knit loops: [237 on yarn C1.1]. 
knit - b8 1 ;knit loops: [238 on yarn C1.1]. 
knit - b5 1 ;knit loops: [239 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit + f3 1 ;knit loops: [240 on yarn C1.1]. 
knit + f6 1 ;knit loops: [241 on yarn C1.1]. 
knit + f9 1 ;knit loops: [242 on yarn C1.1]. 
knit + f12 1 ;knit loops: [243 on yarn C1.1]. 
knit + f15 1 ;knit loops: [244 on yarn C1.1]. 
knit + f18 1 ;knit loops: [245 on yarn C1.1]. 
knit + f21 1 ;knit loops: [246 on yarn C1.1]. 
knit + f24 1 ;knit loops: [247 on yarn C1.1]. 
knit + f27 1 ;knit loops: [248 on yarn C1.1]. 
knit + f30 1 ;knit loops: [249 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {221 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {223 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {225 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {227 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {229 on yarn C1.1} on b31 to f31
knit - f31 1 ;knit loops: [250 on yarn C1.1]. 
knit - b28 1 ;knit loops: [251 on yarn C1.1]. 
knit - f25 1 ;knit loops: [252 on yarn C1.1]. 
knit - b22 1 ;knit loops: [253 on yarn C1.1]. 
knit - f19 1 ;knit loops: [254 on yarn C1.1]. 
knit - b16 1 ;knit loops: [255 on yarn C1.1]. 
knit - f13 1 ;knit loops: [256 on yarn C1.1]. 
knit - b10 1 ;knit loops: [257 on yarn C1.1]. 
knit - f7 1 ;knit loops: [258 on yarn C1.1]. 
knit - b4 1 ;knit loops: [259 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit + b5 1 ;knit loops: [260 on yarn C1.1]. 
knit + b8 1 ;knit loops: [261 on yarn C1.1]. 
knit + b11 1 ;knit loops: [262 on yarn C1.1]. 
knit + b14 1 ;knit loops: [263 on yarn C1.1]. 
knit + b17 1 ;knit loops: [264 on yarn C1.1]. 
knit + b20 1 ;knit loops: [265 on yarn C1.1]. 
knit + b23 1 ;knit loops: [266 on yarn C1.1]. 
knit + b26 1 ;knit loops: [267 on yarn C1.1]. 
knit + b29 1 ;knit loops: [268 on yarn C1.1]. 
knit + b32 1 ;knit loops: [269 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit - f30 1 ;knit loops: [270 on yarn C1.1]. 
knit - f27 1 ;knit loops: [271 on yarn C1.1]. 
knit - f24 1 ;knit loops: [272 on yarn C1.1]. 
knit - f21 1 ;knit loops: [273 on yarn C1.1]. 
knit - f18 1 ;knit loops: [274 on yarn C1.1]. 
knit - f15 1 ;knit loops: [275 on yarn C1.1]. 
knit - f12 1 ;knit loops: [276 on yarn C1.1]. 
knit - f9 1 ;knit loops: [277 on yarn C1.1]. 
knit - f6 1 ;knit loops: [278 on yarn C1.1]. 
knit - f3 1 ;knit loops: [279 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {258 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {256 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {254 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {252 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {250 on yarn C1.1} on b31 to f31
knit + b4 1 ;knit loops: [280 on yarn C1.1]. 
knit + f7 1 ;knit loops: [281 on yarn C1.1]. 
knit + b10 1 ;knit loops: [282 on yarn C1.1]. 
knit + f13 1 ;knit loops: [283 on yarn C1.1]. 
knit + b16 1 ;knit loops: [284 on yarn C1.1]. 
knit + f19 1 ;knit loops: [285 on yarn C1.1]. 
knit + b22 1 ;knit loops: [286 on yarn C1.1]. 
knit + f25 1 ;knit loops: [287 on yarn C1.1]. 
knit + b28 1 ;knit loops: [288 on yarn C1.1]. 
knit + f31 1 ;knit loops: [289 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit - b32 1 ;knit loops: [290 on yarn C1.1]. 
knit - b29 1 ;knit loops: [291 on yarn C1.1]. 
knit - b26 1 ;knit loops: [292 on yarn C1.1]. 
knit - b23 1 ;knit loops: [293 on yarn C1.1]. 
knit - b20 1 ;knit loops: [294 on yarn C1.1]. 
knit - b17 1 ;knit loops: [295 on yarn C1.1]. 
knit - b14 1 ;knit loops: [296 on yarn C1.1]. 
knit - b11 1 ;knit loops: [297 on yarn C1.1]. 
knit - b8 1 ;knit loops: [298 on yarn C1.1]. 
knit - b5 1 ;knit loops: [299 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit + f3 1 ;knit loops: [300 on yarn C1.1]. 
knit + f6 1 ;knit loops: [301 on yarn C1.1]. 
knit + f9 1 ;knit loops: [302 on yarn C1.1]. 
knit + f12 1 ;knit loops: [303 on yarn C1.1]. 
knit + f15 1 ;knit loops: [304 on yarn C1.1]. 
knit + f18 1 ;knit loops: [305 on yarn C1.1]. 
knit + f21 1 ;knit loops: [306 on yarn C1.1]. 
knit + f24 1 ;knit loops: [307 on yarn C1.1]. 
knit + f27 1 ;knit loops: [308 on yarn C1.1]. 
knit + f30 1 ;knit loops: [309 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {281 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {283 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {285 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {287 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {289 on yarn C1.1} on b31 to f31
knit - f31 1 ;knit loops: [310 on yarn C1.1]. 
knit - b28 1 ;knit loops: [311 on yarn C1.1]. 
knit - f25 1 ;knit loops: [312 on yarn C1.1]. 
knit - b22 1 ;knit loops: [313 on yarn C1.1]. 
knit - f19 1 ;knit loops: [314 on yarn C1.1]. 
knit - b16 1 ;knit loops: [315 on yarn C1.1]. 
knit - f13 1 ;knit loops: [316 on yarn C1.1]. 
knit - b10 1 ;knit loops: [317 on yarn C1.1]. 
knit - f7 1 ;knit loops: [318 on yarn C1.1]. 
knit - b4 1 ;knit loops: [319 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit + b5 1 ;knit loops: [320 on yarn C1.1]. 
knit + b8 1 ;knit loops: [321 on yarn C1.1]. 
knit + b11 1 ;knit loops: [322 on yarn C1.1]. 
knit + b14 1 ;knit loops: [323 on yarn C1.1]. 
knit + b17 1 ;knit loops: [324 on yarn C1.1]. 
knit + b20 1 ;knit loops: [325 on yarn C1.1]. 
knit + b23 1 ;knit loops: [326 on yarn C1.1]. 
knit + b26 1 ;knit loops: [327 on yarn C1.1]. 
knit + b29 1 ;knit loops: [328 on yarn C1.1]. 
knit + b32 1 ;knit loops: [329 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit - f30 1 ;knit loops: [330 on yarn C1.1]. 
knit - f27 1 ;knit loops: [331 on yarn C1.1]. 
knit - f24 1 ;knit loops: [332 on yarn C1.1]. 
knit - f21 1 ;knit loops: [333 on yarn C1.1]. 
knit - f18 1 ;knit loops: [334 on yarn C1.1]. 
knit - f15 1 ;knit loops: [335 on yarn C1.1]. 
knit - f12 1 ;knit loops: [336 on yarn C1.1]. 
knit - f9 1 ;knit loops: [337 on yarn C1.1]. 
knit - f6 1 ;knit loops: [338 on yarn C1.1]. 
knit - f3 1 ;knit loops: [339 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {318 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {316 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {314 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {312 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {310 on yarn C1.1} on b31 to f31
knit + b4 1 ;knit loops: [340 on yarn C1.1]. 
knit + f7 1 ;knit loops: [341 on yarn C1.1]. 
knit + b10 1 ;knit loops: [342 on yarn C1.1]. 
knit + f13 1 ;knit loops: [343 on yarn C1.1]. 
knit + b16 1 ;knit loops: [344 on yarn C1.1]. 
knit + f19 1 ;knit loops: [345 on yarn C1.1]. 
knit + b22 1 ;knit loops: [346 on yarn C1.1]. 
knit + f25 1 ;knit loops: [347 on yarn C1.1]. 
knit + b28 1 ;knit loops: [348 on yarn C1.1]. 
knit + f31 1 ;knit loops: [349 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit - b32 1 ;knit loops: [350 on yarn C1.1]. 
knit - b29 1 ;knit loops: [351 on yarn C1.1]. 
knit - b26 1 ;knit loops: [352 on yarn C1.1]. 
knit - b23 1 ;knit loops: [353 on yarn C1.1]. 
knit - b20 1 ;knit loops: [354 on yarn C1.1]. 
knit - b17 1 ;knit loops: [355 on yarn C1.1]. 
knit - b14 1 ;knit loops: [356 on yarn C1.1]. 
knit - b11 1 ;knit loops: [357 on yarn C1.1]. 
knit - b8 1 ;knit loops: [358 on yarn C1.1]. 
knit - b5 1 ;knit loops: [359 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit + f3 1 ;knit loops: [360 on yarn C1.1]. 
knit + f6 1 ;knit loops: [361 on yarn C1.1]. 
knit + f9 1 ;knit loops: [362 on yarn C1.1]. 
knit + f12 1 ;knit loops: [363 on yarn C1.1]. 
knit + f15 1 ;knit loops: [364 on yarn C1.1]. 
knit + f18 1 ;knit loops: [365 on yarn C1.1]. 
knit + f21 1 ;knit loops: [366 on yarn C1.1]. 
knit + f24 1 ;knit loops: [367 on yarn C1.1]. 
knit + f27 1 ;knit loops: [368 on yarn C1.1]. 
knit + f30 1 ;knit loops: [369 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {341 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {343 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {345 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {347 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {349 on yarn C1.1} on b31 to f31
knit - f31 1 ;knit loops: [370 on yarn C1.1]. 
knit - b28 1 ;knit loops: [371 on yarn C1.1]. 
knit - f25 1 ;knit loops: [372 on yarn C1.1]. 
knit - b22 1 ;knit loops: [373 on yarn C1.1]. 
knit - f19 1 ;knit loops: [374 on yarn C1.1]. 
knit - b16 1 ;knit loops: [375 on yarn C1.1]. 
knit - f13 1 ;knit loops: [376 on yarn C1.1]. 
knit - b10 1 ;knit loops: [377 on yarn C1.1]. 
knit - f7 1 ;knit loops: [378 on yarn C1.1]. 
knit - b4 1 ;knit loops: [379 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit + b5 1 ;knit loops: [380 on yarn C1.1]. 
knit + b8 1 ;knit loops: [381 on yarn C1.1]. 
knit + b11 1 ;knit loops: [382 on yarn C1.1]. 
knit + b14 1 ;knit loops: [383 on yarn C1.1]. 
knit + b17 1 ;knit loops: [384 on yarn C1.1]. 
knit + b20 1 ;knit loops: [385 on yarn C1.1]. 
knit + b23 1 ;knit loops: [386 on yarn C1.1]. 
knit + b26 1 ;knit loops: [387 on yarn C1.1]. 
knit + b29 1 ;knit loops: [388 on yarn C1.1]. 
knit + b32 1 ;knit loops: [389 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit - f30 1 ;knit loops: [390 on yarn C1.1]. 
knit - f27 1 ;knit loops: [391 on yarn C1.1]. 
knit - f24 1 ;knit loops: [392 on yarn C1.1]. 
knit - f21 1 ;knit loops: [393 on yarn C1.1]. 
knit - f18 1 ;knit loops: [394 on yarn C1.1]. 
knit - f15 1 ;knit loops: [395 on yarn C1.1]. 
knit - f12 1 ;knit loops: [396 on yarn C1.1]. 
knit - f9 1 ;knit loops: [397 on yarn C1.1]. 
knit - f6 1 ;knit loops: [398 on yarn C1.1]. 
knit - f3 1 ;knit loops: [399 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {378 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {376 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {374 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {372 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {370 on yarn C1.1} on b31 to f31
knit + b4 1 ;knit loops: [400 on yarn C1.1]. 
knit + f7 1 ;knit loops: [401 on yarn C1.1]. 
knit + b10 1 ;knit loops: [402 on yarn C1.1]. 
knit + f13 1 ;knit loops: [403 on yarn C1.1]. 
knit + b16 1 ;knit loops: [404 on yarn C1.1]. 
knit + f19 1 ;knit loops: [405 on yarn C1.1]. 
knit + b22 1 ;knit loops: [406 on yarn C1.1]. 
knit + f25 1 ;knit loops: [407 on yarn C1.1]. 
knit + b28 1 ;knit loops: [408 on yarn C1.1]. 
knit + f31 1 ;knit loops: [409 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit - b32 1 ;knit loops: [410 on yarn C1.1]. 
knit - b29 1 ;knit loops: [411 on yarn C1.1]. 
knit - b26 1 ;knit loops: [412 on yarn C1.1]. 
knit - b23 1 ;knit loops: [413 on yarn C1.1]. 
knit - b20 1 ;knit loops: [414 on yarn C1.1]. 
knit - b17 1 ;knit loops: [415 on yarn C1.1]. 
knit - b14 1 ;knit loops: [416 on yarn C1.1]. 
knit - b11 1 ;knit loops: [417 on yarn C1.1]. 
knit - b8 1 ;knit loops: [418 on yarn C1.1]. 
knit - b5 1 ;knit loops: [419 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit + f3 1 ;knit loops: [420 on yarn C1.1]. 
knit + f6 1 ;knit loops: [421 on yarn C1.1]. 
knit + f9 1 ;knit loops: [422 on yarn C1.1]. 
knit + f12 1 ;knit loops: [423 on yarn C1.1]. 
knit + f15 1 ;knit loops: [424 on yarn C1.1]. 
knit + f18 1 ;knit loops: [425 on yarn C1.1]. 
knit + f21 1 ;knit loops: [426 on yarn C1.1]. 
knit + f24 1 ;knit loops: [427 on yarn C1.1]. 
knit + f27 1 ;knit loops: [428 on yarn C1.1]. 
knit + f30 1 ;knit loops: [429 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {401 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {403 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {405 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {407 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {409 on yarn C1.1} on b31 to f31
knit - f31 1 ;knit loops: [430 on yarn C1.1]. 
knit - b28 1 ;knit loops: [431 on yarn C1.1]. 
knit - f25 1 ;knit loops: [432 on yarn C1.1]. 
knit - b22 1 ;knit loops: [433 on yarn C1.1]. 
knit - f19 1 ;knit loops: [434 on yarn C1.1]. 
knit - b16 1 ;knit loops: [435 on yarn C1.1]. 
knit - f13 1 ;knit loops: [436 on yarn C1.1]. 
knit - b10 1 ;knit loops: [437 on yarn C1.1]. 
knit - f7 1 ;knit loops: [438 on yarn C1.1]. 
knit - b4 1 ;knit loops: [439 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit + b5 1 ;knit loops: [440 on yarn C1.1]. 
knit + b8 1 ;knit loops: [441 on yarn C1.1]. 
knit + b11 1 ;knit loops: [442 on yarn C1.1]. 
knit + b14 1 ;knit loops: [443 on yarn C1.1]. 
knit + b17 1 ;knit loops: [444 on yarn C1.1]. 
knit + b20 1 ;knit loops: [445 on yarn C1.1]. 
knit + b23 1 ;knit loops: [446 on yarn C1.1]. 
knit + b26 1 ;knit loops: [447 on yarn C1.1]. 
knit + b29 1 ;knit loops: [448 on yarn C1.1]. 
knit + b32 1 ;knit loops: [449 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit - f30 1 ;knit loops: [450 on yarn C1.1]. 
knit - f27 1 ;knit loops: [451 on yarn C1.1]. 
knit - f24 1 ;knit loops: [452 on yarn C1.1]. 
knit - f21 1 ;knit loops: [453 on yarn C1.1]. 
knit - f18 1 ;knit loops: [454 on yarn C1.1]. 
knit - f15 1 ;knit loops: [455 on yarn C1.1]. 
knit - f12 1 ;knit loops: [456 on yarn C1.1]. 
knit - f9 1 ;knit loops: [457 on yarn C1.1]. 
knit - f6 1 ;knit loops: [458 on yarn C1.1]. 
knit - f3 1 ;knit loops: [459 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {438 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {436 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {434 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {432 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {430 on yarn C1.1} on b31 to f31
knit + b4 1 ;knit loops: [460 on yarn C1.1]. 
knit + f7 1 ;knit loops: [461 on yarn C1.1]. 
knit + b10 1 ;knit loops: [462 on yarn C1.1]. 
knit + f13 1 ;knit loops: [463 on yarn C1.1]. 
knit + b16 1 ;knit loops: [464 on yarn C1.1]. 
knit + f19 1 ;knit loops: [465 on yarn C1.1]. 
knit + b22 1 ;knit loops: [466 on yarn C1.1]. 
knit + f25 1 ;knit loops: [467 on yarn C1.1]. 
knit + b28 1 ;knit loops: [468 on yarn C1.1]. 
knit + f31 1 ;knit loops: [469 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit - b32 1 ;knit loops: [470 on yarn C1.1]. 
knit - b29 1 ;knit loops: [471 on yarn C1.1]. 
knit - b26 1 ;knit loops: [472 on yarn C1.1]. 
knit - b23 1 ;knit loops: [473 on yarn C1.1]. 
knit - b20 1 ;knit loops: [474 on yarn C1.1]. 
knit - b17 1 ;knit loops: [475 on yarn C1.1]. 
knit - b14 1 ;knit loops: [476 on yarn C1.1]. 
knit - b11 1 ;knit loops: [477 on yarn C1.1]. 
knit - b8 1 ;knit loops: [478 on yarn C1.1]. 
knit - b5 1 ;knit loops: [479 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit + f3 1 ;knit loops: [480 on yarn C1.1]. 
knit + f6 1 ;knit loops: [481 on yarn C1.1]. 
knit + f9 1 ;knit loops: [482 on yarn C1.1]. 
knit + f12 1 ;knit loops: [483 on yarn C1.1]. 
knit + f15 1 ;knit loops: [484 on yarn C1.1]. 
knit + f18 1 ;knit loops: [485 on yarn C1.1]. 
knit + f21 1 ;knit loops: [486 on yarn C1.1]. 
knit + f24 1 ;knit loops: [487 on yarn C1.1]. 
knit + f27 1 ;knit loops: [488 on yarn C1.1]. 
knit + f30 1 ;knit loops: [489 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {461 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {463 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {465 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {467 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {469 on yarn C1.1} on b31 to f31
knit - f31 1 ;knit loops: [490 on yarn C1.1]. 
knit - b28 1 ;knit loops: [491 on yarn C1.1]. 
knit - f25 1 ;knit loops: [492 on yarn C1.1]. 
knit - b22 1 ;knit loops: [493 on yarn C1.1]. 
knit - f19 1 ;knit loops: [494 on yarn C1.1]. 
knit - b16 1 ;knit loops: [495 on yarn C1.1]. 
knit - f13 1 ;knit loops: [496 on yarn C1.1]. 
knit - b10 1 ;knit loops: [497 on yarn C1.1]. 
knit - f7 1 ;knit loops: [498 on yarn C1.1]. 
knit - b4 1 ;knit loops: [499 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit + b5 1 ;knit loops: [500 on yarn C1.1]. 
knit + b8 1 ;knit loops: [501 on yarn C1.1]. 
knit + b11 1 ;knit loops: [502 on yarn C1.1]. 
knit + b14 1 ;knit loops: [503 on yarn C1.1]. 
knit + b17 1 ;knit loops: [504 on yarn C1.1]. 
knit + b20 1 ;knit loops: [505 on yarn C1.1]. 
knit + b23 1 ;knit loops: [506 on yarn C1.1]. 
knit + b26 1 ;knit loops: [507 on yarn C1.1]. 
knit + b29 1 ;knit loops: [508 on yarn C1.1]. 
knit + b32 1 ;knit loops: [509 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit - f30 1 ;knit loops: [510 on yarn C1.1]. 
knit - f27 1 ;knit loops: [511 on yarn C1.1]. 
knit - f24 1 ;knit loops: [512 on yarn C1.1]. 
knit - f21 1 ;knit loops: [513 on yarn C1.1]. 
knit - f18 1 ;knit loops: [514 on yarn C1.1]. 
knit - f15 1 ;knit loops: [515 on yarn C1.1]. 
knit - f12 1 ;knit loops: [516 on yarn C1.1]. 
knit - f9 1 ;knit loops: [517 on yarn C1.1]. 
knit - f6 1 ;knit loops: [518 on yarn C1.1]. 
knit - f3 1 ;knit loops: [519 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {498 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {496 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {494 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {492 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {490 on yarn C1.1} on b31 to f31
knit + b4 1 ;knit loops: [520 on yarn C1.1]. 
knit + f7 1 ;knit loops: [521 on yarn C1.1]. 
knit + b10 1 ;knit loops: [522 on yarn C1.1]. 
knit + f13 1 ;knit loops: [523 on yarn C1.1]. 
knit + b16 1 ;knit loops: [524 on yarn C1.1]. 
knit + f19 1 ;knit loops: [525 on yarn C1.1]. 
knit + b22 1 ;knit loops: [526 on yarn C1.1]. 
knit + f25 1 ;knit loops: [527 on yarn C1.1]. 
knit + b28 1 ;knit loops: [528 on yarn C1.1]. 
knit + f31 1 ;knit loops: [529 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit - b32 1 ;knit loops: [530 on yarn C1.1]. 
knit - b29 1 ;knit loops: [531 on yarn C1.1]. 
knit - b26 1 ;knit loops: [532 on yarn C1.1]. 
knit - b23 1 ;knit loops: [533 on yarn C1.1]. 
knit - b20 1 ;knit loops: [534 on yarn C1.1]. 
knit - b17 1 ;knit loops: [535 on yarn C1.1]. 
knit - b14 1 ;knit loops: [536 on yarn C1.1]. 
knit - b11 1 ;knit loops: [537 on yarn C1.1]. 
knit - b8 1 ;knit loops: [538 on yarn C1.1]. 
knit - b5 1 ;knit loops: [539 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit + f3 1 ;knit loops: [540 on yarn C1.1]. 
knit + f6 1 ;knit loops: [541 on yarn C1.1]. 
knit + f9 1 ;knit loops: [542 on yarn C1.1]. 
knit + f12 1 ;knit loops: [543 on yarn C1.1]. 
knit + f15 1 ;knit loops: [544 on yarn C1.1]. 
knit + f18 1 ;knit loops: [545 on yarn C1.1]. 
knit + f21 1 ;knit loops: [546 on yarn C1.1]. 
knit + f24 1 ;knit loops: [547 on yarn C1.1]. 
knit + f27 1 ;knit loops: [548 on yarn C1.1]. 
knit + f30 1 ;knit loops: [549 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {521 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {523 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {525 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {527 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {529 on yarn C1.1} on b31 to f31
knit - f31 1 ;knit loops: [550 on yarn C1.1]. 
knit - b28 1 ;knit loops: [551 on yarn C1.1]. 
knit - f25 1 ;knit loops: [552 on yarn C1.1]. 
knit - b22 1 ;knit loops: [553 on yarn C1.1]. 
knit - f19 1 ;knit loops: [554 on yarn C1.1]. 
knit - b16 1 ;knit loops: [555 on yarn C1.1]. 
knit - f13 1 ;knit loops: [556 on yarn C1.1]. 
knit - b10 1 ;knit loops: [557 on yarn C1.1]. 
knit - f7 1 ;knit loops: [558 on yarn C1.1]. 
knit - b4 1 ;knit loops: [559 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit + b5 1 ;knit loops: [560 on yarn C1.1]. 
knit + b8 1 ;knit loops: [561 on yarn C1.1]. 
knit + b11 1 ;knit loops: [562 on yarn C1.1]. 
knit + b14 1 ;knit loops: [563 on yarn C1.1]. 
knit + b17 1 ;knit loops: [564 on yarn C1.1]. 
knit + b20 1 ;knit loops: [565 on yarn C1.1]. 
knit + b23 1 ;knit loops: [566 on yarn C1.1]. 
knit + b26 1 ;knit loops: [567 on yarn C1.1]. 
knit + b29 1 ;knit loops: [568 on yarn C1.1]. 
knit + b32 1 ;knit loops: [569 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit - f30 1 ;knit loops: [570 on yarn C1.1]. 
knit - f27 1 ;knit loops: [571 on yarn C1.1]. 
knit - f24 1 ;knit loops: [572 on yarn C1.1]. 
knit - f21 1 ;knit loops: [573 on yarn C1.1]. 
knit - f18 1 ;knit loops: [574 on yarn C1.1]. 
knit - f15 1 ;knit loops: [575 on yarn C1.1]. 
knit - f12 1 ;knit loops: [576 on yarn C1.1]. 
knit - f9 1 ;knit loops: [577 on yarn C1.1]. 
knit - f6 1 ;knit loops: [578 on yarn C1.1]. 
knit - f3 1 ;knit loops: [579 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {558 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {556 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {554 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {552 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {550 on yarn C1.1} on b31 to f31
knit + b4 1 ;knit loops: [580 on yarn C1.1]. 
knit + f7 1 ;knit loops: [581 on yarn C1.1]. 
knit + b10 1 ;knit loops: [582 on yarn C1.1]. 
knit + f13 1 ;knit loops: [583 on yarn C1.1]. 
knit + b16 1 ;knit loops: [584 on yarn C1.1]. 
knit + f19 1 ;knit loops: [585 on yarn C1.1]. 
knit + b22 1 ;knit loops: [586 on yarn C1.1]. 
knit + f25 1 ;knit loops: [587 on yarn C1.1]. 
knit + b28 1 ;knit loops: [588 on yarn C1.1]. 
knit + f31 1 ;knit loops: [589 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit - b32 1 ;knit loops: [590 on yarn C1.1]. 
knit - b29 1 ;knit loops: [591 on yarn C1.1]. 
knit - b26 1 ;knit loops: [592 on yarn C1.1]. 
knit - b23 1 ;knit loops: [593 on yarn C1.1]. 
knit - b20 1 ;knit loops: [594 on yarn C1.1]. 
knit - b17 1 ;knit loops: [595 on yarn C1.1]. 
knit - b14 1 ;knit loops: [596 on yarn C1.1]. 
knit - b11 1 ;knit loops: [597 on yarn C1.1]. 
knit - b8 1 ;knit loops: [598 on yarn C1.1]. 
knit - b5 1 ;knit loops: [599 on yarn C1.1]. 
;Resetting to sheet s0:g3 of 3
; Peel sheet 0 relative to 0
; Peel sheet 1 relative to 0
xfer f4 b4 ;
xfer f7 b7 ;
xfer f10 b10 ;
xfer f13 b13 ;
xfer f16 b16 ;
xfer f19 b19 ;
xfer f22 b22 ;
xfer f25 b25 ;
xfer f28 b28 ;
xfer f31 b31 ;
; Peel sheet 2 relative to 0
knit + f3 1 ;knit loops: [600 on yarn C1.1]. 
knit + f6 1 ;knit loops: [601 on yarn C1.1]. 
knit + f9 1 ;knit loops: [602 on yarn C1.1]. 
knit + f12 1 ;knit loops: [603 on yarn C1.1]. 
knit + f15 1 ;knit loops: [604 on yarn C1.1]. 
knit + f18 1 ;knit loops: [605 on yarn C1.1]. 
knit + f21 1 ;knit loops: [606 on yarn C1.1]. 
knit + f24 1 ;knit loops: [607 on yarn C1.1]. 
knit + f27 1 ;knit loops: [608 on yarn C1.1]. 
knit + f30 1 ;knit loops: [609 on yarn C1.1]. 
;Resetting to sheet s1:g3 of 3
; Peel sheet 0 relative to 1
; Peel sheet 1 relative to 1
; Peel sheet 2 relative to 1
xfer b7 f7 ;Return loops {581 on yarn C1.1} on b7 to f7
xfer b13 f13 ;Return loops {583 on yarn C1.1} on b13 to f13
xfer b19 f19 ;Return loops {585 on yarn C1.1} on b19 to f19
xfer b25 f25 ;Return loops {587 on yarn C1.1} on b25 to f25
xfer b31 f31 ;Return loops {589 on yarn C1.1} on b31 to f31
knit - f31 1 ;knit loops: [610 on yarn C1.1]. 
knit - b28 1 ;knit loops: [611 on yarn C1.1]. 
knit - f25 1 ;knit loops: [612 on yarn C1.1]. 
knit - b22 1 ;knit loops: [613 on yarn C1.1]. 
knit - f19 1 ;knit loops: [614 on yarn C1.1]. 
knit - b16 1 ;knit loops: [615 on yarn C1.1]. 
knit - f13 1 ;knit loops: [616 on yarn C1.1]. 
knit - b10 1 ;knit loops: [617 on yarn C1.1]. 
knit - f7 1 ;knit loops: [618 on yarn C1.1]. 
knit - b4 1 ;knit loops: [619 on yarn C1.1]. 
;Resetting to sheet s2:g3 of 3
; Peel sheet 0 relative to 2
; Peel sheet 1 relative to 2
xfer b4 f4 ;
xfer b10 f10 ;
xfer b16 f16 ;
xfer b22 f22 ;
xfer b28 f28 ;
; Peel sheet 2 relative to 2
knit + b5 1 ;knit loops: [620 on yarn C1.1]. 
knit + b8 1 ;knit loops: [621 on yarn C1.1]. 
knit + b11 1 ;knit loops: [622 on yarn C1.1]. 
knit + b14 1 ;knit loops: [623 on yarn C1.1]. 
knit + b17 1 ;knit loops: [624 on yarn C1.1]. 
knit + b20 1 ;knit loops: [625 on yarn C1.1]. 
knit + b23 1 ;knit loops: [626 on yarn C1.1]. 
knit + b26 1 ;knit loops: [627 on yarn C1.1]. 
knit + b29 1 ;knit loops: [628 on yarn C1.1]. 
knit + b32 1 ;knit loops: [629 on yarn C1.1]. 
outhook 1; Cut yarn 1, disconnecting knitted piece
