# =============================================================================
# TEST RELEASE TO TEST PYPI WORKFLOW FOR KNITSCRIPT INTERPRETER
# =============================================================================
# This workflow builds and publishes your package to Test PyPI for testing
# before doing a real release to the main PyPI repository.
#
# WHEN THIS RUNS:
# - When you create a GitHub Release (published)
# - When you push a tag that starts with 'v' (like v0.0.19, v0.1.0, etc.)
#
# WHAT IT DOES:
# 1. Builds your Python package (wheel and source distribution)
# 2. Runs your full test suite to ensure quality
# 3. Validates the package meets PyPI standards
# 4. Publishes to Test PyPI (https://test.pypi.org)
# 5. Builds documentation for verification
#
# WHY USE TEST PYPI:
# - Test your package installation without affecting the real PyPI
# - Verify metadata, description, and dependencies work correctly
# - Practice the release process safely
# - Test that users can actually install and use your package
# =============================================================================

name: Test Release to PyPI

# =============================================================================
# WORKFLOW TRIGGERS
# =============================================================================
on:
  release:
    types: [published]              # Run when you publish a GitHub Release
  push:
    tags:
      - 'v*'                       # Run when you push any tag starting with 'v'
  workflow_dispatch:               # Allow manual triggering for testing

# =============================================================================
# WORKFLOW JOBS
# =============================================================================
jobs:

  # ===========================================================================
  # JOB 1: BUILD AND PUBLISH TO TEST PYPI
  # ===========================================================================
  test-release:
    name: Build and Publish to Test PyPI
    runs-on: ubuntu-latest
    environment: release           # Use GitHub environment for additional security

    steps:
    # -------------------------------------------------------------------------
    # STEP 1: Download repository content
    # -------------------------------------------------------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # -------------------------------------------------------------------------
    # STEP 2: Set up Python environment
    # -------------------------------------------------------------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # -------------------------------------------------------------------------
    # STEP 3: Install Poetry dependency manager
    # -------------------------------------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true

    # -------------------------------------------------------------------------
    # STEP 4: Configure Poetry for Test PyPI authentication
    # -------------------------------------------------------------------------
    - name: Configure Poetry for Test PyPI
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_TOKEN }}

    # -------------------------------------------------------------------------
    # STEP 5: Install all project dependencies
    # -------------------------------------------------------------------------
    - name: Install dependencies
      run: |
        poetry install

    # -------------------------------------------------------------------------
    # STEP 6: Run comprehensive test suite
    # -------------------------------------------------------------------------
    - name: Run full test suite
      run: |
        poetry run coverage run -m unittest discover tests -p "test_*.py" -v
        poetry run coverage report -m
      # Run all tests with coverage reporting before releasing
      # If ANY test fails, the workflow stops here (prevents broken releases)

    # -------------------------------------------------------------------------
    # STEP 7: Build the package
    # -------------------------------------------------------------------------
    - name: Build package
      run: |
        poetry build
      # This creates two files in the dist/ directory:
      # 1. A wheel file (.whl) - binary distribution for faster installation
      # 2. A source distribution (.tar.gz) - source code archive

    # -------------------------------------------------------------------------
    # STEP 8: Validate package before uploading
    # -------------------------------------------------------------------------
    - name: Check package quality
      run: |
        poetry run pip install twine
        poetry run twine check dist/*
      # Twine validates that your package:
      # - Has correct metadata format
      # - README renders properly on PyPI
      # - All required fields are present
      # - Package structure follows PyPI requirements

    # -------------------------------------------------------------------------
    # STEP 9: Publish to Test PyPI
    # -------------------------------------------------------------------------
    - name: Publish to Test PyPI
      run: |
        poetry publish -r testpypi
      # Uploads your package to Test PyPI (https://test.pypi.org)
      # After this step, your package will be available for testing:
      # pip install --index-url https://test.pypi.org/simple/ knitout-interpreter

    # -------------------------------------------------------------------------
    # STEP 10: Save build artifacts
    # -------------------------------------------------------------------------
    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-release-dist
        path: dist/
        retention-days: 90          # Keep test release artifacts longer

    # -------------------------------------------------------------------------
    # STEP 11: Create installation test script
    # -------------------------------------------------------------------------
    - name: Create installation verification script
      run: |
        cat > test_installation.py << 'EOF'
        #!/usr/bin/env python3
        """
        Test script to verify the package can be installed and imported from Test PyPI.
        """
        import subprocess
        import sys
        import tempfile
        import os

        def test_installation():
            """Test installing the package from Test PyPI in a clean environment."""
            # Extract version from the built package
            import glob
            wheel_files = glob.glob('dist/*.whl')
            if wheel_files:
                wheel_name = os.path.basename(wheel_files[0])
                # Extract package name and version from wheel filename
                # Format: knitout_interpreter-0.0.18-py3-none-any.whl
                parts = wheel_name.split('-')
                package_name = parts[0].replace('_', '-')  # Convert to PyPI format
                version = parts[1]

                print(f"Testing installation of {package_name} version {version}")
                print(f"Install command: pip install --index-url https://test.pypi.org/simple/ {package_name}=={version}")
                print(f"After installation, test with: python -c 'import knitout_interpreter; print(\"Import successful!\")'")
            else:
                print("No wheel file found in dist/")

        if __name__ == "__main__":
            test_installation()
        EOF
        python test_installation.py

    # -------------------------------------------------------------------------
    # STEP 12: Upload installation test script
    # -------------------------------------------------------------------------
    - name: Upload installation test script
      uses: actions/upload-artifact@v4
      with:
        name: installation-test-script
        path: test_installation.py
        retention-days: 30

  # ===========================================================================
  # JOB 2: BUILD DOCUMENTATION (For Verification)
  # ===========================================================================
  docs-build:
    name: Build Documentation (Verification)
    runs-on: ubuntu-latest
    needs: test-release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies with documentation tools
      run: |
        poetry install --with=docs

    # -------------------------------------------------------------------------
    # Build documentation with Sphinx
    # -------------------------------------------------------------------------
    - name: Build documentation
      run: |
        # Create basic Sphinx documentation if it doesn't exist
        if [ ! -f "docs/source/conf.py" ]; then
          mkdir -p docs/source
          poetry run sphinx-quickstart docs/source --quiet --project="Knitout Interpreter" \
            --author="Megan Hofmann" --release="$(poetry version -s)" --language="en" \
            --extensions=sphinx.ext.autodoc,sphinx.ext.viewcode,sphinx.ext.napoleon \
            --makefile --batchfile
        fi

        # Build the documentation
        poetry run sphinx-build -b html docs/source docs/build/html -W || \
        echo "Documentation build completed with warnings/errors - check logs above"

    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: built-documentation
        path: docs/build/html/
        retention-days: 30

# =============================================================================
# SETUP REQUIREMENTS FOR THIS WORKFLOW
# =============================================================================
#
# 1. GITHUB SECRETS (configure in repository settings → Secrets and variables → Actions):
#    - TEST_PYPI_API_TOKEN: Your Test PyPI API token
#      Get this from: https://test.pypi.org/manage/account/token/
#
# 2. GITHUB ENVIRONMENT (optional but recommended):
#    - Create 'release' environment in repository settings
#    - Add protection rules like requiring manual approval
#
# 3. TEST PYPI ACCOUNT:
#    - Create account at https://test.pypi.org
#    - Generate API token for your account
#    - Add token to GitHub Secrets as TEST_PYPI_API_TOKEN
#
# 4. PACKAGE VERSION:
#    - Update version in pyproject.toml before creating release
#    - Version should follow semantic versioning (e.g., 0.0.19, 0.1.0)
#
# =============================================================================

# =============================================================================
# HOW TO USE THIS WORKFLOW
# =============================================================================
#
# METHOD 1 - Create a GitHub Release:
# 1. Update version in pyproject.toml (e.g., version = "0.0.19")
# 2. Commit and push changes
# 3. Go to your repository on GitHub
# 4. Click "Releases" → "Create a new release"
# 5. Choose a tag (like v0.0.19) and title
# 6. Write release notes describing changes
# 7. Click "Publish release"
# 8. Workflow runs automatically
#
# METHOD 2 - Push a version tag:
# 1. Update version in pyproject.toml
# 2. Commit changes: git commit -am "Bump version to 0.0.19"
# 3. Create tag: git tag v0.0.19
# 4. Push: git push origin main --tags
# 5. Workflow runs automatically
#
# METHOD 3 - Manual trigger:
# 1. Go to Actions tab → "Test Release to PyPI" → "Run workflow"
#
# AFTER WORKFLOW COMPLETES:
# 1. Check Test PyPI: https://test.pypi.org/project/knitout-interpreter/
# 2. Test installation: pip install --index-url https://test.pypi.org/simple/ knitout-interpreter
# 3. Download and test the documentation artifacts
# 4. If everything works, proceed with real PyPI release using production workflow
#
# =============================================================================
